### ISSUE TITLE
Error when generating video

### ISSUE THREAD

**Issue by rikabi89** [Winfredy/SadTalker#100]
```
docs/sadtalker_logo.png: No such file or directory
The generated video is named ./results/9275e4fe-031c-49ad-98ab-7315103bd2b8/tmpn8pewopf##trumpcity17-0-100_full.mp4
face enhancer....
Face Enhancer::   0%|                                                                                                       | 0/86 [00:00<?, ?it/s][ WARN:20@2281.549] global loadsave.cpp:244 cv::findDecoder imread_('.'): can't open/read file: check file path/integrity
Face Enhancer::   0%|                                                                                                       | 0/86 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "H:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "H:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "H:\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 121, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "H:\stable-diffusion-webui/extensions/SadTalker\src\facerender\animate.py", line 202, in generate
    enhanced_images = face_enhancer(full_video_path, method=enhancer, bg_upsampler=background_enhancer)
  File "H:\stable-diffusion-webui/extensions/SadTalker\src\utils\face_enhancer.py", line 81, in enhancer
    cropped_faces, restored_faces, r_img = restorer.enhance(
  File "H:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\gfpgan\utils.py", line 109, in enhance
    self.face_helper.read_image(img)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 114, in read_image
    if np.max(img) > 256:  # 16-bit image
TypeError: '>' not supported between instances of 'NoneType' and 'int'

```

However can the video file in : `H:\stable-diffusion-webui\results\9275e4fe-031c-49ad-98ab-7315103bd2b8` but it has no upscaling. Any idea?

**Comment by vinthony** [comment]
try to download the lastest version of code
