### ISSUE TITLE
./docs/sadtalker_log.png: No such file or directory

### ISSUE THREAD

**Issue by lurj7988** [Winfredy/SadTalker#101]
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '4ec5c489-5484-4d11-a11f-1a2677c0d7ab.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.27.100
  Duration: 00:00:04.40, start: 0.000000, bitrate: 1850 kb/s
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 1058x1058 [SAR 1:1 DAR 1:1], 1848 kb/s, 25 fps, 25 tbr, 12800 tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Guessed Channel Layout for Input Stream #1.0 : mono
Input #1, wav, from './results/2023_04_10_21.46.48/1681133372014.wav':
  Duration: 00:00:04.40, bitrate: 256 kb/s
    Stream #1:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, mp4, to 'a5b115f0-b926-4e9a-90f0-21593adf70c9.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 1058x1058 [SAR 1:1 DAR 1:1], q=2-31, 1848 kb/s, 25 fps, 25 tbr, 12800 tbn, 12800 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 69 kb/s
    Metadata:
      encoder         : Lavc58.54.100 aac
frame=  110 fps=0.0 q=-1.0 Lsize=    1034kB time=00:00:04.41 bitrate=1918.2kbits/s speed= 225x    
video:993kB audio:38kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.320434%
[aac @ 0x55f0c833f740] Qavg: 12543.789
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'a5b115f0-b926-4e9a-90f0-21593adf70c9.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:04.46, start: 0.000000, bitrate: 1897 kb/s
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 1058x1058 [SAR 1:1 DAR 1:1], 1848 kb/s, 25 fps, 25 tbr, 12800 tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
./docs/sadtalker_log.png: No such file or directory
The generated video is named ./results/2023_04_10_21.46.48/20230410212430##1681133372014_full.mp4
face enhancer....
Face Enhancer::   0%|                                                                                                                                                  | 0/68 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 112, in main
    animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "/opt/SadTalker/src/facerender/animate.py", line 202, in generate
    enhanced_images = face_enhancer(full_video_path, method=enhancer, bg_upsampler=background_enhancer)
  File "/opt/SadTalker/src/utils/face_enhancer.py", line 81, in enhancer
    cropped_faces, restored_faces, r_img = restorer.enhance(
  File "/opt/miniconda3/envs/sadtalker/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/sadtalker/lib/python3.8/site-packages/gfpgan/utils.py", line 109, in enhance
    self.face_helper.read_image(img)
  File "/opt/miniconda3/envs/sadtalker/lib/python3.8/site-packages/facexlib/utils/face_restoration_helper.py", line 114, in read_image
    if np.max(img) > 256:  # 16-bit image
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by vinthony** [comment]
fixed in the latest version. a small mistake between `sadtalker_log.png` and `sadtalker_logo.png`.
