### ISSUE TITLE
Error when generating

### ISSUE THREAD

**Issue by skullzy77** [Winfredy/SadTalker#103]
It seems to start off working but then stops and gives me this...

    IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (256, 239) to (256, 240) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility). 'ffmpeg' is not recognized as an internal or external command, operable program or batch file. Traceback (most recent call last): File "C:\Users\seans\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 816, in move os.rename(src, real_dst) FileNotFoundError: [WinError 2] The system cannot find the file specified: 'f284dce1-d4c4-4dd3-bb95-5f3ede94b837.mp4' -> './results/f2cf245d-96c9-4a2a-94f9-cb1b76b9fa2a\tmptnhxxmlz##2tg1tecd6.mp4'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last): File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict output = await app.get_blocks().process_api( File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api result = await self.call_function( File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function prediction = await anyio.to_thread.run_sync( File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread return await future File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio_backends_asyncio.py", line 867, in run result = context.run(func, args) File "C:\AI\stable-diffusion-webui\modules\call_queue.py", line 15, in f res = func(args, **kwargs) File "C:\AI\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 121, in test return_path = self.animate_from_coeff.generate(data, save_dir, pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess) File "C:\AI\stable-diffusion-webui/extensions/SadTalker\src\facerender\animate.py", line 183, in generate save_video_with_watermark(path, new_audio_path, av_path, watermark= False) File "C:\AI\stable-diffusion-webui/extensions/SadTalker\src\utils\videoio.py", line 26, in save_video_with_watermark shutil.move(temp_file, save_path) File "C:\Users\seans\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 836, in move copy_function(src, real_dst) File "C:\Users\seans\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2 copyfile(src, dst, follow_symlinks=follow_symlinks) File "C:\Users\seans\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile with open(src, 'rb') as fsrc: FileNotFoundError: [Errno 2] No such file or directory: 'f284dce1-d4c4-4dd3-bb95-5f3ede94b837.mp4
`

**Comment by vinthony** [comment]
it seems the intermedia images are not produced successfully. Try different images and let me know more details about the logs.

**Comment by skullzy77** [comment]
> it seems the intermedia images are not produced successfully. Try different images and let me know more details about the logs.

I've tried with 6 images now and get the same error each time. Not sure what more detail to give, what I posted above was the entire error. Sorry, I'm new to all this.

**Comment by vinthony** [comment]
Ok, which mode are you using? `resize`, `crop` or `full`?

**Comment by skullzy77** [comment]
I just tried resize and full and am getting the same error. Watching it in cmd it goes fine until face renderer finishes and then it errors.

**Comment by skullzy77** [comment]
Seems I don't have ffmpeg installed, I thought I did. I followed the instructions to install it but then I get this when doing ffmpeg -version

C:\Windows\System32>ffmpeg -version
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.

**Comment by skullzy77** [comment]
Ok I got it! I hadn't set the path properly for ffmpeg. Everything seems to be working now. Thanks for your help!
