### ISSUE TITLE
Bunch of sadtalker depencies fail for auto1111

### ISSUE THREAD

**Issue by bbecausereasonss** [Winfredy/SadTalker#106]
Have tried 3x new venv installs. Still not installing everything properly for auto's extension.

face-alignment False
Installing requirements for SadTalker
imageio True
imageio-ffmpeg False
Installing requirements for SadTalker
librosa False
Installing requirements for SadTalker
pydub True
scipy True
tqdm True
yacs False
Installing requirements for SadTalker
pyyaml False
Installing requirements for SadTalker
dlib False
Installing requirements for SadTalker
gfpgan True
load Sadtalker Checkpoints from C:\Users\xxxx\Deep\SadTalker\checkpoints

**Comment by bbecausereasonss** [comment]
Errors on generate.

To create a public link, set `share=True` in `launch()`.
Startup time: 28.9s (import torch: 2.3s, import gradio: 1.5s, import ldm: 0.5s, other imports: 1.1s, list SD models: 0.1s, load scripts: 3.9s, load SD checkpoint: 5.4s, create ui: 13.8s, gradio launch: 0.1s).
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 197, in audio_from_file
    audio = AudioSegment.from_file(filename)
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\xxxx\anaconda3\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\xxxx\anaconda3\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 2147, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 207, in audio_from_file
    raise RuntimeError(msg) from e
RuntimeError: Cannot load audio from file: `ffprobe` not found. Please install `ffmpeg` in your system to use non-WAV audio file formats and make sure `ffprobe` is in your PATH.
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 197, in audio_from_file
    audio = AudioSegment.from_file(filename)
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\xxxx\anaconda3\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\xxxx\anaconda3\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 2147, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 207, in audio_from_file
    raise RuntimeError(msg) from e
RuntimeError: Cannot load audio from file: `ffprobe` not found. Please install `ffmpeg` in your system to use non-WAV audio file formats and make sure `ffprobe` is in your PATH.

**Comment by vinthony** [comment]
refer to #103
