### ISSUE TITLE
webui 安装报错（M1）

### ISSUE THREAD

**Issue by Osub** [Winfredy/SadTalker#109]
```
pyyaml False
Installing requirements for SadTalker
dlib False
Installing requirements for SadTalker
Error executing callback ui_tabs_callback for /Users/nft/Desktop/work/AIDEMO/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py
Traceback (most recent call last):
  File "/Users/nft/Desktop/work/AIDEMO/stable-diffusion-webui/modules/script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "/Users/nft/Desktop/work/AIDEMO/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 68, in on_ui_tabs
    install()
  File "/Users/nft/Desktop/work/AIDEMO/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 54, in install
    launch.run_pip("install "+ v, "requirements for SadTalker")
  File "/Users/nft/Desktop/work/AIDEMO/stable-diffusion-webui/launch.py", line 137, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/Users/nft/Desktop/work/AIDEMO/stable-diffusion-webui/launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for SadTalker.
Command: "/Users/nft/Desktop/work/AIDEMO/stable-diffusion-webui/venv/bin/python3.10" -m pip install dlib-bin --prefer-binary
Error code: 1
stdout: <empty>
stderr: ERROR: Could not find a version that satisfies the requirement dlib-bin (from versions: none)
ERROR: No matching distribution found for dlib-bin

```

**Comment by vinthony** [comment]
mac 推荐使用online service。 比如colab。我尝试装过之后发现跑起来很慢， 如果必须要安装，可以在`sdwebui/extensions/SadTalker/scripts/extensions.py中`把 https://github.com/Winfredy/SadTalker/blob/29160b6d618bef998def1747ce791c94bde9b6f4/scripts/extension.py#L47, 改成:

```
"dlib":"dlib",
```

**Comment by imtiger** [comment]
> mac 推荐使用online service。 比如colab。我尝试装过之后发现跑起来很慢， 如果必须要安装，可以在`sdwebui/extensions/SadTalker/scripts/extensions.py中`把
> 
> https://github.com/Winfredy/SadTalker/blob/29160b6d618bef998def1747ce791c94bde9b6f4/scripts/extension.py#L47
> 
> , 改成:
> ```
> "dlib":"dlib",
> ```
我改为了dlib，但是webui安装的时候又报了这个错误。
/apps/stable-diffusion-webui-install/python/3.10.10/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by vinthony** [comment]
这里应该是python版本太高了。

**Comment by allanming** [comment]
同样的问题，dlib难道不支持m1/2的芯片？

**Comment by guangmean** [comment]
I fixed this issue on Mac M1
============= modify the value from "dlib-bin" to "dlib" in requirements.txt ============
numpy==1.23.4
face_alignment==1.3.5
imageio==2.19.3
imageio-ffmpeg==0.4.7
librosa==0.9.2 # 
numba
resampy==0.3.1
pydub==0.25.1 
scipy==1.10.1
kornia==0.6.8
tqdm
yacs==0.1.8
pyyaml  
joblib==1.1.0
scikit-image==0.19.3
basicsr==1.4.2
facexlib==0.3.0
gradio
gfpgan
dlib-bin **_# Modify this line to "dlib", and then pip install -r requirements.txt will success_**
av

==================================
Successfully installed 💯

**Comment by TiffanyWU888** [comment]
> mac 推荐使用online service。 比如colab。我尝试装过之后发现跑起来很慢， 如果必须要安装，可以在`sdwebui/extensions/SadTalker/scripts/extensions.py中`把 https://github.com/Winfredy/SadTalker/blob/29160b6d618bef998def1747ce791c94bde9b6f4/scripts/extension.py#L47, 改成:
> 
> 
> 
> ```
> 
> "dlib":"dlib",
> 
> ```

哇！我終於看到一位是成功安装的
可以教？

**Comment by TiffanyWU888** [comment]
無數次安装失敗   請問有建議的安装教學？
