### ISSUE TITLE
TypeError: snapshot_download() got an unexpected keyword argument 'local_dir'

### ISSUE THREAD

**Issue by GitHongWu** [Winfredy/SadTalker#111]
I am getting the following error message
```
Error executing callback ui_tabs_callback for /workspace/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/modules/script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "/workspace/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 69, in on_ui_tabs
    install()
  File "/workspace/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 65, in install
    download_model(paths.script_path+'/extensions/SadTalker/checkpoints')
  File "/workspace/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 15, in download_model
    snapshot_download(repo_id=REPO_ID, local_dir=local_dir, local_dir_use_symlinks=True)
  File "/workspace/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
TypeError: snapshot_download() got an unexpected keyword argument 'local_dir'
```

The output of print(local_dir) is "/workspace/stable-diffusion-webui/extensions/SadTalker/checkpoints"

I am wondering if this related with huggingface_hub version issue, when I ran `python -c "import huggingface_hub; print(huggingface_hub.__version__)"`
I got 0.12.0

**Comment by GitHongWu** [comment]
Never mind, my huggingface_hub is ou tof date, sovled it by running `pip install --upgrade huggingface_hub`
