### ISSUE TITLE
Webui on Google Colab - crash SadTalker

### ISSUE THREAD

**Issue by hparenty** [Winfredy/SadTalker#119]
Hello, 
  
  (I'm not technical) I'm trying to run SadTalker extension on WebUI Google Colab from StableDiffusionUI_ngrok_sagiodev.ipynb.
  But I got this issue.
  
  Could you help me ?
  
  Thank you ! 
  
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/SadTalker/src/gradio_demo.py", line 64, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "/content/stable-diffusion-webui/extensions/SadTalker/src/utils/preprocess.py", line 46, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "/content/stable-diffusion-webui/extensions/SadTalker/src/face3d/extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device=device)
  File "/usr/local/lib/python3.9/dist-packages/face_alignment/api.py", line 77, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose, **face_detector_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/face_alignment/detection/sfd/sfd_detector.py", line 30, in __init__
    self.face_detector.load_state_dict(model_weights)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1994, in load_state_dict
    raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.

**Comment by vinthony** [comment]
may directly run our colab demo: https://colab.research.google.com/github/Winfredy/SadTalker/blob/main/quick_demo.ipynb

**Comment by vinthony** [comment]
it seems the checkpoint are not downloaded correctly.

**Comment by Qian-Hao** [comment]
我也遇到相同的问题

Error verifying pickled file from /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SadTalker/checkpoints/hub/checkpoints/s3fd-619a316812.pth:
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/usr/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/safe.py", line 102, in check_pt
    unpickler.load()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/safe.py", line 62, in find_class
    raise Exception(f"global '{module}/{name}' is forbidden")
Exception: global 'torch._utils/_rebuild_tensor' is forbidden


The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.


Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SadTalker/src/gradio_demo.py", line 64, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SadTalker/src/utils/preprocess.py", line 46, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SadTalker/src/face3d/extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device=device)
  File "/usr/local/lib/python3.9/dist-packages/face_alignment/api.py", line 77, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose, **face_detector_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/face_alignment/detection/sfd/sfd_detector.py", line 30, in __init__
    self.face_detector.load_state_dict(model_weights)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1624, in load_state_dict
    raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.

**Comment by vinthony** [comment]
Fixed, if you have any problem please reopen it.

**Comment by Qian-Hao** [comment]
> it seems the checkpoint are not downloaded correctly.

checkpoint如何下载？

**Comment by vinthony** [comment]
> > it seems the checkpoint are not downloaded correctly.
> 
> checkpoint如何下载？

这个不是checkpoint的问题，是有一个第三方的包不安全。已经修复了。

**Comment by Qian-Hao** [comment]
> stable-diffusion-webui 需要 --disable-safe-unpickle，参考：https://github.com/Winfredy/SadTalker#sd-webui-extension 和#78

这个命令是加在webui-user.sh里吗，我在google云盘修改后不生效
