### ISSUE TITLE
Automatic1111 

### ISSUE THREAD

**Issue by niatro** [Winfredy/SadTalker#123]
Hi looks like we must to have installed automatic1111 in C: otherwise Throw a error

**Comment by syousip** [comment]
same here

**Comment by Ionaut** [comment]
Yep. me too

**Comment by vinthony** [comment]
it seems some thing about the huggingface_hub library, i will fixed it today. 

in advanced, you can try to set the `local_dir_use_symlinks` to false.
File "X:\AyudantesAI\AUTOMATIC_1111\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 14, in download_model
snapshot_download(repo_id=REPO_ID, local_dir=local_dir, local_dir_use_symlinks=True)

**Comment by vinthony** [comment]
Or you can set the %SADTALKER_CHECKPOINTS% in your bash file in advanced.

**Comment by vinthony** [comment]
https://github.com/huggingface/huggingface_hub/issues/1385 it is something about huggingface_hub

**Comment by wukenny11111** [comment]
Loading weights [fc2511737a] from D:\AI\novelai-webui-aki-v3\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
Creating model from config: D:\AI\novelai-webui-aki-v3\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 3.0s (create model: 0.4s, apply weights to model: 0.8s, move model to device: 0.7s, load textual inversion embeddings: 1.0s).
face-alignment False
Installing requirements for SadTalker
imageio True
imageio-ffmpeg False
Installing requirements for SadTalker
librosa True
pydub True
scipy True
tqdm True
yacs True
pyyaml False
Installing requirements for SadTalker
dlib True
huggingface_hub True
gfpgan True
Error executing callback ui_tabs_callback for D:\AI\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py
Traceback (most recent call last):
  File "D:\AI\novelai-webui-aki-v3\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\AI\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py", line 69, in on_ui_tabs
    install()
  File "D:\AI\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py", line 65, in install
    download_model(paths.script_path+'/extensions/SadTalker/checkpoints')
  File "D:\AI\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py", line 14, in download_model
    snapshot_download(repo_id=REPO_ID, local_dir=local_dir, local_dir_use_symlinks=false)
NameError: name 'false' is not defined
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。





你好，我设置成false了 还是有很多报错！

**Comment by vinthony** [comment]
大写？
```
snapshot_download(repo_id=REPO_ID, local_dir=local_dir, local_dir_use_symlinks=False)
```

**Comment by wukenny11111** [comment]
我在webui-user.bat里面也设置了，模型位置，并将模型放进去了，还是有报错，webui上也没有相关按钮
set SADTALKER_CHECKPOINTS=.\extensions\SadTalker\checkpoints

**Comment by vinthony** [comment]
> 我在webui-user.bat里面也设置了，模型位置，并将模型放进去了，还是有报错，webui上也没有相关按钮 set SADTALKER_CHECKPOINTS=.\extensions\SadTalker\checkpoints

这里确定启动的时候用`webui-user.bat`

**Comment by vinthony** [comment]
> > 我在webui-user.bat里面也设置了，模型位置，并将模型放进去了，还是有报错，webui上也没有相关按钮 set SADTALKER_CHECKPOINTS=.\extensions\SadTalker\checkpoints
> 
> 这里确定启动的时候用`webui-user.bat`

没有相关按钮是安装有问题，可以给一些log

**Comment by wukenny11111** [comment]
> > > 我在webui-user.bat里面也设置了，模型位置，并将模型放进去了，还是有报错，webui上也没有相关按钮 set SADTALKER_CHECKPOINTS=.\extensions\SadTalker\checkpoints
> > 
> > 
> > 这里确定启动的时候用`webui-user.bat`
> 
> 没有相关按钮是安装有问题，可以给一些log

Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI

Launching Web UI with arguments: --xformers --no-half --autolaunch --api
[AddNet] Updating model hashes...

[AddNet] Updating model hashes...

Loading weights [fc2511737a] from D:\AI\novelai-webui-aki-v3\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
Creating model from config: D:\AI\novelai-webui-aki-v3\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 3.1s (create model: 0.5s, apply weights to model: 0.7s, move model to device: 0.8s, load textual inversion embeddings: 1.1s).
face-alignment False
Installing requirements for SadTalker
imageio True
imageio-ffmpeg False
Installing requirements for SadTalker
librosa True
pydub True
scipy True
tqdm True
yacs True
pyyaml False
Installing requirements for SadTalker
dlib True
huggingface_hub True
gfpgan True
Error executing callback ui_tabs_callback for D:\AI\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py
Traceback (most recent call last):
  File "D:\AI\novelai-webui-aki-v3\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\AI\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py", line 69, in on_ui_tabs
    install()
  File "D:\AI\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py", line 65, in install
    download_model(paths.script_path+'/extensions/SadTalker/checkpoints')
  File "D:\AI\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py", line 14, in download_model
    snapshot_download(repo_id=REPO_ID, local_dir=local_dir, local_dir_use_symlinks=False)
  File "D:\AI\novelai-webui-aki-v3\py310\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "D:\AI\novelai-webui-aki-v3\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
TypeError: snapshot_download() got an unexpected keyword argument 'local_dir'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。


启动信息都在这里了

**Comment by vinthony** [comment]
这个是huggingface_hub 的版本问题，确定第48行：

```
"huggingface_hub":"huggingface_hub==0.13.4",
```

**Comment by wukenny11111** [comment]
> 这个是huggingface_hub 的版本问题，确定第48行：
> 
> ```
> "huggingface_hub":"huggingface_hub==0.13.4",
> ```

代码这里没有问题，我这里是
 "huggingface_hub":"huggingface_hub==0.13.4",

**Comment by jet3004** [comment]
Little confused on the timeline on if this is fixed or it is still pending – SadTalker was working great as extension for me in A11 on Mac. Then it updated and broke with the HuggingFace code above. I did what you said @vinthony and I checked to see if "    snapshot_download(repo_id=REPO_ID, local_dir=local_dir, local_dir_use_symlinks=False)" was set to False and it already was. I updated the huggingface like @Wauplin said...But still on latest **_f797c071 (Thu Apr 13 15:08:47 2023)_**
 it's reinstalling every time, doesn't load the tab, and shows this in terminal:
 
`Installing requirements for SadTalker
imageio-ffmpeg False
Installing requirements for SadTalker
pyyaml False
Installing requirements for SadTalker
Found existing installation: huggingface-hub 0.14.0.dev0
Uninstalling huggingface-hub-0.14.0.dev0:
  Successfully uninstalled huggingface-hub-0.14.0.dev0
Collecting git+https://github.com/huggingface/huggingface_hub@main
  Cloning https://github.com/huggingface/huggingface_hub (to revision main) to /private/var/folders/f3/nrjf0tzs2jj89dx48mvjw8200000gn/T/pip-req-build-al1db96d
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/huggingface_hub /private/var/folders/f3/nrjf0tzs2jj89dx48mvjw8200000gn/T/pip-req-build-al1db96d
  Resolved https://github.com/huggingface/huggingface_hub to commit b38dd9cab73472ebf4903423561973363dda19f4
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: packaging>=20.9 in ./venv/lib/python3.10/site-packages (from huggingface-hub==0.14.0.dev0) (23.0)
Requirement already satisfied: tqdm>=4.42.1 in ./venv/lib/python3.10/site-packages (from huggingface-hub==0.14.0.dev0) (4.64.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./venv/lib/python3.10/site-packages (from huggingface-hub==0.14.0.dev0) (4.5.0)
Requirement already satisfied: filelock in ./venv/lib/python3.10/site-packages (from huggingface-hub==0.14.0.dev0) (3.9.0)
Requirement already satisfied: fsspec in ./venv/lib/python3.10/site-packages (from huggingface-hub==0.14.0.dev0) (2023.1.0)
Requirement already satisfied: pyyaml>=5.1 in ./venv/lib/python3.10/site-packages (from huggingface-hub==0.14.0.dev0) (6.0)
Requirement already satisfied: requests in ./venv/lib/python3.10/site-packages (from huggingface-hub==0.14.0.dev0) (2.28.2)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.10/site-packages (from requests->huggingface-hub==0.14.0.dev0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.10/site-packages (from requests->huggingface-hub==0.14.0.dev0) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests->huggingface-hub==0.14.0.dev0) (1.26.14)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.10/site-packages (from requests->huggingface-hub==0.14.0.dev0) (3.0.1)
Building wheels for collected packages: huggingface-hub
  Building wheel for huggingface-hub (pyproject.toml) ... done
  Created wheel for huggingface-hub: filename=huggingface_hub-0.14.0.dev0-py3-none-any.whl size=206741 sha256=b76e49655d802ea53cfb260ded2c2570f6f5dec612d46117e371f106a8405f92
  Stored in directory: /private/var/folders/f3/nrjf0tzs2jj89dx48mvjw8200000gn/T/pip-ephem-wheel-cache-8_ow4y_j/wheels/9e/13/6f/0a9fb9f2699c2245faeb9f35bd1ab98a43de539dc433a61b49
Successfully built huggingface-hub
Installing collected packages: huggingface-hub
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 3.19.6 which is incompatible.
Successfully installed huggingface-hub-0.14.0.dev0
Fetching 22 files:   0%|                                 | 0/22 [00:00<?, ?it/s]
Error executing callback ui_tabs_callback for /Users/jet/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py
Traceback (most recent call last):
  File "/Users/jet/stable-diffusion-webui/modules/script_callbacks.py", line 125, in ui_tabs_callback
	res += c.callback() or []
  File "/Users/jet/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 74, in on_ui_tabs
	install()
  File "/Users/jet/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 70, in install
	download_model(paths.script_path+'/extensions/SadTalker/checkpoints')
  File "/Users/jet/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 14, in download_model
	snapshot_download(repo_id=REPO_ID, local_dir=local_dir, local_dir_use_symlinks=False)
  File "/Users/jet/stable-diffusion-webui/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
	return fn(*args, **kwargs)
  File "/Users/jet/stable-diffusion-webui/venv/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 239, in snapshot_download
	thread_map(
  File "/Users/jet/stable-diffusion-webui/venv/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 94, in thread_map
	return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/Users/jet/stable-diffusion-webui/venv/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 76, in _executor_map
	return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "/Users/jet/stable-diffusion-webui/venv/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
	for obj in iterable:
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
	yield _result_or_cancel(fs.pop())
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
	return fut.result(timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/concurrent/futures/_base.py", line 458, in result
	return self.__get_result()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
	raise self._exception
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/concurrent/futures/thread.py", line 58, in run
	result = self.fn(*self.args, **self.kwargs)
  File "/Users/jet/stable-diffusion-webui/venv/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 215, in _inner_hf_hub_download
	return hf_hub_download(
  File "/Users/jet/stable-diffusion-webui/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
	return fn(*args, **kwargs)
  File "/Users/jet/stable-diffusion-webui/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1300, in hf_hub_download
	return _to_local_dir(blob_path, local_dir, relative_filename, use_symlinks=local_dir_use_symlinks)
  File "/Users/jet/stable-diffusion-webui/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1610, in _to_local_dir
	shutil.copyfile(real_blob_path, local_dir_filepath)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/shutil.py", line 234, in copyfile
	raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/Users/jet/.cache/huggingface/hub/models--vinthony--SadTalker/blobs/50ccb1de2d4dad19b280047bdc1c5a3af7438ff9' and '/Users/jet/stable-diffusion-webui/extensions/SadTalker/checkpoints/.gitattributes' are the same file
`

**Comment by vinthony** [comment]
> Hey everyone 👋 I can confirm it was an issue in `huggingface_hub` when copying file to local directory that is not on the same volume (on Windows). It should be fixed by [huggingface/huggingface_hub#1437](https://github.com/huggingface/huggingface_hub/pull/1437). For context, with this fix files will not be symlinked as it's not supported but entirely copy-pasted instead. To get the fix, you must install from source:
> 
> ```
> pip install git+https://github.com/huggingface/huggingface_hub@main
> ```
> 
> Otherwise, I'll be published in next `hfh` release.
> 
> (disclaimer: I'm a maintainer of `huggingface_hub`)

Thanks for this information. I will update the code about this release.

**Comment by MadHalaster** [comment]
Still having issue even with the latest update for both huggingface, and SadTalker.
I have updated SadTalker, and I have ran "pip install git+https://github.com/huggingface/huggingface_hub@main" in the venv, and verified that my current version is 0.14.0.dev0. I have also set SADTALKER_CHECKPOINTS=.\extensions\SadTalker\checkpoints in the web-user.bat.

I am receiving the following error:
```
Installing requirements for SadTalker
"
            SadTalker are trying to downloaded all the files from hugging face, which will take a long time.

            To avoid this, please manually set the SADTALKER_CHECKPOINTS in `webui_user.bat`(windows) or `webui_user.sh`(linux)

WARNING: Ignoring invalid distribution -rotobuf (d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages)
Found existing installation: huggingface-hub 0.14.0.dev0
Uninstalling huggingface-hub-0.14.0.dev0:
  Successfully uninstalled huggingface-hub-0.14.0.dev0
WARNING: Ignoring invalid distribution -rotobuf (d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages)
Collecting git+https://github.com/huggingface/huggingface_hub@main
  Cloning https://github.com/huggingface/huggingface_hub (to revision main) to c:\users\MyName\appdata\local\temp\pip-req-build-fpvfnhbp
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/huggingface_hub 'C:\Users\MyName\AppData\Local\Temp\pip-req-build-fpvfnhbp'
  Resolved https://github.com/huggingface/huggingface_hub to commit b38dd9cab73472ebf4903423561973363dda19f4
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub==0.14.0.dev0) (3.11.0)
Requirement already satisfied: tqdm>=4.42.1 in d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub==0.14.0.dev0) (4.64.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub==0.14.0.dev0) (4.5.0)
Requirement already satisfied: requests in d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub==0.14.0.dev0) (2.28.2)
Requirement already satisfied: packaging>=20.9 in d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub==0.14.0.dev0) (23.0)
Requirement already satisfied: fsspec in d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub==0.14.0.dev0) (2023.4.0)
Requirement already satisfied: pyyaml>=5.1 in d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub==0.14.0.dev0) (6.0)
Requirement already satisfied: colorama in d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tqdm>=4.42.1->huggingface-hub==0.14.0.dev0) (0.4.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->huggingface-hub==0.14.0.dev0) (1.26.15)
Requirement already satisfied: idna<4,>=2.5 in d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->huggingface-hub==0.14.0.dev0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->huggingface-hub==0.14.0.dev0) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->huggingface-hub==0.14.0.dev0) (3.1.0)
Building wheels for collected packages: huggingface-hub
  Building wheel for huggingface-hub (pyproject.toml) ... done
  Created wheel for huggingface-hub: filename=huggingface_hub-0.14.0.dev0-py3-none-any.whl size=208064 sha256=78ab75ce26d5cc41835da801659bd73d05ede25e17d848cd5b90b41e23222fd8
  Stored in directory: C:\Users\MyName\AppData\Local\Temp\pip-ephem-wheel-cache-b4y09emu\wheels\9e\13\6f\0a9fb9f2699c2245faeb9f35bd1ab98a43de539dc433a61b49
Successfully built huggingface-hub
WARNING: Ignoring invalid distribution -rotobuf (d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages)
Installing collected packages: huggingface-hub
WARNING: Ignoring invalid distribution -rotobuf (d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 4.22.1 which is incompatible.
Successfully installed huggingface-hub-0.14.0.dev0
WARNING: Ignoring invalid distribution -rotobuf (d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (d:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages)

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: D:\StableDiffusion\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
Downloading (…)d516c/.gitattributes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 1.89k/1.89k [00:00<00:00, 1.90MB/s]
Fetching 22 files:   0%|                                                                                                                              | 0/22 [00:00<?, ?it/s]
Downloading (…)ng/BFM_front_idx.mat: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 44.9k/44.9k [00:00<00:00, 1.22MB/s]
Downloading (…)select_vertex_id.mat: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 62.3k/62.3k [00:00<00:00, 1.05MB/s]
Downloading (…)ting/BFM_exp_idx.mat: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 91.9k/91.9k [00:00<00:00, 917kB/s]
Downloading (…)ilarity_Lm3D_all.mat: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 994/994 [00:00<00:00, 1.39MB/s]
Downloading (…)g/facemodel_info.mat: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 739k/739k [00:00<00:00, 1.82MB/s]
Downloading Exp_Pca.bin: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 51.1M/51.1M [00:06<00:00, 8.17MB/s]
Downloading BFM09_model_info.mat: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 127M/127M [00:12<00:00, 10.1MB/s]
Downloading 01_MorphableModel.mat: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 241M/241M [00:14<00:00, 16.6MB/s]
Error executing callback ui_tabs_callback for D:\StableDiffusion\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py███████| 51.1M/51.1M [00:06<00:00, 9.63MB/s]
Traceback (most recent call last):
  File "D:\StableDiffusion\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback                            | 62.9M/241M [00:05<00:13, 13.7MB/s]
    res += c.callback() or [].mat:  78%|████████████████████████████████████████████████████████████████████████████▊                     | 189M/241M [00:12<00:02, 18.9MB/s]
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 80, in on_ui_tabs██████████████████████| 241M/241M [00:14<00:00, 23.1MB/s]
    install()
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 76, in install
    download_model(paths.script_path+'/extensions/SadTalker/checkpoints')
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 14, in download_model
    snapshot_download(repo_id=REPO_ID, local_dir=local_dir, local_dir_use_symlinks=False)
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\_snapshot_download.py", line 239, in snapshot_download
    thread_map(
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\tqdm\contrib\concurrent.py", line 94, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\tqdm\contrib\concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\_snapshot_download.py", line 215, in _inner_hf_hub_download
    return hf_hub_download(
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1377, in hf_hub_download
    _chmod_and_replace(temp_file.name, local_dir_filepath)
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1569, in _chmod_and_replace
    os.replace(src, dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\MyName\\.cache\\huggingface\\hub\\tmpgofpjao_' -> 'D:\\StableDiffusion\\stable-diffusion-webui/extensions/SadTalker/checkpoints\\.gitattributes'
```

**Comment by vinthony** [comment]
manually download the checkpoints may works better, we give a new tutorial here: https://github.com/Winfredy/SadTalker/blob/main/docs/webui_extension.md

**Comment by Wauplin** [comment]
> Still having issue even with the latest update for both huggingface, and SadTalker.
I have updated SadTalker, and I have ran "pip install git+https://github.com/huggingface/huggingface_hub@main" in the venv, and verified that my current version is 0.14.0.dev0. I have also set SADTALKER_CHECKPOINTS=.\extensions\SadTalker\checkpoints in the web-user.bat.

> ```
> OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\MyName\\.cache\\huggingface\\hub\\tmpgofpjao_' -> 'D:\\StableDiffusion\\stable-diffusion-webui/extensions/SadTalker/checkpoints\\.gitattributes'
> ```

@MadHalaster this is a different issue in `huggingface_hub` regarding copying files between different partitions. It has been addressed by @thaiminhpv in PR https://github.com/huggingface/huggingface_hub/pull/1439. So now if you reinstall from source (`pip install git+https://github.com/huggingface/huggingface_hub@main`), your issues should be resolved.

Please let me know if everything is finally settled for you :)

**Comment by G-force78** [comment]
> manually download the checkpoints may works better, we give a new tutorial here: https://github.com/Winfredy/SadTalker/blob/main/docs/webui_extension.md

Hi, where to put this file? s3fd-619a316812.pth
https://drive.google.com/file/d/1EwGG1bS0EQA_R6yGoWm9BJVzli-erVpG/view?usp=sharing

**Comment by vinthony** [comment]
keep the same folder as here:
![image](https://user-images.githubusercontent.com/4397546/231994113-2139ac8d-d6b4-497b-ae26-ee53ae93bd79.png)

s3fd-619a316812.pth need to put under `extensions/SadTalker/checkpoints/hub/checkpoints/`

**Comment by G-force78** [comment]
Ok thanks for quick reply! Ive downloaded all the files in the gdrive and from the hub , do I need to the files from BFM_fitting too?

**Comment by vinthony** [comment]
sure, please download all the files.

**Comment by Bm930** [comment]
> manually download the checkpoints may works better, we give a new tutorial here: https://github.com/Winfredy/SadTalker/blob/main/docs/webui_extension.md

SadTalker will not support download all the files from hugging face, which will take a long time. please manually set the SADTALKER_CHECKPOINTS in webui_user.bat我真的找不到解决办法，我在SADTALKER_CHECKPOINTS文件路径下cmd后键入webui_user.bat不可操作

**Comment by JeroenSteen** [comment]
How to do the SADTALKER_CHECKPOINTS in webui_user.bat?

C:\stable-diffusion-webui\extensions\SadTalker\scripts\checkpoints
C:\stable-diffusion-webui\extensions\SadTalker\scripts\gfpgan
