### ISSUE TITLE
TAB won't appear ?

### ISSUE THREAD

**Issue by AlonDan** [Winfredy/SadTalker#124]
After installing to Automatic1111 WebUI via the link,
it does show the directory under extensions but there is no TAB

Any idea how to make it APPEAR ?

Thanks ahead 💙

**Comment by GitHubAliyen** [comment]
I had the same problem, and saw this in the console:
"C:\...\Python310\lib\ntpath.py", line 804, in commonpath
    raise ValueError("Paths don't have the same drive")
ValueError: Paths don't have the same drive."

This was following a number of other errors. I have SD on my D: drive, and system on C: drive.

**Comment by lstep** [comment]
Same problem, on Windows, my python is installed on C: but my SD is on D:

```
  File "D:\Stable-Diffusion\SD21\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1280, in hf_hub_download
    return _to_local_dir(blob_path, local_dir, relative_filename, use_symlinks=local_dir_use_symlinks)
  File "D:\Stable-Diffusion\SD21\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1568, in _to_local_dir
    _create_symlink(real_blob_path, local_dir_filepath, new_blob=False)
  File "D:\Stable-Diffusion\SD21\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 873, in _create_symlink
    _support_symlinks = are_symlinks_supported(os.path.dirname(os.path.commonpath([abs_src, abs_dst])))
  File "C:\Python\Python310\lib\ntpath.py", line 807, in commonpath
    raise ValueError("Paths don't have the same drive")
ValueError: Paths don't have the same drive
```

**Comment by NOSALIS** [comment]
Same here. SD installed on E:\ - system/ffmpeg on C:\

**Comment by vinthony** [comment]
refer to #123

**Comment by NOSALIS** [comment]
> refer to #123

The tab has appeared before with SD and ST installed on two different drives.

**Comment by vinthony** [comment]
It is something about hugging face download tools,  please follow our new installation documents about webui here:https://github.com/Winfredy/SadTalker/blob/main/docs/webui_extension.md

**Comment by AlonDan** [comment]
> It is something about hugging face download tools, please follow our new installation documents about webui here:https://github.com/Winfredy/SadTalker/blob/main/docs/webui_extension.md

Thanks! 💙
That new installation guide bring back the TAB

I'm getting Out of Memory when trying to generate:
Using the extension via **Automatic1111 WebUI** is there a way I can tweak the **Batch size** to something lower than default?

**Comment by vinthony** [comment]
change this line:

https://github.com/Winfredy/SadTalker/blob/84d1f4eb5eabb9a6a02d2f8766e618b4a2812715/src/gradio_demo.py#L120

**Comment by AlonDan** [comment]
> change this line:
> 
> https://github.com/Winfredy/SadTalker/blob/84d1f4eb5eabb9a6a02d2f8766e618b4a2812715/src/gradio_demo.py#L120

I would like contribute my help by sharing my tests, 
I hope that my feedback info will help the developers team and also to others:

I've tested the **local Gradio App** now with:

- CPU = Intel  **i7**-4770K  3.50GHz
- GPU = Nvidia GTX 980 - **4GB** GDDR5 
- OS = Windows **10**

All Modes Tests:
- Crop = ✅ Works!
- Resize = ✅ Works!
- Full = ✅ Works!
- w/ Still = ✅ Works!
- w/ GFPGAN = ✅ Works!

Batch Size Tests:
- Batch_Size = 4 and above ❎  Failed
- Batch_Size = **3** and below ✅  **Works!**

Maybe Batch Size = 2 should remain the default for safety, as I didn't see much difference between 2-3 with the speed.

The reason I put these to the test is to let you know it works with a **10 years old PC** I also tested on a newer machine but this one still run nicely which I couldn't believe until I tried many different tests, even with longer audio.
Sure, it's slower but not too bad to be honest. everything works smoothly without any Out of Memory issues. at least **on the current version**.

---

Unfortunately testing Automatic1111 WebUI I still get **Out of Memory** even with **Batch Size = 1** ❎ (I can still use Automatic1111 WebUI on the other modes such as txt2img, img2img, inpainting etc.. it's only getting out of memory with SadTalker.

**Comment by vinthony** [comment]
very cool testing, Stable-diffusion-webui will automatically hold 3GB VRAM memories when running. So it is hard for our code for a 4GB memory card within it.

**Comment by AlonDan** [comment]
> very cool testing, Stable-diffusion-webui will automatically hold 3GB VRAM memories when running. So it is hard for our code for a 4GB memory card within it.

That make sense,
I defiantly appreciate the Local Gradio App,
I forgot to mention that my minimum requirements tests I did, also works WONDERFUL with the **TTS**, I just appreciate real Audio tests much better ;)

I will be happy to share more tests with the upcoming features, I hope it will keep working with GPUS with 4GB VRAM that will be very nice.

Please keep up the good work!

**Comment by lovewanity** [comment]
Traceback (most recent call last):
  File "E:\STD\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\STD\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\STD\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\STD\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "E:\STD\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

**Comment by Keller010** [comment]
After clicking generate, top right corner show red line: Error
Expecting value: line 1 column 1 (char 0)

**Comment by zozo7110** [comment]
venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "C:\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "C:\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.
Press any key to continue . . .
What could be the problem?????

**Comment by RichardC05** [comment]
> venv folder already exists, skipping creation... venv "venv\Scripts\Python.exe" Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] Commit hash: [cd4c046](https://github.com/OpenTalker/SadTalker/commit/cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8) Installing requirements for SadTalker WebUI (may take longer time in first time) Launching SadTalker Web UI Traceback (most recent call last): File "C:\SadTalker\Launcher.py", line 204, in start() File "C:\SadTalker\Launcher.py", line 198, in start demo = sadtalker_demo() File "C:\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo with gr.Row().style(equal_height=False): AttributeError: 'Row' object has no attribute 'style'
> 
> Launch unsuccessful. Exiting. Press any key to continue . . . What could be the problem?????

Hi

I have the same problem, did you find the solution?

**Comment by U2siel** [comment]
> > venv folder already exists, skipping creation... venv "venv\Scripts\Python.exe" Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] Commit hash: [cd4c046](https://github.com/OpenTalker/SadTalker/commit/cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8) Installing requirements for SadTalker WebUI (may take longer time in first time) Launching SadTalker Web UI Traceback (most recent call last): File "C:\SadTalker\Launcher.py", line 204, in start() File "C:\SadTalker\Launcher.py", line 198, in start demo = sadtalker_demo() File "C:\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo with gr.Row().style(equal_height=False): AttributeError: 'Row' object has no attribute 'style'
> > Launch unsuccessful. Exiting. Press any key to continue . . . What could be the problem?????
> 
> Hi
> 
> I have the same problem, did you find the solution?

I was able to use it easily through Automatic1111, but never independently.

**Comment by RichardC05** [comment]
> > > venv folder already exists, skipping creation... venv "venv\Scripts\Python.exe" Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] Commit hash: [cd4c046](https://github.com/OpenTalker/SadTalker/commit/cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8) Installing requirements for SadTalker WebUI (may take longer time in first time) Launching SadTalker Web UI Traceback (most recent call last): File "C:\SadTalker\Launcher.py", line 204, in start() File "C:\SadTalker\Launcher.py", line 198, in start demo = sadtalker_demo() File "C:\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo with gr.Row().style(equal_height=False): AttributeError: 'Row' object has no attribute 'style'
> > > Launch unsuccessful. Exiting. Press any key to continue . . . What could be the problem?????
> > 
> > 
> > Hi
> > I have the same problem, did you find the solution?
> 
> I was able to use it easily through Automatic1111, but never independently.

I found a ZIP patch on this French youtube video at the bottom of the description. I couldn't find the original url of the patch.

https://youtu.be/cG_bTyINNpk?si=9NMZHU09e_UJIPmG
