### ISSUE TITLE
ValueError: Paths don't have the same drive

### ISSUE THREAD

**Issue by Gcode808** [Winfredy/SadTalker#128]
Fetching 22 files:   0%|                                                                     | 0/22 [00:00<?, ?it/s]
Error executing callback ui_tabs_callback for D:\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 69, in on_ui_tabs
    install()
  File "D:\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 65, in install
    download_model(paths.script_path+'/extensions/SadTalker/checkpoints')
  File "D:\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 14, in download_model
    snapshot_download(repo_id=REPO_ID, local_dir=local_dir, local_dir_use_symlinks=True)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\_snapshot_download.py", line 235, in snapshot_download
    thread_map(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "D:\stable-diffusion-webui\venv\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\_snapshot_download.py", line 212, in _inner_hf_hub_download
    return hf_hub_download(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1280, in hf_hub_download
    return _to_local_dir(blob_path, local_dir, relative_filename, use_symlinks=local_dir_use_symlinks)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1568, in _to_local_dir
    _create_symlink(real_blob_path, local_dir_filepath, new_blob=False)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 873, in _create_symlink
    _support_symlinks = are_symlinks_supported(os.path.dirname(os.path.commonpath([abs_src, abs_dst])))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 804, in commonpath
    raise ValueError("Paths don't have the same drive")
ValueError: Paths don't have the same drive

**Comment by Gcode808** [comment]
I watched a youtube video and the video didn't mention to set this in webui_user.bat

set SADTALKER_CHECKPOINTS=D:\SadTalker\checkpoints

after I set this in my webui_user.bat, got it working.
