### ISSUE TITLE
RuntimeError ?

### ISSUE THREAD

**Issue by AlonDan** [Winfredy/SadTalker#131]
I'm trying to use:
 `python app.py`
 
 Installation was nice and easy to follow but...
After I drop an Image + Audio and then I press the Generate button, I get this error:
 
```
 checkpoints\auido2pose_00140-model.pth
Traceback (most recent call last):
  File "Z:\anaconda3\envs\sadtalker\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "Z:\anaconda3\envs\sadtalker\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "Z:\anaconda3\envs\sadtalker\lib\site-packages\gradio\blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "Z:\anaconda3\envs\sadtalker\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "Z:\anaconda3\envs\sadtalker\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "Z:\anaconda3\envs\sadtalker\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\SadTalker\src\gradio_demo.py", line 65, in test
    self.audio_to_coeff = Audio2Coeff(self.audio2pose_checkpoint, self.audio2pose_yaml_path,
  File "D:\SadTalker\src\test_audio2coeff.py", line 35, in __init__
    self.audio2pose_model = Audio2Pose(cfg_pose, wav2lip_checkpoint, device=device)
  File "D:\SadTalker\src\audio2pose_models\audio2pose.py", line 15, in __init__
    self.audio_encoder = AudioEncoder(wav2lip_checkpoint, device)
  File "D:\SadTalker\src\audio2pose_models\audio_encoder.py", line 45, in __init__
    wav2lip_state_dict = torch.load(wav2lip_checkpoint, map_location=torch.device(device))['state_dict']
  File "Z:\anaconda3\envs\sadtalker\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "Z:\anaconda3\envs\sadtalker\lib\site-packages\torch\serialization.py", line 938, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 1630207 more bytes. The file might be corrupted.
```

**Comment by vinthony** [comment]
maybe the `wav2lip.pth` is not fully downloaded, try to redownload it.

**Comment by AlonDan** [comment]
> maybe the `wav2lip.pth` is not fully downloaded, try to redownload it.

I downloaded it from Google Drive just in case, but it was exactly the same full size, also it says the exacts same size before I downloaded so it is the full file.

**Comment by AlonDan** [comment]
I reinstall it on another computer,

I made sure all the checkpoints are finished download completely, no missing file everything downloaded until finished so no reason for a corrupt downloaded file.

I get the exact same error as above when I press "Generate"

**Comment by vinthony** [comment]
duplicated with #132 , close and discussion in that issue
