### ISSUE TITLE
No such file or directory: '/root/.cache/torch/hub/checkpoints/s3fd-619a316812.pth'

### ISSUE THREAD

**Issue by VSBDev** [Winfredy/SadTalker#133]
When installing on a mac m1 or using the google colab I get the same error.

Looks like is looking for the s3fd-619a316812.pth file in the wrong context

examples/source_image/full3.png
./checkpoints/epoch_20.pth
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 55, in main
    preprocess_model = CropAndExtract(path_of_lm_croper, path_of_net_recon_model, dir_of_BFM_fitting, device)
  File "/content/SadTalker/src/utils/preprocess.py", line 51, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "/content/SadTalker/src/face3d/extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, 
  File "/usr/local/lib/python3.8/dist-packages/face_alignment/api.py", line 77, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose, **face_detector_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/face_alignment/detection/sfd/sfd_detector.py", line 26, in __init__
    model_weights = torch.load(path_to_detector)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/checkpoints/s3fd-619a316812.pth'

**Comment by Ionaut** [comment]
I'm getting the same thing for the same checkpoint

**Comment by vinthony** [comment]
similar to #125, fixed now.
