### ISSUE TITLE
Error executing callback ui_tabs_callback for F:\AI\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py/s]

### ISSUE THREAD

**Issue by Wasobi23** [Winfredy/SadTalker#139]
Hello,
I am getting this error on Windows 10, 

Error executing callback ui_tabs_callback for F:\AI\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py/s]
Traceback (most recent call last): 74%|████████████████████████████████▋           | 94.4M/127M [00:13<00:04, 7.57MB/s]
  File "F:\AI\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback[00:14<00:00, 14.7MB/s]
    res += c.callback() or []
  File "F:\AI\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 69, in on_ui_tabs
    install()
  File "F:\AI\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 65, in install
    download_model(paths.script_path+'/extensions/SadTalker/checkpoints')
  File "F:\AI\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 14, in download_model
    snapshot_download(repo_id=REPO_ID, local_dir=local_dir, local_dir_use_symlinks=True)
  File "F:\AI\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "F:\AI\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\_snapshot_download.py", line 235, in snapshot_download
    thread_map(
  File "F:\AI\stable-diffusion-webui\venv\lib\site-packages\tqdm\contrib\concurrent.py", line 94, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "F:\AI\stable-diffusion-webui\venv\lib\site-packages\tqdm\contrib\concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "F:\AI\stable-diffusion-webui\venv\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\AI\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\_snapshot_download.py", line 212, in _inner_hf_hub_download
    return hf_hub_download(
  File "F:\AI\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "F:\AI\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1349, in hf_hub_download
    _create_symlink(blob_path, local_dir_filepath, new_blob=False)
  File "F:\AI\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 873, in _create_symlink
    _support_symlinks = are_symlinks_supported(os.path.dirname(os.path.commonpath([abs_src, abs_dst])))
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 804, in commonpath
    raise ValueError("Paths don't have the same drive")
ValueError: Paths don't have the same drive

Is there a way around this that I can guide it to the other drive or is there a way to install the requirements on the same drive?
Thanks!

**Comment by vinthony** [comment]
this link may be helpful: https://github.com/Winfredy/SadTalker/issues/123

**Comment by Wasobi23** [comment]
> 

Thank you, I will wait for the update and then try it.

**Comment by vinthony** [comment]
Hi, we have update the code and see the new tutorial here: https://github.com/Winfredy/SadTalker/blob/main/docs/webui_extension.md


I will close this issue and you can reopen it if you have any other problems.

**Comment by davidraymondcross** [comment]
vinthony doesn't solve any issues and marks them as completed. Don't waste your time, this GIT doesn't work!

**Comment by leo852** [comment]
Doesn't work +1, tried both webui and webui-forge

Environment: Ubuntu Server 22.04 LTS
Python 3.10
NVIDIA RTX 3090 (Driver: 550-headless)
Extensions: Only SadTalker is on

**Comment by orkun41** [comment]
I tried everything but Doesn't work , i have the same issue +1 

 Error executing callback ui_tabs_callback for D:\Program Files\STABLE UI\webui\extensions\SadTalker\scripts\extension.py
