### ISSUE TITLE
colab中安装报错

### ISSUE THREAD

**Issue by Qian-Hao** [Winfredy/SadTalker#142]
Error executing callback ui_tabs_callback for /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 69, in on_ui_tabs
    install()
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 65, in install
    download_model(paths.script_path+'/extensions/SadTalker/checkpoints')
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 14, in download_model
    snapshot_download(repo_id=REPO_ID, local_dir=local_dir, local_dir_use_symlinks=False)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/_snapshot_download.py", line 235, in snapshot_download
    thread_map(
  File "/usr/local/lib/python3.9/dist-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/usr/local/lib/python3.9/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/_snapshot_download.py", line 212, in _inner_hf_hub_download
    return hf_hub_download(
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/file_download.py", line 1363, in hf_hub_download
    _chmod_and_replace(temp_file.name, local_dir_filepath)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/file_download.py", line 1555, in _chmod_and_replace
    os.replace(src, dst)
OSError: [Errno 18] Invalid cross-device link: '/root/.cache/huggingface/hub/tmprqh9mrss' -> '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SadTalker/checkpoints/.gitattributes'

**Comment by vinthony** [comment]
It maybe because of the version of huggingface_cli, I have downgraded to 0.13.2.

**Comment by vinthony** [comment]
I also test the code here, it works fine:
https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/video/stable/stable_diffusion_1_5_video_webui_colab.ipynb
