### ISSUE TITLE
是不支持解析.w4a格式的文件吗？

### ISSUE THREAD

**Issue by yanyusanqian** [Winfredy/SadTalker#144]
环境：
sd-webui extensions
ffmpeg version 5.1.2-essentials_build

问题：
使用.w4a音频文件生成视频时报错如下，但是手动用ffmpeg把.wa4换成了.wav再次导入就可以正确生成了。请问是不支持.w4a格式吗？还是ffmpeg的参数设置有问题？我该如何更改。

`Traceback (most recent call last):
  File "D:\miaoshouai-sd-webui-v230222full\python\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\miaoshouai-sd-webui-v230222full\python\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\miaoshouai-sd-webui-v230222full\python\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\miaoshouai-sd-webui-v230222full\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\miaoshouai-sd-webui-v230222full\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\miaoshouai-sd-webui-v230222full\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\miaoshouai-sd-webui-v230222full\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "D:\miaoshouai-sd-webui-v230222full/extensions/SadTalker\src\gradio_demo.py", line 122, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "D:\miaoshouai-sd-webui-v230222full/extensions/SadTalker\src\facerender\animate.py", line 176, in generate
    sound = AudioSegment.from_mp3(audio_path)
  File "D:\miaoshouai-sd-webui-v230222full\python\lib\site-packages\pydub\audio_segment.py", line 796, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "D:\miaoshouai-sd-webui-v230222full\python\lib\site-packages\pydub\audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 5.1.2-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers

  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
 configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband

  libavutil      57. 28.100 / 57. 28.100

  libavcodec     59. 37.100 / 59. 37.100

  libavformat    59. 27.100 / 59. 27.100

  libavdevice    59.  7.100 / 59.  7.100

  libavfilter     8. 44.100 /  8. 44.100

  libswscale      6.  7.100 /  6.  7.100

  libswresample   4.  7.100 /  4.  7.100

  libpostproc    56.  6.100 / 56.  6.100

[mp3float @ 000002491018cbc0] Header missing

    Last message repeated 151 times

[mp3 @ 000002491018b940] Could not find codec parameters for stream 0 (Audio: mp3 (mp3float), 0 channels, fltp): unspecified frame size

Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

Input #0, mp3, from 'D:\miaoshouai-sd-webui-v230222full\outputs\SadTalker\28b76c52-4571-4227-a3a7-291f4067317e\input\test-0-100.m4a':`

**Comment by vinthony** [comment]
mp3 and wav only.

**Comment by yanyusanqian** [comment]
fine, thanks.
