### ISSUE TITLE
Problem with SadTalker

### ISSUE THREAD

**Issue by Gammablitze** [Winfredy/SadTalker#145]
.\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
.\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
.\extensions\SadTalker\checkpoints\facevid2vid_00189-model.pth.tar
C:\Users\Spiele\AppData\Local\Temp\tmpqrxa5n9u.png
Traceback (most recent call last):
  File "H:\KI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\KI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "H:\KI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\KI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\KI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\KI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\KI\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "H:\KI\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 111, in test
    first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir, preprocess)
  File "H:\KI\stable-diffusion-webui/extensions/SadTalker\src\utils\preprocess.py", line 93, in generate
    x_full_frames, crop, quad = self.croper.crop(x_full_frames, still=True, xsize=pic_size)
TypeError: cannot unpack non-iterable NoneType object

I dont know what to do with this error, doas anybody know a solution ?

**Comment by tkyeung2000** [comment]
C:\SD\stable-diffusion-webui-directml\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
C:SD\stable-diffusion-webui-directml\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
C:SD\stable-diffusion-webui-directml\extensions\SadTalker\checkpoints\facevid2vid_00189-model.pth.tar
C:\Users\CP\AppData\Local\Temp\tmp0zml2t13.png
landmark Det::   0%|                                                                             | 0/1 [00:00<?, ?it/s]"softmax_kernel_impl" not implemented for 'Half'
landmark Det::   0%|                                                                             | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:SD\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:SD\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:SD\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:SD\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:SD\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:SD\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:SD\stable-diffusion-webui-directml\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "C:SD\stable-diffusion-webui-directml/extensions/SadTalker\src\gradio_demo.py", line 111, in test
    first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir, preprocess)
  File "C:SD\stable-diffusion-webui-directml/extensions/SadTalker\src\utils\preprocess.py", line 122, in generate
    lm = self.kp_extractor.extract_keypoint(frames_pil, landmarks_path)
  File "C:SD\stable-diffusion-webui-directml/extensions/SadTalker\src\face3d\extract_kp_videos.py", line 28, in extract_keypoint
    current_kp = self.extract_keypoint(image)
  File "C:SD\stable-diffusion-webui-directml/extensions/SadTalker\src\face3d\extract_kp_videos.py", line 56, in extract_keypoint
    return keypoints
UnboundLocalError: local variable 'keypoints' referenced before assignment

Hi all, I dont know how to fix this error, does anybody know a solution ?

**Comment by B1gM8c** [comment]
> UnboundLocalError: local variable 'keypoints' referenced before assignment

The same issues
```
UnboundLocalError: local variable 'keypoints' referenced before assignment
```

**Comment by vinthony** [comment]
It is also an issue that the face detector can not detect the face of the image. Make sure you are input a REAL person image.
