### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by boricuapab** [Winfredy/SadTalker#165]
Startup time: 20.3s (import torch: 3.6s, import gradio: 0.8s, import ldm: 0.4s, other imports: 1.0s, load scripts: 3.9s, load SD checkpoint: 2.0s, create ui: 8.0s, gradio launch: 0.2s, scripts app_started_callback: 0.3s).
C:\sdLocal\stable-diffusion-webui\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
C:\sdLocal\stable-diffusion-webui\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
C:\sdLocal\stable-diffusion-webui\extensions\SadTalker\checkpoints\facevid2vid_00189-model.pth.tar
C:\Users\ADMINI~1\AppData\Local\Temp\tmpsxyevpdh.png
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.11s/it]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.50it/s]
mel:: 100%|███████████████████████████████████████████████████████████████████████| 200/200 [00:00<00:00, 99983.41it/s]
audio2exp:: 100%|█████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 133.30it/s]
Face Renderer:: 100%|████████████████████████████████████████████████████████████████| 100/100 [01:00<00:00,  1.66it/s]
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (256, 255) to (256, 256) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '256eb34a-f5c6-4ca2-8567-9bc2394f2f55.mp4' -> 'C:\\sdLocal\\stable-diffusion-webui\\outputs\\SadTalker\\cecb2bf3-b43e-4b05-a1b0-49986bf5c44d\\tmpsxyevpdh##RD_Radio31_000-0-100.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\sdLocal\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\sdLocal\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\sdLocal\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\sdLocal\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\sdLocal\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\sdLocal\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\sdLocal\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "C:\sdLocal\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 122, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "C:\sdLocal\stable-diffusion-webui/extensions/SadTalker\src\facerender\animate.py", line 183, in generate
    save_video_with_watermark(path, new_audio_path, av_path, watermark= False)
  File "C:\sdLocal\stable-diffusion-webui/extensions/SadTalker\src\utils\videoio.py", line 26, in save_video_with_watermark
    shutil.move(temp_file, save_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '256eb34a-f5c6-4ca2-8567-9bc2394f2f55.mp4'

**Comment by boricuapab** [comment]
fixed after installing ffmpeg and setting up the environment variable for it
