### ISSUE TITLE
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

### ISSUE THREAD

**Issue by Verystone** [Winfredy/SadTalker#17]
I generate 2D face from a single Image, the audio size is 11499622.

Python 3.8.16

pip list:

```
Package            Version
------------------ ------------
audioread          3.0.0
blurhash           1.1.4
boost              0.1
certifi            2022.12.7
charset-normalizer 2.1.1
cmake              3.26.0
decorator          5.1.1
dlib               19.24.0
face-alignment     1.3.5
ffmpy              0.3.0
greenlet           2.0.2
idna               3.4
imageio            2.19.3
imageio-ffmpeg     0.4.7
joblib             1.1.0
kornia             0.6.8
librosa            0.6.0
llvmlite           0.31.0
Mastodon.py        1.8.0
networkx           3.0
numba              0.48.0
numpy              1.23.4
opencv-python      4.7.0.72
packaging          23.0
Pillow             9.3.0
pip                23.0.1
pydub              0.25.1
python-dateutil    2.8.2
python-magic       0.4.27
PyWavelets         1.4.1
PyYAML             6.0
requests           2.28.1
resampy            0.3.1
scikit-image       0.19.3
scikit-learn       1.1.3
scipy              1.5.3
setuptools         65.6.3
six                1.16.0
SQLAlchemy         2.0.6
threadpoolctl      3.1.0
tifffile           2023.3.15
torch              1.12.1+cu113
torchaudio         0.12.1+cu113
torchvision        0.13.1+cu113
tqdm               4.65.0
typing_extensions  4.4.0
urllib3            1.26.13
wheel              0.38.4
yacs               0.1.8
```

errors:
```
Traceback (most recent call last):
  File "inference.py", line 98, in <module>
    main(args)
  File "inference.py", line 75, in main
    animate_from_coeff.generate(data, save_dir)
  File "/home/ubuntu/SadTalker/facerender/animate.py", line 154, in generate
    sound = AudioSegment.from_mp3(audio_path)
  File "/home/ubuntu/anaconda3/envs/sadtalker/lib/python3.8/site-packages/pydub/audio_segment.py", line 796, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "/home/ubuntu/anaconda3/envs/sadtalker/lib/python3.8/site-packages/pydub/audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7.3.0 (crosstool-NG 1.23.0.449-a04d0)
  configuration: --prefix=/home/ubuntu/anaconda3/envs/sadtalker --cc=/tmp/build/80754af9/ffmpeg_1587154242452/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc --disable-doc --enable-avresample --enable-gmp --enable-hardcoded-tables --enable-libfreetype --enable-libvpx --enable-pthreads --enable-libopus --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame --disable-nonfree --enable-gpl --enable-gnutls --disable-openssl --enable-libopenh264 --enable-libx264
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mp3float @ 0x55dce8ccfc80] Header missing
    Last message repeated 162 times
[mp3 @ 0x55dce8cc5fc0] decoding for stream 0 failed
[mp3 @ 0x55dce8cc5fc0] Could not find codec parameters for stream 0 (Audio: mp3 (mp3float), 0 channels, fltp): unspecified frame size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mp3, from './face-zxc.wav':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: mp3, 0 channels, fltp
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s32le (native))
```

How to solve this problem?

**Comment by Winfredy** [comment]
I search for solution of this errors and it seems there is something wrong in your audio. You could try other audios.

**Comment by Verystone** [comment]
Yes, there is something wrong with my audio. I try to use another audio and it is ok.
Thank you very much.
