### ISSUE TITLE
请问一下为什么在SD生成时总提示出错？

### ISSUE THREAD

**Issue by Clement-mo** [Winfredy/SadTalker#171]
C:\novelai-webui-aki-v3\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
C:\novelai-webui-aki-v3\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
Traceback (most recent call last):
  File "C:\novelai-webui-aki-v3\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\novelai-webui-aki-v3\py310\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\novelai-webui-aki-v3\py310\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\novelai-webui-aki-v3\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\novelai-webui-aki-v3\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\novelai-webui-aki-v3\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\novelai-webui-aki-v3\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "C:\novelai-webui-aki-v3/extensions/SadTalker\src\gradio_demo.py", line 69, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "C:\novelai-webui-aki-v3/extensions/SadTalker\src\utils\preprocess.py", line 51, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "C:\novelai-webui-aki-v3/extensions/SadTalker\src\face3d\extract_kp_videos_safe.py", line 34, in __init__
    self.detector = init_alignment_model('awing_fan',device=device)
  File "C:\novelai-webui-aki-v3\py310\lib\site-packages\facexlib\alignment\__init__.py", line 19, in init_alignment_model
    model.load_state_dict(torch.load(model_path)['state_dict'], strict=True)
  File "C:\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\reallysafe.py", line 117, in load
    return load_with_extra(filename, *args, **kwargs)
  File "C:\novelai-webui-aki-v3\extensions\sd_dreambooth_extension\reallysafe.py", line 164, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\novelai-webui-aki-v3\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "C:\novelai-webui-aki-v3\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\novelai-webui-aki-v3\py310\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\novelai-webui-aki-v3\py310\lib\site-packages\torch\serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 237192 more bytes. The file might be corrupted.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by vinthony** [comment]
看起来是checkpoint文件没有下载成功
