### ISSUE TITLE
你好，checkpoints里面的文件提示加载错误 RuntimeError: unexpected EOF, expected 854792 more bytes

### ISSUE THREAD

**Issue by dotcool** [Winfredy/SadTalker#173]
这个是错误提示
`.\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
Traceback (most recent call last):
  File "D:\dev\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\dev\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\dev\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\dev\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\dev\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\dev\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\dev\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "D:\dev\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 69, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "D:\dev\stable-diffusion-webui/extensions/SadTalker\src\utils\preprocess.py", line 51, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "D:\dev\stable-diffusion-webui/extensions/SadTalker\src\face3d\extract_kp_videos_safe.py", line 34, in __init__
    self.detector = init_alignment_model('awing_fan',device=device)
  File "D:\dev\stable-diffusion-webui\venv\lib\site-packages\facexlib\alignment\__init__.py", line 19, in init_alignment_model
    model.load_state_dict(torch.load(model_path)['state_dict'], strict=True)
  File "D:\dev\stable-diffusion-webui\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "D:\dev\stable-diffusion-webui\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\dev\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\dev\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 854792 more bytes. The file might be corrupted.`

这是checkpoints的文件结构
![image](https://user-images.githubusercontent.com/6111056/232249982-5f20573a-ecd7-4a5b-ae25-70e86103d57b.png)
这个是webui
![image](https://user-images.githubusercontent.com/6111056/232250002-63c2e048-83b7-473d-ae8a-17501e9d234f.png)
这是启动参数
`@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --api --medvram --xformers --autolaunch --no-gradio-queue --disable-safe-unpickle 
set SADTALKER_CHECKPOINTS=D:\dev\stable-diffusion-webui\extensions\SadTalker\checkpoints
call webui.bat
`
checkpoints的文件，我从2个渠道下载 github和百度网盘都提示这个错误，麻烦帮我瞅瞅，谢谢

**Comment by vinthony** [comment]
这个应该是checkpoint损坏了。应该是facexlib checkpoint下载失败。我看看有什么方法可以避免第三方库带来的问题

**Comment by dotcool** [comment]
> 

感谢大佬

**Comment by vinthony** [comment]
https://github.com/Winfredy/SadTalker/blob/3e51304835e8fe804d4305e993e3bafd3f62028a/src/utils/preprocess.py#L13

一个简单的替代方案是吧这一行的`_safe`去掉

**Comment by dotcool** [comment]
嗯嗯，可以了

**Comment by Eagle07-Sudo** [comment]
worked for me.
But how to redownload the corrupted files, and permanently solve the problem?
It's not a problem in the checkpoints because i download them from [this link](https://drive.google.com/drive/folders/1Wd88VDoLhVzYsQ30_qDVluQr_Xm46yHT) many times and replace them but the issue still occurs.

**Comment by vinthony** [comment]
Hi, we are working on a totally offline version which prevent to download additional files.

**Comment by vinthony** [comment]
are you run local gradio via `python app.py`?

**Comment by Eagle07-Sudo** [comment]
> are you run local gradio via `python app.py`?

When i try to use SadTalker as an extension in the SD Webui i had problems because the downloaded additional files are corrupted (the files that download during the first time task), and might cause by a weakness in internet connection.
Even by deleting the extension folder and models and then reinstalling them the problem wasn't solved. not even by running python app.py

If there a way to automatically redownload  the defined file that give such error "expected 854792 more bytes", i think it will work fine.

for me the work around was to installing the software as a stand-alone app

**Comment by vinthony** [comment]
Hi, sorry for the inconvenience. We are trying to release a totally offline version today or tomorrow. still testing if it is work well on different devices.
