### ISSUE TITLE
一直报错EOF，不知道为什么

### ISSUE THREAD

**Issue by supca** [Winfredy/SadTalker#184]
Startup time: 24.9s (import torch: 4.3s, import gradio: 1.0s, import ldm: 0.6s, other imports: 1.2s, load scripts: 3.6s, load SD checkpoint: 4.9s, create ui: 2.2s, gradio launch: 6.5s, scripts app_started_callback: 0.3s).
F:\AIDraw\novelai-webui\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
F:\AIDraw\novelai-webui\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
Traceback (most recent call last):
  File "F:\AIDraw\novelai-webui\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\AIDraw\novelai-webui\py310\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "F:\AIDraw\novelai-webui\py310\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\AIDraw\novelai-webui\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\AIDraw\novelai-webui\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\AIDraw\novelai-webui\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\AIDraw\novelai-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "F:\AIDraw\novelai-webui/extensions/SadTalker\src\gradio_demo.py", line 69, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "F:\AIDraw\novelai-webui/extensions/SadTalker\src\utils\preprocess.py", line 52, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "F:\AIDraw\novelai-webui/extensions/SadTalker\src\face3d\extract_kp_videos_safe.py", line 34, in __init__
    self.detector = init_alignment_model('awing_fan',device=device)
  File "F:\AIDraw\novelai-webui\py310\lib\site-packages\facexlib\alignment\__init__.py", line 19, in init_alignment_model
    model.load_state_dict(torch.load(model_path)['state_dict'], strict=True)
  File "F:\AIDraw\novelai-webui\extensions\sd_dreambooth_extension\reallysafe.py", line 117, in load
    return load_with_extra(filename, *args, **kwargs)
  File "F:\AIDraw\novelai-webui\extensions\sd_dreambooth_extension\reallysafe.py", line 164, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "F:\AIDraw\novelai-webui\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "F:\AIDraw\novelai-webui\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "F:\AIDraw\novelai-webui\py310\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "F:\AIDraw\novelai-webui\py310\lib\site-packages\torch\serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 4880 more bytes. The file might be corrupted.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by vinthony** [comment]
参考： https://github.com/Winfredy/SadTalker/issues/173#issuecomment-1510134397， 并打开 --disable-safe-unpickle, 参考：https://github.com/Winfredy/SadTalker/blob/main/docs/webui_extension.md#questsions

**Comment by supca** [comment]
> 参考： [https://github.com/Winfredy/SadTalker/issues/173#issuecomment-1510134397，](https://github.com/Winfredy/SadTalker/issues/173#issuecomment-1510134397%EF%BC%8C) 并打开 --disable-safe-unpickle, 参考：https://github.com/Winfredy/SadTalker/blob/main/docs/webui_extension.md#questsions

解决了，呜呜呜，谢谢你大佬，你真的很厉害

**Comment by vinthony** [comment]
enjoy :) 这个issue我就关闭了。
