### ISSUE TITLE
丢失文件：TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by toniedeng** [Winfredy/SadTalker#189]
stable diffusion里面生成视频出现新问题，看下面代码，我仔细找了， 
 C:\Windows\TEMP\tmp535kjeao.png 没有这个图片

F:\AI\sd-webui-aki-v4\webui-aki-v4\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
F:\AI\sd-webui-aki-v4\webui-aki-v4\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
F:\AI\sd-webui-aki-v4\webui-aki-v4\extensions\SadTalker\checkpoints\facevid2vid_00189-model.pth.tar
C:\Windows\TEMP\tmp535kjeao.png
Traceback (most recent call last):
  File "F:\AI\sd-webui-aki-v4\webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\AI\sd-webui-aki-v4\webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "F:\AI\sd-webui-aki-v4\webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\AI\sd-webui-aki-v4\webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\AI\sd-webui-aki-v4\webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\AI\sd-webui-aki-v4\webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\AI\sd-webui-aki-v4\webui-aki-v4\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "F:\AI\sd-webui-aki-v4\webui-aki-v4/extensions/SadTalker\src\gradio_demo.py", line 111, in test
    first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir, preprocess)
  File "F:\AI\sd-webui-aki-v4\webui-aki-v4/extensions/SadTalker\src\utils\preprocess.py", line 94, in generate
    x_full_frames, crop, quad = self.croper.crop(x_full_frames, still=True, xsize=512)
TypeError: cannot unpack non-iterable NoneType object

**Comment by vinthony** [comment]
输入的图像是真实的还是二次元的嘛？二次元的无法处理。

**Comment by toniedeng** [comment]
stable diffusion生成的：
（buleberry juice, buleberry cake, buleberry）, 1girl, near window, wind,
Steps: 25, Sampler: DPM++ 2S a Karras, CFG scale: 7, Seed: 4076335938, Size: 512x512, Model hash: fc2511737a, Model: chilloutmix_NiPrunedFp32Fix, Denoising strength: 0.75, Clip skip: 3, ENSD: 31337, Mask blur: 4, Hashes: {"vae": "c6a580b13a", "model": "fc2511737a"}

![00066-4076335938-（buleberry juice, buleberry cake, buleberry）, 1girl, near window, wind,](https://user-images.githubusercontent.com/130746710/232552286-5b648b6e-99de-4ce9-bad4-46313d0b9bc5.png)

**Comment by toniedeng** [comment]
> 我测试了一下，这个图dlib检测不出来关键点。后续会考虑换更强的检测器。

大神高手，你看看这个检测器文章如何：https://baijiahao.baidu.com/s?id=1762775088223349495&wfr=spider&for=pc
【新智元导读】Meta的SAM「分割一切」模型刚发布，国内团队就进行了二创，打造了一个最强的零样本视觉应用Grounded-SAM，不仅能分割一切，还能检测一切，生成一切。

另外，我发现正面图片识别唇和眼睛，还不错。但是一旦是侧面，眼睛就看起来很不好，是否有好的调整，期待。
还有，正常交流情况下。人的头部动作是会微微的向下频繁点头。而不是左顾右盼。这个你们自己评估吧。

**Comment by vinthony** [comment]
SAM不能用作人脸识别和检测哦。这里可能还有一些其他工作需要去做的。
