### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Diffusion\\stable-diffusion-webui/extensions/SadTalker/checkpoints/BFM_Fitting\\similarity_Lm3D_all.mat'

### ISSUE THREAD

**Issue by GitLeandroHub** [Winfredy/SadTalker#191]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Diffusion\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "D:\Diffusion\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 69, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "D:\Diffusion\stable-diffusion-webui/extensions/SadTalker\src\utils\preprocess.py", line 57, in __init__
    self.lm3d_std = load_lm3d(dir_of_BFM_fitting)
  File "D:\Diffusion\stable-diffusion-webui/extensions/SadTalker\src\face3d\util\load_mats.py", line 107, in load_lm3d
    Lm3D = loadmat(osp.join(bfm_folder, 'similarity_Lm3D_all.mat'))
  File "D:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "D:\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "D:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "D:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Diffusion\\stable-diffusion-webui/extensions/SadTalker/checkpoints/BFM_Fitting\\similarity_Lm3D_all.mat'

Any clue? The fisrt time a progress bar appeared, but now nothing happens.
I'm using the Automatic1111 extension.
Thanks!

![image](https://user-images.githubusercontent.com/31373943/232578771-c6cd08ce-9544-4a4c-8d60-a13cb2c80bd2.png)

**Comment by GitLeandroHub** [comment]
Fixed.

I was missing some files from the drive:
https://drive.google.com/drive/folders/1KuudFcZLcp5mAIu8iFcc9RZcforrS8KI

**Comment by vinthony** [comment]
close it since it has been fixed
