### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by chaai2** [Winfredy/SadTalker#194]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui-master\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui-master/extensions/SadTalker\src\gradio_demo.py", line 69, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "D:\stable-diffusion-webui-master/extensions/SadTalker\src\utils\preprocess.py", line 52, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "D:\stable-diffusion-webui-master/extensions/SadTalker\src\face3d\extract_kp_videos_safe.py", line 27, in __init__
    self.detector = init_alignment_model('awing_fan',device=device, model_rootpath=root_path)
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\facexlib\alignment\__init__.py", line 19, in init_alignment_model
    model.load_state_dict(torch.load(model_path)['state_dict'], strict=True)
  File "D:\stable-diffusion-webui-master\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "D:\stable-diffusion-webui-master\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\torch\serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 102280 more bytes. The file might be corrupted.

**Comment by vinthony** [comment]
please update the codes, downloaded the `gfpgan` files as [here](https://github.com/Winfredy/SadTalker#-2-download-trained-models) and put it in `extensions/SadTalker/gfpgan`

**Comment by LeoCeasar** [comment]
> please update the codes, downloaded the `gfpgan` files as [here](https://github.com/Winfredy/SadTalker#-2-download-trained-models) and put it in `extensions/SadTalker/gfpgan`

I have already done what you said. but I still met the same problem.

**Comment by chaai2** [comment]
现在这样了大佬

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui-master\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui-master/extensions/SadTalker\src\gradio_demo.py", line 69, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "D:\stable-diffusion-webui-master/extensions/SadTalker\src\utils\preprocess.py", line 52, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "D:\stable-diffusion-webui-master/extensions/SadTalker\src\face3d\extract_kp_videos_safe.py", line 28, in __init__
    self.det_net = init_detection_model('retinaface_resnet50', half=False,device=device, model_rootpath=root_path)
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\facexlib\detection\__init__.py", line 18, in init_detection_model
    model_path = load_file_from_url(
  File "D:\stable-diffusion-webui-master\modules\gfpgan_model.py", line 94, in facex_load_file_from_url
    return facex_load_file_from_url_orig(**dict(kwargs, save_dir=model_path, model_dir=None))
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\facexlib\utils\misc.py", line 77, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\torch\hub.py", line 597, in download_url_to_file
    u = urlopen(req)
  File "D:\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\python\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>

**Comment by vinthony** [comment]
这个是下模型哈。可以下载gfpgan的离线补丁包，[参考：](https://github.com/Winfredy/SadTalker#-2-download-trained-models)

**Comment by vinthony** [comment]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/4397546/233231157-2234ed49-4dbc-4a7a-b213-386368d84ec8.png">

**Comment by chaai2** [comment]
这个有办法解决吗

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 6.00 GiB total capacity; 4.94 GiB already allocated; 0 bytes free; 5.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by vinthony** [comment]
你的显卡多大呀？

> 这个有办法解决吗
> 
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 6.00 GiB total capacity; 4.94 GiB already allocated; 0 bytes free; 5.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by chaai2** [comment]
Card name: NVIDIA GeForce RTX 3060 Laptop GPU
        Manufacturer: NVIDIA
           Chip type: NVIDIA GeForce RTX 3060 Laptop GPU
            DAC type: Integrated RAMDAC
         Device Type: Full Device (POST)
          Device Key: Enum\PCI\VEN_10DE&DEV_2520&SUBSYS_866C1558&REV_A1
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 14053 MB
    Dedicated Memory: 6009 MB
       Shared Memory: 8044 MB
        Current Mode: 1920 x 1080 (32 bit) (144Hz)
         HDR Support: Not Supported

**Comment by vinthony** [comment]
6G的话不要从SDwebui启动，直接跑inference.py 或者 app.py.
sd的checkpoint会占用3G的显存

**Comment by MrRiverFov** [comment]
> please update the codes, downloaded the `gfpgan` files as [here](https://github.com/Winfredy/SadTalker#-2-download-trained-models) and put it in `extensions/SadTalker/gfpgan`

我已经有gfpgan以及checkpoints文件了，但是依然报错
---------------------------------------------------------------
using safetensor as default
{'checkpoint': '/home/bsxt/stable-diffusion-webui/extensions/SadTalker/checkpoints/SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': '/home/bsxt/stable-diffusion-webui/extensions/SadTalker/src/config', 'audio2pose_yaml_path': '/home/bsxt/stable-diffusion-webui/extensions/SadTalker/src/config/auido2pose.yaml', 'audio2exp_yaml_path': '/home/bsxt/stable-diffusion-webui/extensions/SadTalker/src/config/auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': '/home/bsxt/stable-diffusion-webui/extensions/SadTalker/checkpoints/mapping_00229-model.pth.tar', 'facerender_yaml': '/home/bsxt/stable-diffusion-webui/extensions/SadTalker/src/config/facerender.yaml'}
Traceback (most recent call last):
  File "/home/bsxt/anaconda3/envs/sdwebui-main/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/bsxt/anaconda3/envs/sdwebui-main/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/bsxt/anaconda3/envs/sdwebui-main/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/bsxt/anaconda3/envs/sdwebui-main/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/bsxt/anaconda3/envs/sdwebui-main/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/bsxt/anaconda3/envs/sdwebui-main/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/bsxt/anaconda3/envs/sdwebui-main/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/bsxt/stable-diffusion-webui/modules/call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "/home/bsxt/stable-diffusion-webui/extensions/SadTalker/src/gradio_demo.py", line 50, in test
    self.preprocess_model = CropAndExtract(self.sadtalker_paths, self.device)
  File "/home/bsxt/stable-diffusion-webui/extensions/SadTalker/src/utils/preprocess.py", line 49, in __init__
    self.propress = Preprocesser(device)
  File "/home/bsxt/stable-diffusion-webui/extensions/SadTalker/src/utils/croper.py", line 21, in __init__
    self.predictor = KeypointExtractor(device)
  File "/home/bsxt/stable-diffusion-webui/extensions/SadTalker/src/face3d/extract_kp_videos_safe.py", line 46, in __init__
    self.det_net = init_detection_model('retinaface_resnet50', half=False,device=device, model_rootpath=root_path)
  File "/home/bsxt/anaconda3/envs/sdwebui-main/lib/python3.10/site-packages/facexlib/detection/__init__.py", line 22, in init_detection_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "/home/bsxt/stable-diffusion-webui/modules/safe.py", line 108, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "/home/bsxt/stable-diffusion-webui/modules/safe.py", line 156, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/home/bsxt/anaconda3/envs/sdwebui-main/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/bsxt/anaconda3/envs/sdwebui-main/lib/python3.10/site-packages/torch/serialization.py", line 1264, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 510489 more bytes. The file might be corrupted.
