### ISSUE TITLE
Exceptions and exceptions

### ISSUE THREAD

**Issue by TanvirHafiz** [Winfredy/SadTalker#197]
just getting this, I installed FFMPEG and everything else the tutorial asked. I am runninng automatic1111 SD flawlessly (but not SadTalker in it)

Traceback (most recent call last):
  File "G:\Sadtalker\SadTalker\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints\\BFM_Fitting\\similarity_Lm3D_all.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Sadtalker\SadTalker\venv\lib\site-packages\gradio\routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Sadtalker\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "G:\Sadtalker\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Sadtalker\SadTalker\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Sadtalker\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\Sadtalker\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\Sadtalker\SadTalker\src\gradio_demo.py", line 69, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "G:\Sadtalker\SadTalker\src\utils\preprocess.py", line 57, in __init__
    self.lm3d_std = load_lm3d(dir_of_BFM_fitting)
  File "G:\Sadtalker\SadTalker\src\face3d\util\load_mats.py", line 107, in load_lm3d
    Lm3D = loadmat(osp.join(bfm_folder, 'similarity_Lm3D_all.mat'))
  File "G:\Sadtalker\SadTalker\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "G:\Sadtalker\SadTalker\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "G:\Sadtalker\SadTalker\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints\\BFM_Fitting\\similarity_Lm3D_all.mat'

**Comment by TanvirHafiz** [comment]
also, i know nothing about python git etc etc etc

**Comment by vinthony** [comment]
https://github.com/Winfredy/SadTalker#-2-download-trained-models you need to download the checkpoints and put them in the right place, for example: `sdwebui\extensions\SadTalker\checkpoints`.

**Comment by TanvirHafiz** [comment]
I finally got it. actually yhe checkpoint folder downloads in 2 parts which I didnt notice and didnt download the second part. now I have and it worked. Its a google drive issue!
