### ISSUE TITLE
Tab Missing again

### ISSUE THREAD

**Issue by SauChi666** [Winfredy/SadTalker#202]
After trying to use the command line operations on Sad Talker, and installing more requirements that I was supposed to install before... I no longer be able to see the SadTalker Tab on stable diffusion.  Just updated the extension with sd update interface...  not helping...

**Comment by vinthony** [comment]
Hi, can you give me more information in command line log of sdwebui?

**Comment by SauChi666** [comment]
I completely reinstalled, downloaded checkpoints... ran pip install -r requirements.txt... Tab still not showing. .. I do not know what condition you added to hide the tab,  I think show it without condition and if condition are not met, show it on the web page, or show it in the setting page... , pureerosface_v1, isometric_dreams, cloudport
Model loaded in 11.8s (create model: 0.6s, apply weights to model: 7.2s, apply half(): 2.6s, load VAE: 0.5s, move model to device: 0.8s).
Error executing callback ui_tabs_callback for /Users/appleid/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py
Traceback (most recent call last):
  File "/Users/appleid/stable-diffusion-webui/modules/script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "/Users/appleid/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 141, in on_ui_tabs
    from src.gradio_demo import SadTalker
  File "/Users/appleid/stable-diffusion-webui/extensions/SadTalker/src/gradio_demo.py", line 3, in <module>
    from src.utils.preprocess import CropAndExtract
  File "/Users/appleid/stable-diffusion-webui/extensions/SadTalker/src/utils/preprocess.py", line 19, in <module>
    from src.utils.croper import Croper
  File "/Users/appleid/stable-diffusion-webui/extensions/SadTalker/src/utils/croper.py", line 32, in <module>
    import dlib
  File "/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: dlopen(/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/ffmpeg/lib/libavdevice.59.dylib
  Referenced from: <3FCB77CF-6A26-3D07-86F6-2562B448D173> /Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-darwin.so

**Comment by SauChi666** [comment]
I tried many times, concluded libavdevice.59.dylib is not part of ffmpeg...  tried many ways of install ffmpeg, this is missing in the package...

**Comment by SauChi666** [comment]
don't know what's going on... tried other ways... same error

**Comment by SauChi666** [comment]
look like you need to specify your FFmpeg version...

**Comment by goblin776655** [comment]
> I completely reinstalled, downloaded checkpoints... ran pip install -r requirements.txt... Tab still not showing. .. I do not know what condition you added to hide the tab, I think show it without condition and if condition are not met, show it on the web page, or show it in the setting page... ,
> 
> Not sure if the following help:
> 
> pureerosface_v1, isometric_dreams, cloudport Model loaded in 11.8s (create model: 0.6s, apply weights to model: 7.2s, apply half(): 2.6s, load VAE: 0.5s, move model to device: 0.8s). Error executing callback ui_tabs_callback for /Users/appleid/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py Traceback (most recent call last): File "/Users/appleid/stable-diffusion-webui/modules/script_callbacks.py", line 125, in ui_tabs_callback res += c.callback() or [] File "/Users/appleid/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 141, in on_ui_tabs from src.gradio_demo import SadTalker File "/Users/appleid/stable-diffusion-webui/extensions/SadTalker/src/gradio_demo.py", line 3, in from src.utils.preprocess import CropAndExtract File "/Users/appleid/stable-diffusion-webui/extensions/SadTalker/src/utils/preprocess.py", line 19, in from src.utils.croper import Croper File "/Users/appleid/stable-diffusion-webui/extensions/SadTalker/src/utils/croper.py", line 32, in import dlib File "/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/dlib/**init**.py", line 19, in from _dlib_pybind11 import * ImportError: dlopen(/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/ffmpeg/lib/libavdevice.59.dylib Referenced from: <3FCB77CF-6A26-3D07-86F6-2562B448D173> /Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-darwin.so

Same here :(
Don know how to fix it :(((

**Comment by Adamtechonline** [comment]
the same problem here, SadTalker tab is missing in my A1111 !!

**Comment by marc2608** [comment]
If you are on windows, this solution worked fine for me . Sadtalker tab is ok now. It is only a very simple modification to do: 

The error message that you're getting indicates that there's a problem with your numpy version where np.complex is no longer an existing attribute.
In version 1.20.0, Numpy updated where 'np.complex' was a deprecated alias for the builtin 'complex'. As a solution, you can do one of the following:

You can replace np.complex with complex in the faulty line of code.
If you specifically wanted the numpy scalar type, use np.complex128.

Here's how to apply this:

    Navigate to C:\Users\marc2\Desktop\SD Webui Forge\stable-diffusion-webui-forge\venv\lib\site-packages\librosa\core\constantq.py, line 1058.

    Change np.complex to complex or np.complex128

Additionally, consider adding librosa to your requirements file to ensure the correct version is installed when setting up your environment if not already there.

If these changes don't resolve the issue, you may want to check if you're using the latest versions of the packages as updating them might solve the problem. If you're specifically facing this issue in a virtual environment try recreating it.
