### ISSUE TITLE
I have error when press generate button

### ISSUE THREAD

**Issue by besbesmany** [Winfredy/SadTalker#209]
I have Error in generate button after I upload photo and sount

I made all the steps in the video 
https://www.youtube.com/watch?v=YCFPuDJs4EQ

but when I made install from extensions in the install from URL nothing installed (https://github.com/Winfredy/SadTalker.git)

so what should I do

**Comment by vinthony** [comment]
any command line log?

**Comment by besbesmany** [comment]
To create a public link, set `share=True` in `launch()`.
Startup time: 47.4s (import torch: 7.8s, import gradio: 4.4s, import ldm: 2.7s, other imports: 4.1s, setup codeformer: 0.3s, load scripts: 1.5s, load SD checkpoint: 22.4s, create ui: 3.9s, gradio launch: 0.2s).
C:\Users\legion\stable-diffusion\stable-diffusion-webui/extensions/SadTalker/checkpoints/auido2pose_00140-model.pth
Traceback (most recent call last):
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 65, in test
    self.audio_to_coeff = Audio2Coeff(self.audio2pose_checkpoint, self.audio2pose_yaml_path,
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui/extensions/SadTalker\src\test_audio2coeff.py", line 35, in __init__
    self.audio2pose_model = Audio2Pose(cfg_pose, wav2lip_checkpoint, device=device)
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui/extensions/SadTalker\src\audio2pose_models\audio2pose.py", line 15, in __init__
    self.audio_encoder = AudioEncoder(wav2lip_checkpoint, device)
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui/extensions/SadTalker\src\audio2pose_models\audio_encoder.py", line 45, in __init__
    wav2lip_state_dict = torch.load(wav2lip_checkpoint, map_location=torch.device(device))['state_dict']
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\legion\\stable-diffusion\\stable-diffusion-webui/extensions/SadTalker/checkpoints/wav2lip.pth'


> any command line log?

**Comment by vinthony** [comment]
it seem you do not download all the checkpoints? , please refer here: https://github.com/Winfredy/SadTalker#-2-download-trained-models

**Comment by vinthony** [comment]
For Windows, you need to download the checkpoints manually as on our readme page.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/4397546/234065670-74c62873-ec2e-446a-82c0-147d51ed654b.png">

**Comment by nathanisayas** [comment]
i also have a similar problem as the generating box says error when i press generate
i am using macbook and followed this tutorial (https://www.youtube.com/watch?v=p0iwxbL042g) having already downloaded stable diffusion ui using this tutorial (https://www.youtube.com/watch?v=Jh-clc4jEvk) .
i had the same error problem when creating images from text using stable diffusion.
can you please help me as soon as possible. 
also is there a reason why the public sadtalker by vinthony always says error or that the queue is too large.
<img width="1261" alt="Screenshot 2023-12-10 at 09 18 54" src="https://github.com/OpenTalker/SadTalker/assets/152363868/13e28f38-ebe6-437d-8dbb-c08ac4d7eb24">

**Comment by writeboywrite** [comment]
I'm running SadTalker through the Stable Diffusion WebUI as an extension. Everything looks great, but when I press the generate button I continually get an error and nothing happens. 

I have also tried different settings within SadTalker and have read the Best Practices page. However, no matter what I do, I continue to get the error and no video is generated. I have all the checkpoints installed correctly as well as the GFPGAN model.

I am running on a CPU without NVIDIA GPU. I don't know if that would cause an error though.

**Comment by lim214** [comment]
Please fix this error issue coz every time I press generate it shows error and if mistakenly it starts generate it is taking too much time for just 10 sec video..

**Comment by vlasenkoalexey** [comment]
Pinning gradio version to 3.48 (latest 3.xx) fixed issue for me.
Run pip install -U gradio==3.48
