### ISSUE TITLE
Can't find the file

### ISSUE THREAD

**Issue by GXMT** [Winfredy/SadTalker#210]
Error verifying pickled file from D:\stable-diffusion-webui/extensions/SadTalker/checkpoints/facevid2vid_00189-model.pth.tar:
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\reallysafe.py", line 146, in load_with_extra
    check_pt(filename, extra_handler)
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\reallysafe.py", line 92, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1249, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\stable-diffusion-webui/extensions/SadTalker/checkpoints/facevid2vid_00189-model.pth.tar'

The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 79, in test
    self.animate_from_coeff = AnimateFromCoeff(self.free_view_checkpoint, self.mapping_checkpoint,
  File "D:\stable-diffusion-webui/extensions/SadTalker\src\facerender\animate.py", line 58, in __init__
    self.load_cpk_facevid2vid(free_view_checkpoint, kp_detector=kp_extractor, generator=generator, he_estimator=he_estimator)
  File "D:\stable-diffusion-webui/extensions/SadTalker\src\facerender\animate.py", line 85, in load_cpk_facevid2vid
    generator.load_state_dict(checkpoint['generator'])
TypeError: 'NoneType' object is not subscriptable

This i what I am viewing. I was trying webui

**Comment by vinthony** [comment]
you may need `bash webui.sh --disable-safe-unpickle`
