### ISSUE TITLE
ConnectionResetError: [WinError 10054] occurs every time the movie is finished

### ISSUE THREAD

**Issue by paultw2** [Winfredy/SadTalker#214]
Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 512x512, q=2-31, 1008 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc60.9.100 aac
[out#0/mp4 @ 0000012c695d9380] video:2138kB audio:173kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.528636%
frame=  434 fps=0.0 q=-1.0 Lsize=    2323kB time=00:00:17.34 bitrate=1097.2kbits/s speed=19.5x
[aac @ 0000012c695e9000] Qavg: 65533.832
The generated video is named E:\sd002\stable-diffusion-webui-master\stable-diffusion-webui-master\outputs\SadTalker\371839d2-72ac-4f89-8ee2-33e85f9a8b84/tmp_182jq__##777-0-100_enhanced.mp4
The generated video is named tmp_182jq__##777-0-100 in E:\sd002\stable-diffusion-webui-master\stable-diffusion-webui-master\outputs\SadTalker\371839d2-72ac-4f89-8ee2-33e85f9a8b84
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 遠端主機已強制關閉一個現存的連線。
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 遠端主機已強制關閉一個現存的連線。

我想問問 這種狀況可以解決嗎 ? 還是可以生成影片 只是時間有點久

**Comment by UncleK** [comment]
勾选增强就会出现这个报错，但是生成的视频可以正常播放。估计是一个不痛不痒的小BUG

**Comment by Jeffuy** [comment]
This is also happening to me. The video is generated but I receive that error after the generation. While sometimes I'm able to continue using webui, sometimes I have to restart it. Do you know the reason of this error?
