### ISSUE TITLE
Error deserializing object of type int64

### ISSUE THREAD

**Issue by michaelpick** [Winfredy/SadTalker#223]
I'm able to load the UI (standalone or via Automatic1111 extension), add an image, and add an audio file, but after a few seconds of generation I see the following error:

```
C:\Users\madeb\Automattic1111\stable-diffusion-webui\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
C:\Users\madeb\Automattic1111\stable-diffusion-webui\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
Traceback (most recent call last):
  File "C:\Users\madeb\Automattic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\madeb\Automattic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Users\madeb\Automattic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\madeb\Automattic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\madeb\Automattic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\madeb\Automattic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\madeb\Automattic1111\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "C:\Users\madeb\Automattic1111\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 69, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "C:\Users\madeb\Automattic1111\stable-diffusion-webui/extensions/SadTalker\src\utils\preprocess.py", line 51, in __init__
    self.croper = Croper(path_of_lm_croper)
  File "C:\Users\madeb\Automattic1111\stable-diffusion-webui/extensions/SadTalker\src\utils\croper.py", line 38, in __init__
    self.predictor = dlib.shape_predictor(path_of_lm)
RuntimeError: Error deserializing object of type int64
   while deserializing a floating point number.
   while deserializing a dlib::matrix
   while deserializing object of type std::vector
   while deserializing object of type std::vector
   while deserializing object of type std::vector
```

I'm almost certainly doing something wrong, but wondered if you had any ideas as to what might be causing the error? I do realize there are probably lots of potential variables at play. 

In case it helps, I'm running Automatic1111 on:
- Windows 11
- With a 4090
- And with the following CL args: `--opt-sdp-attention --api --listen --disable-safe-unpickle`
- And versions: python: 3.10.9  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.23.0  •  commit: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)

Thanks!

**Comment by vinthony** [comment]
try to redownload `shape_predictor_68_face_landmarks.dat`: https://stackoverflow.com/questions/43981231/dlib-error-deserializing-object-of-type-short

**Comment by michaelpick** [comment]
Thanks @vinthony! That did the job.
