### ISSUE TITLE
can someone  help me to fix this error

### ISSUE THREAD

**Issue by gr44l** [Winfredy/SadTalker#224]
`IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (256, 259) to (256, 272) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\Gael1\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'dbfa9156-e363-40bb-a6f3-70d17da953d2.mp4' -> 'C:\\Users\\Gael1\\stable-diffusion-webui\\outputs\\SadTalker\\4a835c4f-5365-44c9-9c4b-1c1b5c0d382a\\tmp7h7fw4wv##44-0-100.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gael1\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Gael1\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Users\Gael1\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Gael1\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Gael1\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Gael1\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Gael1\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "C:\Users\Gael1\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 122, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "C:\Users\Gael1\stable-diffusion-webui/extensions/SadTalker\src\facerender\animate.py", line 187, in generate
    save_video_with_watermark(path, new_audio_path, av_path, watermark= False)
  File "C:\Users\Gael1\stable-diffusion-webui/extensions/SadTalker\src\utils\videoio.py", line 26, in save_video_with_watermark
    shutil.move(temp_file, save_path)
  File "C:\Users\Gael1\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "C:\Users\Gael1\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Gael1\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'dbfa9156-e363-40bb-a6f3-70d17da953d2.mp4'`

**Comment by vinthony** [comment]
you need to install ffmpeg, following https://github.com/Winfredy/SadTalker#windows-%E4%B8%AD%E6%96%87windows%E6%95%99%E7%A8%8B,  window (3) install ffmpeg
