### ISSUE TITLE
多数二次元图片无法识别出面部

### ISSUE THREAD

**Issue by w4xxx** [Winfredy/SadTalker#225]
C:\Users\Hasee\AppData\Local\Temp\tmpgo2smyo_.png
Traceback (most recent call last):
  File "E:\aiPainter230121\stable-diffusion-webui_23-01-20\stable-diffusion-webui\python\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\aiPainter230121\stable-diffusion-webui_23-01-20\stable-diffusion-webui\python\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\aiPainter230121\stable-diffusion-webui_23-01-20\stable-diffusion-webui\python\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\aiPainter230121\stable-diffusion-webui_23-01-20\stable-diffusion-webui\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\aiPainter230121\stable-diffusion-webui_23-01-20\stable-diffusion-webui\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\aiPainter230121\stable-diffusion-webui_23-01-20\stable-diffusion-webui\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\aiPainter230121\stable-diffusion-webui_23-01-20\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "E:\aiPainter230121\stable-diffusion-webui_23-01-20\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 111, in test
    first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir, preprocess)
  File "E:\aiPainter230121\stable-diffusion-webui_23-01-20\stable-diffusion-webui/extensions/SadTalker\src\utils\preprocess.py", line 94, in generate
    x_full_frames, crop, quad = self.croper.crop(x_full_frames, still=True, xsize=512)
  File "E:\aiPainter230121\stable-diffusion-webui_23-01-20\stable-diffusion-webui/extensions/SadTalker\src\utils\croper.py", line 170, in crop
    raise 'can not detect the landmark from source image'
TypeError: exceptions must derive from BaseException

有什么办法吗？

**Comment by vinthony** [comment]
二次元图像需要单独的模型进行训练

**Comment by w4xxx** [comment]
> 二次元图像需要单独的模型进行训练
感谢大佬，看来只能等待新模型了。

**Comment by H9990HH969** [comment]
请问现在有二次元，或者是那种大头吉祥物的模型了吗？

**Comment by jelly-liu** [comment]
> 二次元图像需要单独的模型进行训练

i run vinthony/SadTalker on m1, 256*256 work well, where i can get 512*512 or higher 1024*1024 model, thank you so mush. @vinthony

**Comment by fuqifacai** [comment]
> > 二次元图像需要单独的模型进行训练
> 
> i run vinthony/SadTalker on m1, 256_256 work well, where i can get 512_512 or higher 1024*1024 model, thank you so mush. @vinthony

more info will be appreciated.
