### ISSUE TITLE
运行非常慢，不到2分钟的音频，运行超过12个小时进行Face Renderer，最好因无法分配高达1.26GiB的内存空间而产生异常崩溃了。

### ISSUE THREAD

**Issue by boyhero** [Winfredy/SadTalker#227]
E:\Software\SadTalker>D:\ProgramData\Anaconda3\python E:\Software\SadTalker\inference.py --driven_audio E:\Software\SadTalker\audio\NewsAboutAItoday.wav --source_image E:\Software\SadTalker\img\PrettyGirl5.jpg --result_dir E:\Software\SadTalker\output --still --preprocess full --enhancer gfpgan
E:\Software\SadTalker\checkpoints\epoch_20.pth
E:\Software\SadTalker\checkpoints\auido2pose_00140-model.pth
E:\Software\SadTalker\checkpoints\auido2exp_00300-model.pth
E:\Software\SadTalker\checkpoints\facevid2vid_00189-model.pth.tar
E:\Software\SadTalker\checkpoints\mapping_00109-model.pth.tar
3DMM Extraction for source image
landmark Det:: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:15<00:00, 15.17s/it]
3DMM Extraction In Video:: 100%|███████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.62it/s]
mel:: 100%|███████████████████████████████████████████████████████████████████████████| 1722/1722 [00:00<00:00, 20500.15it/s]
audio2exp:: 100%|██████████████████████████████████████████████████████████████████████████| 173/173 [00:11<00:00, 14.69it/s]
Face Renderer:: 100%|████████████████████████████████████████████████████████████████████| 861/861 [8:31:55<00:00, 35.67s/it]
Traceback (most recent call last):
  File "E:\Software\SadTalker\inference.py", line 158, in <module>
    main(args)
  File "E:\Software\SadTalker\inference.py", line 112, in main
    animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "E:\Software\SadTalker\src\facerender\animate.py", line 158, in generate
    result = img_as_ubyte(video)
  File "D:\ProgramData\Anaconda3\lib\site-packages\skimage\util\dtype.py", line 541, in img_as_ubyte
    return _convert(image, np.uint8, force_copy)
  File "D:\ProgramData\Anaconda3\lib\site-packages\skimage\util\dtype.py", line 227, in _convert
    image = np.asarray(image)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 1.26 GiB for an array with shape (1722, 256, 256, 3) and data type float32
看来对性能需要着力优化。

**Comment by vinthony** [comment]
抱歉哈，如果cpu，这个网络确实特别慢。未来会对速度和生成质量进行更新，之前都在修复安装和sdwebui的bug。

**Comment by HUAFOR** [comment]
请问训练这个模型的话最少需要的GPU是多少呢？

**Comment by TsaiKoga** [comment]
希望能够支持在运行时指定mac mps的GPU
