### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by besbesmany** [Winfredy/SadTalker#234]
To create a public link, set `share=True` in `launch()`.
Startup time: 17.3s (import torch: 2.0s, import gradio: 1.2s, import ldm: 1.5s, other imports: 1.0s, setup codeformer: 0.2s, load scripts: 0.8s, load SD checkpoint: 9.1s, create ui: 1.3s, gradio launch: 0.1s).
C:\Users\legion\stable-diffusion\stable-diffusion-webui\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
C:\Users\legion\stable-diffusion\stable-diffusion-webui\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
C:\Users\legion\stable-diffusion\stable-diffusion-webui\extensions\SadTalker\checkpoints\facevid2vid_00189-model.pth.tar
C:\Users\legion\AppData\Local\Temp\tmpbmmpdzlh.png
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.57s/it]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.48it/s]
mel:: 100%|██████████████████████████████████████████████████████████████████████| 905/905 [00:00<00:00, 131599.12it/s]
audio2exp:: 100%|█████████████████████████████████████████████████████████████████████| 91/91 [00:00<00:00, 248.88it/s]
Face Renderer:: 100%|████████████████████████████████████████████████████████████████| 453/453 [03:46<00:00,  2.00it/s]
Traceback (most recent call last):
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 122, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui/extensions/SadTalker\src\facerender\animate.py", line 149, in generate
    predictions_video = make_animation(source_image, source_semantics, target_semantics,
  File "C:\Users\legion\stable-diffusion\stable-diffusion-webui/extensions/SadTalker\src\facerender\modules\make_animation.py", line 138, in make_animation
    predictions_ts = torch.stack(predictions, dim=1)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 680.00 MiB (GPU 0; 6.00 GiB total capacity; 4.02 GiB already allocated; 0 bytes free; 4.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by vinthony** [comment]
you may refer this solution for out of memory problem: https://github.com/Winfredy/SadTalker/issues/196#issuecomment-1512768312
