### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by MetAIvisuals** [Winfredy/SadTalker#237]
Traceback (most recent call last):
  File "G:\Programme\STABLE DIFFUSION\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Programme\STABLE DIFFUSION\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "G:\Programme\STABLE DIFFUSION\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Programme\STABLE DIFFUSION\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Programme\STABLE DIFFUSION\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\Programme\STABLE DIFFUSION\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\Programme\STABLE DIFFUSION\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "G:\Programme\STABLE DIFFUSION/extensions/SadTalker\src\gradio_demo.py", line 65, in test
    self.audio_to_coeff = Audio2Coeff(self.audio2pose_checkpoint, self.audio2pose_yaml_path,
  File "G:\Programme\STABLE DIFFUSION/extensions/SadTalker\src\test_audio2coeff.py", line 35, in __init__
    self.audio2pose_model = Audio2Pose(cfg_pose, wav2lip_checkpoint, device=device)
  File "G:\Programme\STABLE DIFFUSION/extensions/SadTalker\src\audio2pose_models\audio2pose.py", line 15, in __init__
    self.audio_encoder = AudioEncoder(wav2lip_checkpoint, device)
  File "G:\Programme\STABLE DIFFUSION/extensions/SadTalker\src\audio2pose_models\audio_encoder.py", line 45, in __init__
    wav2lip_state_dict = torch.load(wav2lip_checkpoint, map_location=torch.device(device))['state_dict']
TypeError: 'NoneType' object is not subscriptable

**Comment by MetAIvisuals** [comment]
Hm, I treid that, but its not working still

**Comment by vinthony** [comment]
redownload the checkpoint of `wav2lip.pth`

**Comment by codeViii** [comment]
still not working
