### ISSUE TITLE
Help. i tried installing ffmpeg now my stable diffusion wont work

### ISSUE THREAD

**Issue by stts111** [Winfredy/SadTalker#243]
i tried installing ffmpeg and it said i had to change my path to setx /m PATH "C:\Users/user_name/ffmpeg\bin;%PATH%"  

now when i launch stable diffusion i get this error 

venv "C:\ai\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\launch.py", line 360, in <module>
    prepare_environment()
  File "C:\ai\stable-diffusion-webui\launch.py", line 300, in prepare_environment
    git_clone(stable_diffusion_repo, repo_dir('stable-diffusion-stability-ai'), "Stable Diffusion", stable_diffusion_commit_hash)
  File "C:\ai\stable-diffusion-webui\launch.py", line 151, in git_clone
    current_hash = run(f'"{git}" -C "{dir}" rev-parse HEAD', None, f"Couldn't determine {name}'s hash: {commithash}").strip()
  File "C:\ai\stable-diffusion-webui\launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't determine Stable Diffusion's hash: 47b6b607fdd31875c9279cd2f4f16b92e4ea958e.
Command: "git" -C "repositories\stable-diffusion-stability-ai" rev-parse HEAD
Error code: 1
stdout: <empty>
stderr: '"git"' is not recognized as an internal or external command,
operable program or batch file.

Press any key to continue . . .

**Comment by vinthony** [comment]
I guess you have deleted the PATH by mistake.

try to reinstall the `git` https://git-scm.com/download/win

**Comment by vinthony** [comment]
It seems `ffmpeg` can be easily installed via `scoop install ffmpeg`, you may try it on Windows(https://scoop.sh/).

**Comment by AndyCyberSec** [comment]
I have the same issue, env variable is not deleted.
I think it's more like once automatic1111 is started in python virtual environment it discards some Windows env var. In fact, if I stop automatic1111 and run ffmpeg command, the command is not found anymore.

So as a very ugly but fast workaround, if you placed ffmpeg in C:\ffmpeg you should edit the following files in webui\extensions\ebsynth_utility:

replace ffmpeg with C:\\ffmpeg\bin\\ffmpeg in:

stage1.py Line 197
stage7.py Line 31, Line 98, Line 103
stage8.py Line 67
