### ISSUE TITLE
ImportError: DLL load failed while importing _dlib_pybind11: 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by luolin19850304** [Winfredy/SadTalker#319]
Error executing callback ui_tabs_callback for C:\novelai-webui-aki-v2\extensions\SadTalker\scripts\extension.py
Traceback (most recent call last):
  File "C:\novelai-webui-aki-v2\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "C:\novelai-webui-aki-v2\extensions\SadTalker\scripts\extension.py", line 141, in on_ui_tabs
    from src.gradio_demo import SadTalker
  File "C:\novelai-webui-aki-v2/extensions/SadTalker\src\gradio_demo.py", line 3, in <module>
    from src.utils.preprocess import CropAndExtract
  File "C:\novelai-webui-aki-v2/extensions/SadTalker\src\utils\preprocess.py", line 19, in <module>
    from src.utils.croper import Croper
  File "C:\novelai-webui-aki-v2/extensions/SadTalker\src\utils\croper.py", line 32, in <module>
    import dlib
  File "C:\novelai-webui-aki-v2\py310\lib\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed while importing _dlib_pybind11: 动态链接库(DLL)初始化例程失败。
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

----------------
使用的是秋葉aaaki的novelai整合包，启动loading checkpoints时总会出现错误（mistakes），页面也不出现sadtalkers菜单（menu），帮我看看怎么回事。

**Comment by vinthony** [comment]
这个是windows下安装dlib的问题，现在新版可以不用安装了。
