### ISSUE TITLE
Ubuntu runtime error: init_ Alignment_ Model() got an unexpected keyword argument 'model_ Rootpath '

### ISSUE THREAD

**Issue by shiyueGG** [Winfredy/SadTalker#398]
`(sadtalker) root@autodl-container-40b311b9f2-f5a0d366:~/SadTalker# python inference.py
using safetensor as default
Traceback (most recent call last):
  File "inference.py", line 150, in <module>
    main(args)
  File "inference.py", line 42, in main
    preprocess_model = CropAndExtract(sadtalker_paths, device)
  File "/root/SadTalker/src/utils/preprocess.py", line 49, in __init__
    self.propress = Preprocesser(device)
  File "/root/SadTalker/src/utils/croper.py", line 21, in __init__
    self.predictor = KeypointExtractor(device)
  File "/root/SadTalker/src/face3d/extract_kp_videos_safe.py", line 27, in __init__
    self.detector = init_alignment_model('awing_fan',device=device, model_rootpath=root_path)   
TypeError: init_alignment_model() got an unexpected keyword argument 'model_rootpath'`

**Comment by vinthony** [comment]
which facexlib version are you using?

**Comment by shiyueGG** [comment]
> which facexlib version are you using?

Name: facexlib
Version: 0.2.4
Summary: Basic face library

**Comment by shiyueGG** [comment]
> which facexlib version are you using?

reinstalling version 0.3.0 resolved this issue
