### ISSUE TITLE
关于自定义音频

### ISSUE THREAD

**Issue by skyeKing** [Winfredy/SadTalker#50]
我这边想通过调用国内的语音合成，从文字生成语音，现阶段测试选的标贝的。将音频输入进去之后报错
![微信图片_20230330171502](https://user-images.githubusercontent.com/17171471/228789350-bd440de0-1648-4324-83b6-ed9af9815a67.png)
报错log如下
Traceback (most recent call last):
  File "inference.py", line 133, in <module>
    main(args)
  File "inference.py", line 72, in main
    coeff_path = audio_to_coeff.generate(batch, save_dir, pose_style)
  File "E:\PycharmProjects\SadTalker_Git\src\test_audio2coeff.py", line 74, in generate
    results_dict_pose = self.audio2pose_model.test(batch) 
  File "E:\PycharmProjects\SadTalker_Git\src\audio2pose_models\audio2pose.py", line 85, in test
    batch = self.netG.test(batch)
  File "E:\PycharmProjects\SadTalker_Git\src\audio2pose_models\cvae.py", line 49, in test
    return self.decoder(batch)
  File "E:\Anaconda3\envs\sadtalker\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\PycharmProjects\SadTalker_Git\src\audio2pose_models\cvae.py", line 139, in forward
    x_out = self.MLP(x_in)                                  # bs layer_sizes[-1]
  File "E:\Anaconda3\envs\sadtalker\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Anaconda3\envs\sadtalker\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "E:\Anaconda3\envs\sadtalker\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Anaconda3\envs\sadtalker\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x220 and 262x128)
仔细翻看了readme，并未发现对音频文件有说明，劳烦大佬了

**Comment by vinthony** [comment]
音频多长呢？

**Comment by Winfredy** [comment]
这个是因为音频长度过短导致的，这个bug我们已经修复了，你可以更新最新的代码，重新测试

**Comment by skyeKing** [comment]
最终的解决方案是通过ffmpeg将音频的采样率从16k提高24k。
音频果断的问题我在自己测试的时候遇见了，手动做了区分，感谢大佬更新，我这就去更新
