### ISSUE TITLE
使用cpu版本渲染时解码音频部分出现异常

### ISSUE THREAD

**Issue by bjfrbjx** [Winfredy/SadTalker#53]
完整异常栈：
`Traceback (most recent call last):
  File "E:\learn\sadtalker\inference.py", line 141, in <module>
    main(args)
  File "E:\learn\sadtalker\inference.py", line 53, in main
    audio_to_coeff = Audio2Coeff(audio2pose_checkpoint, audio2pose_yaml_path, 
  File "E:\learn\sadtalker\src\test_audio2coeff.py", line 35, in __init__
    self.audio2pose_model = Audio2Pose(cfg_pose, wav2lip_checkpoint, device=device)
  File "E:\learn\sadtalker\src\audio2pose_models\audio2pose.py", line 15, in __init__
    self.audio_encoder = AudioEncoder(wav2lip_checkpoint,device=device)
  File "E:\learn\sadtalker\src\audio2pose_models\audio_encoder.py", line 45, in __init__
    wav2lip_state_dict = torch.load(wav2lip_checkpoint)['state_dict']
  File "E:\venv\sadtalker\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\venv\sadtalker\lib\site-packages\torch\serialization.py", line 930, in _legacy_load
    result = unpickler.load()
  File "E:\venv\sadtalker\lib\site-packages\torch\serialization.py", line 876, in persistent_load
    wrap_storage=restore_location(obj, location),
  File "E:\venv\sadtalker\lib\site-packages\torch\serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "E:\venv\sadtalker\lib\site-packages\torch\serialization.py", line 152, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "E:\venv\sadtalker\lib\site-packages\torch\serialization.py", line 136, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`

解决方法：1.AudioEncoder构造函数添加device,从外部传入。
                  2. `torch.load(wav2lip_checkpoint)['state_dict']` 改为
                  `wav2lip_state_dict = torch.load(wav2lip_checkpoint,map_location=torch.device(device))['state_dict']`
顺带一提，#注释最后最后一位用\结尾的话会导致pychram的debug点不了下一行

**Comment by vinthony** [comment]
这个问题在写gradio demo 的时候发现了，会fixed 掉。
