### ISSUE TITLE
TypeError: zoom() got an unexpected keyword argument 'grid_mode'

### ISSUE THREAD

**Issue by chrisbward** [Winfredy/SadTalker#6]
```
python inference.py --driven_audio japanese.wav --source_image art_1.png --result_dir .
checkpoints/epoch_20.pth
checkpoints/auido2pose_00140-model.pth
checkpoints/auido2exp_00300-model.pth
checkpoints/facevid2vid_00189-model.pth.tar
checkpoints/mapping_00229-model.pth.tar
landmark Det:: 100%|██████████████████████████████| 1/1 [00:04<00:00,  4.67s/it]
 3DMM Extraction In Video:: 100%|█████████████████| 1/1 [00:00<00:00,  6.51it/s]
Traceback (most recent call last):
  File "inference.py", line 98, in <module>
    main(args)
  File "inference.py", line 73, in main
    data = get_facerender_data(coeff_path, crop_pic_path, first_coeff_path, audio_path, 
  File "/media/user/home/04_MachineLearning/10_talkingheads/SadTalker/generate_facerender_batch.py", line 20, in get_facerender_data
    source_image = transform.resize(source_image, (256, 256, 3))
  File "/media/user/home/04_MachineLearning/10_talkingheads/SadTalker/.venv/lib/python3.8/site-packages/skimage/transform/_warps.py", line 186, in resize
    out = ndi.zoom(image, zoom_factors, order=order, mode=ndi_mode,
TypeError: zoom() got an unexpected keyword argument 'grid_mode'

```

**Comment by chrisbward** [comment]
https://github.com/scipy/scipy/pull/13095

could only find a reference here, fix is;

```
pip install scipy==1.6.0
```

Guys. Please test your work before publishing it. It's not hard.

**Comment by seshubonam** [comment]
hi chris, do you think this could work for real time interactive talking head application? like https://chat.d-id.com/
