### ISSUE TITLE
Extension RuntimeError: Couldn't install requirements for SadTalker.

### ISSUE THREAD

**Issue by PsychoSmiley** [Winfredy/SadTalker#64]
0. Describe the bug

After Installing Extension and apply, Tab Animation does not show

2. Initial troubleshooting

- Updated the Stable-Diffusion-WebUI to the latest version
- Updated SadTalker extension to the latest revision
- Completely restarted the stable-diffusion-webUI, not just reloaded the UI

2. following lines in the console

```
[+] xformers version 0.0.17rc482 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.
...
face-alignment False
Installing requirements for SadTalker
imageio True
imageio-ffmpeg False
Installing requirements for SadTalker
librosa True
pydub True
scipy True
tqdm True
yacs True
pyyaml False
Installing requirements for SadTalker
dlib True
gfpgan True
TTS False
Installing requirements for SadTalker
Error executing callback ui_tabs_callback for C:\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "C:\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 60, in on_ui_tabs
    install()
  File "C:\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 50, in install
    launch.run_pip("install "+ v, "requirements for SadTalker")
  File "C:\stable-diffusion-webui\launch.py", line 145, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "C:\stable-diffusion-webui\launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for SadTalker.
Command: "C:\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install tts==0.13.0 --prefer-binary
Error code: 1
```

4. Environment
What OS?
Windows

If Windows - WSL or native?
Native

**Comment by zhuyefan** [comment]
me too

**Comment by vinthony** [comment]
fixed. TTS can not directly install in windows. we remove it in sdwebui for a clear and easy environment.
