### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by pk5ls20** [Winfredy/SadTalker#68]
env：Windows11
当尝试使用`python app.py`生成时报错
```
C:\Users\pk5ls\AppData\Local\Temp\522882b377634f2b601b0a1d0f86207d7ee54fdb\tmpkvypcmaj.png
Traceback (most recent call last):
  File "C:\Users\pk5ls\anaconda3\envs\sadtalker\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\pk5ls\anaconda3\envs\sadtalker\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\Users\pk5ls\anaconda3\envs\sadtalker\lib\site-packages\gradio\blocks.py", line 915, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\pk5ls\anaconda3\envs\sadtalker\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\pk5ls\anaconda3\envs\sadtalker\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\pk5ls\anaconda3\envs\sadtalker\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\ai-draw\SadTalker\src\gradio_demo.py", line 101, in test
    first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir)
  File "E:\ai-draw\SadTalker\src\utils\preprocess.py", line 84, in generate
    x_full_frames, crop, quad = self.croper.crop(x_full_frames, xsize=pic_size)
TypeError: cannot unpack non-iterable NoneType object
```
在`stable-diffusion`的插件中使用同样报错

**Comment by vinthony** [comment]
C:\Users\pk5ls\AppData\Local\Temp\522882b377634f2b601b0a1d0f86207d7ee54fdb\tmpkvypcmaj.png 这张图可以上传我看看吗

**Comment by pk5ls20** [comment]
哦对...看上去它处理二次元型图片会报错，而处理2.5d/三次元图片（也就是webui下面Examples那样）则不会报错
附图：
![1](https://user-images.githubusercontent.com/114645197/230717223-353a8337-4621-4137-969f-6b4f4a90fb02.png)

**Comment by vinthony** [comment]
我们的模型是在真实数据训练的，太二次元的检测不到人脸~ 可能后续会集成[tha2/tha3](https://github.com/pkhungurn/talking-head-anime-2-demo)的功能，就可以处理anime了

**Comment by pk5ls20** [comment]
> 我们的模型是在真实数据训练的，太二次元的检测不到人脸~ 可能后续会集成[tha2/tha3](https://github.com/pkhungurn/talking-head-anime-2-demo)的功能，就可以处理anime了

好的好的🥰
