### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by robbfans** [Winfredy/SadTalker#691]
(base) C:\Users\yt\SadTalker>python inference.py --driven_audio C:\Users\yt\SadTalker\input\1.wav --source_image C:\Users\yt\SadTalker\input\1.jpg --result_dir C:\Users\yt\SadTalker\output --still --enhancer gfpgan --full_img_enhancer gfpgan
Traceback (most recent call last):
  File "C:\Users\yt\SadTalker\inference.py", line 8, in <module>
    from src.utils.preprocess import CropAndExtract
  File "C:\Users\yt\SadTalker\src\utils\preprocess.py", line 2, in <module>
    import cv2, os, sys, torch
ModuleNotFoundError: No module named 'cv2'

按教程安装了很多次，都是这个错误

**Comment by robbfans** [comment]
Traceback (most recent call last):
  File "inference.py", line 10, in <module>
    from src.facerender.animate import AnimateFromCoeff
  File "C:\Users\yt\SadTalker\src\facerender\animate.py", line 23, in <module>
    from src.utils.face_enhancer import enhancer_generator_with_len, enhancer_list
  File "C:\Users\yt\SadTalker\src\utils\face_enhancer.py", line 4, in <module>
    from gfpgan import GFPGANer
ImportError: cannot import name 'GFPGANer' from 'gfpgan' (unknown location)

现在是这个问题了

**Comment by LiMuma** [comment]
pip install opencv-python
