### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by sleechengn** [Winfredy/SadTalker#692]
Launching SadTalker Web UI
Traceback (most recent call last):
  File "Launcher.py", line 204, in <module>
    start()
  File "Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "D:\soft\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

**Comment by easyontheice** [comment]
Replace app_sadtalker.py with this file:

[app_sadtalker.zip](https://github.com/OpenTalker/SadTalker/files/13259997/app_sadtalker.zip)

**Comment by bitsentinel-cell** [comment]
> Replace app_sadtalker.py with this file:
> 
> [app_sadtalker.zip](https://github.com/OpenTalker/SadTalker/files/13259997/app_sadtalker.zip)

you are an unsung hero
