### ISSUE TITLE
AttributeError: 'Row' object has no attribute 'style'

### ISSUE THREAD

**Issue by HubsFeed** [Winfredy/SadTalker#694]
I can’t start SadTalker on PC, it shows this:

venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "C:\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "C:\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.
Press any key to continue . . .

please tell me how to fix it

**Comment by BertyBermuda** [comment]
I got the same error, not sure how to fix this. I hope someone smarter will tell us what to do next! :) tx.

**Comment by easyontheice** [comment]
Replace app_sadtalker.py with this file:

[app_sadtalker.zip](https://github.com/OpenTalker/SadTalker/files/13259997/app_sadtalker.zip)

**Comment by javarike** [comment]
> Replace app_sadtalker.py with this file:
> 
> [app_sadtalker.zip](https://github.com/OpenTalker/SadTalker/files/13259997/app_sadtalker.zip)

this work! thanks for your greate help!!!
