### ISSUE TITLE
got an unexpected keyword argument 'audio_path'

### ISSUE THREAD

**Issue by javarike** [Winfredy/SadTalker#695]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/workspace/stable-diffusion-webui/modules/call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "/mnt/workspace/stable-diffusion-webui/extensions/SadTalker/src/gradio_demo.py", line 139, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess, img_size=size)
  File "/mnt/workspace/stable-diffusion-webui/extensions/SadTalker/src/facerender/animate.py", line 205, in generate
    imageio.mimsave(path, result,  fps=float(25))
  File "/usr/local/lib/python3.10/dist-packages/imageio/v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/imageio/core/legacy_plugin_wrapper.py", line 253, in write
    writer.append_data(image, metadata)
  File "/usr/local/lib/python3.10/dist-packages/imageio/core/format.py", line 590, in append_data
    return self._append_data(im, total_meta)
  File "/usr/local/lib/python3.10/dist-packages/imageio/plugins/ffmpeg.py", line 587, in _append_data
    self._initialize()
  File "/usr/local/lib/python3.10/dist-packages/imageio/plugins/ffmpeg.py", line 630, in _initialize
    self._write_gen = self._ffmpeg_api.write_frames(
TypeError: write_frames() got an unexpected keyword argument 'audio_path'`
env:Ubuntu 22.04.1 LTS
python: 3.10.6
sadtalker:the last new version

**Comment by ningbende** [comment]
+1

**Comment by skywolf123** [comment]
Try to query the version of imageio_ffmpeg. If the version is near 0.4.2, please upgrade the version.
pip show imageio_ffmpeg
