### ISSUE TITLE
Colab error

### ISSUE THREAD

**Issue by impactcolor** [Winfredy/SadTalker#701]
Maybe this is related to the other issues mentioned on the issues.
From Automatic1111 colab link.

2023-11-08 00:29:56.888842: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-08 00:29:56.888889: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-08 00:29:56.888924: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-08 00:29:57.946442: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

**Comment by G-force78** [comment]
Another one

Traceback (most recent call last):
  File "/content/SadTalker/app_sadtalker.py", line 3, in <module>
    from src.gradio_demo import SadTalker  
  File "/content/SadTalker/src/gradio_demo.py", line 3, in <module>
    from src.utils.preprocess import CropAndExtract
  File "/content/SadTalker/src/utils/preprocess.py", line 2, in <module>
    import cv2, os, sys, torch
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/cv2/typing/__init__.py", line 69, in <module>
    NumPyArrayGeneric = numpy.ndarray[typing.Any, numpy.dtype[numpy.generic]]
TypeError: 'numpy._DTypeMeta' object is not subscriptable

**Comment by G-force78** [comment]
This one works, cloned from huggingface, it is a standalone version
https://colab.research.google.com/drive/1PbVhMuSIaO37q2kvaYh7Tp98JDgNVJfI#scrollTo=Z8BBgh8Byr2n

**Comment by impactcolor** [comment]
@G-force78 the colab one works but the automatic1111 doesn't.  The issue with the regular colab is that it doesn't have any options like the hugging faces.  I would use hugging faces but it's always busy and cloning is pretty expensive at $3 an hour.

**Comment by G-force78** [comment]
> @G-force78 the colab one works but the automatic1111 doesn't. The issue with the regular colab is that it doesn't have any options like the hugging faces. I would use hugging faces but it's always busy and cloning is pretty expensive at $3 an hour.

Have you tried it? The colab I linked is the huggingface version just ran on google colab servers instead and has all the options.

**Comment by rachit2315** [comment]
try this it would work https://colab.research.google.com/drive/13noy3VptwctpwKYcdcz58HeJUE6oWZNs?usp=sharing

**Comment by impactcolor** [comment]
@G-force78 yes it worked perfect THANK YOU!!!
