### ISSUE TITLE
RuntimeError: unexpected EOF, expected 133090 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by wustii** [Winfredy/SadTalker#726]
using safetensor as default
{'checkpoint': 'C:\\Users\\wusti\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'C:\\Users\\wusti\\stable-diffusion-webui/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'C:\\Users\\wusti\\stable-diffusion-webui/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'C:\\Users\\wusti\\stable-diffusion-webui/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'C:\\Users\\wusti\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'C:\\Users\\wusti\\stable-diffusion-webui/extensions/SadTalker/src/config\\facerender.yaml'}
Traceback (most recent call last):
  File "C:\Users\wusti\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\wusti\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\wusti\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\wusti\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\wusti\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\wusti\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\wusti\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\wusti\stable-diffusion-webui\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "C:\Users\wusti\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 50, in test
    self.preprocess_model = CropAndExtract(self.sadtalker_paths, self.device)
  File "C:\Users\wusti\stable-diffusion-webui/extensions/SadTalker\src\utils\preprocess.py", line 49, in __init__
    self.propress = Preprocesser(device)
  File "C:\Users\wusti\stable-diffusion-webui/extensions/SadTalker\src\utils\croper.py", line 21, in __init__
    self.predictor = KeypointExtractor(device)
  File "C:\Users\wusti\stable-diffusion-webui/extensions/SadTalker\src\face3d\extract_kp_videos_safe.py", line 46, in __init__
    self.det_net = init_detection_model('retinaface_resnet50', half=False,device=device, model_rootpath=root_path)
  File "C:\Users\wusti\stable-diffusion-webui\venv\lib\site-packages\facexlib\detection\__init__.py", line 22, in init_detection_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "C:\Users\wusti\stable-diffusion-webui\modules\safe.py", line 108, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "C:\Users\wusti\stable-diffusion-webui\modules\safe.py", line 156, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\Users\wusti\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\wusti\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 133090 more bytes. The file might be corrupted.

How to fix that?I have searched in many places but I can't solve the problem? Can you help me please?

**Comment by shareholdr** [comment]
Do this instead of hussle with the local version, full guide on how to get the Google colab variant to work here https://vm.tiktok.com/ZGeLNu2yq/
