### ISSUE TITLE
mac提示torch版本不兼容， pip安装的是2.0.x

### ISSUE THREAD

**Issue by dillonchen001** [Winfredy/SadTalker#729]
Installing torch and torchvision
ERROR: Could not find a version that satisfies the requirement torch==1.12.1 (from versions: 2.0.0, 2.0.1, 2.1.0, 2.1.1)
ERROR: No matching distribution found for torch==1.12.1
Traceback (most recent call last):
  File "/Users/hao/Downloads/SadTalker/launcher.py", line 203, in <module>
    prepare_environment()
  File "/Users/hao/Downloads/SadTalker/launcher.py", line 187, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "/Users/hao/Downloads/SadTalker/launcher.py", line 70, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "/Users/hao/Downloads/SadTalker/venv/bin/python3" -m pip install torch==1.12.1 torchvision==0.13.1
Error code: 1

**Comment by dillonchen001** [comment]
pip install torch==1.12.1                                                    
Collecting torch==1.12.1
  Downloading torch-1.12.1-cp38-none-macosx_10_9_x86_64.whl (137.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.8/137.8 MB 2.7 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions in /usr/local/anaconda3/envs/sadtalker/lib/python3.8/site-packages (from torch==1.12.1) (4.8.0)
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 2.1.1
    Uninstalling torch-2.1.1:
      Successfully uninstalled torch-2.1.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.1 requires torch==2.1.1, but you have torch 1.12.1 which is incompatible.
torchvision 0.16.1 requires torch==2.1.1, but you have torch 1.12.1 which is incompatible.

**Comment by jelly-liu** [comment]
works on my m1 mac, make sure you activate python3.8 env through conda:
>>pip list | grep torch:
>>torch                     2.1.2
>>torchaudio                2.1.2
>>torchvision               0.16.2
or, you can add code after this line: printf "Launching launcher.py..." in web-ui.sh, will show you the torch and vision version.
python3 --version
python3 -c "import torch; print(torch.__version__)"
python3 -c "import torchvision; print(torchvision.__version__)"

**Comment by jelly-liu** [comment]
python3 --version
python3 -c "import torch; print(torch.__version__)"
python3 -c "import torchvision; print(torchvision.__version__)"
