### ISSUE TITLE
Getting TypeError: 'numpy._DTypeMeta' object is not subscriptable, when launching webui on local machine.

### ISSUE THREAD

**Issue by toheedakhtar** [Winfredy/SadTalker#730]
Traceback (most recent call last):
  File "C:\Projects\SadTalker_1\SadTalker\Launcher.py", line 199, in <module>
    start()
  File "C:\Projects\SadTalker_1\SadTalker\Launcher.py", line 192, in start
    from app import sadtalker_demo
  File "C:\Projects\SadTalker_1\SadTalker\app.py", line 3, in <module>
    from src.gradio_demo import SadTalker  
  File "C:\Projects\SadTalker_1\SadTalker\src\gradio_demo.py", line 3, in <module>
    from src.utils.preprocess import CropAndExtract
  File "C:\Projects\SadTalker_1\SadTalker\src\utils\preprocess.py", line 2, in <module>
    import cv2, os, sys, torch
  File "C:\Projects\SadTalker_1\SadTalker\venv\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Projects\SadTalker_1\SadTalker\venv\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Projects\SadTalker_1\SadTalker\venv\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Projects\SadTalker_1\SadTalker\venv\lib\site-packages\cv2\typing\__init__.py", line 69, in <module>
    NumPyArrayGeneric = numpy.ndarray[typing.Any, numpy.dtype[numpy.generic]]
TypeError: 'numpy._DTypeMeta' object is not subscriptable

**Comment by shareholdr** [comment]
Do this instead of hussle with the local version, full guide on how to get the Google colab variant to work here https://vm.tiktok.com/ZGeLNu2yq/
