### ISSUE TITLE
Trojan detected when uncompressing facevid2vid_00189-model.pth

### ISSUE THREAD

**Issue by uisato** [Winfredy/SadTalker#75]
Anyone else experiencing this? I've downloaded checkpoints and + from the designated Google Drive.

**Comment by vinthony** [comment]
you do not need to uncompress these checkpoints

**Comment by ameen-roayan** [comment]
Actually getting errors for file not found, that is why i compressed mine and then got these errors as well. 
![image](https://user-images.githubusercontent.com/92278134/230779285-2f9c1107-4358-4adf-95d5-af8064845592.png)

**Comment by vinthony** [comment]
will try to solve it.

**Comment by uisato** [comment]
Don't get me wrong, pal. I love your work. But I shouldn't be getting those alerts. Neither should I start with some of the arguments for the webui. 

Why did you tagged this post as invalid?

**Comment by vinthony** [comment]
> Don't get me wrong, pal. I love your work. But I shouldn't be getting those alerts. Neither should I start with some of the arguments for the webui.
> 
> Why did you tagged this post as invalid?

change to enhancement

**Comment by bbecausereasonss** [comment]
Yeah why should we being removing safe unpickle, especially when we're getting trojan warnings.

**Comment by vinthony** [comment]
> 

fixed.

**Comment by ameen-roayan** [comment]
Thanks for that, now getting these errors instead 

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 13.5s (load scripts: 0.7s, create ui: 12.5s, gradio launch: 0.1s).
Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 333, in svgPreprocess
    if (inputs['image'].startswith("data:image/svg+xml;base64,") and svgsupport):
TypeError: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 333, in svgPreprocess
    if (inputs['image'].startswith("data:image/svg+xml;base64,") and svgsupport):
TypeError: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range

**Comment by vinthony** [comment]
it seems the errors in controlnet?

**Comment by LeaderBronze** [comment]
SO it iis a trojan or not?
