### ISSUE TITLE
python app_sadtalker.py run error

### ISSUE THREAD

**Issue by ashishakkumar** [Winfredy/SadTalker#756]
Running on my MacOS machine. Installed as per the instructions. Giving error, : OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Traceback (most recent call last):
  File "app_sadtalker.py", line 107, in <module>
    demo = sadtalker_demo()
  File "app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

**Comment by priamai** [comment]
Exactly the same error for me, just pulled from the main branch.
I am not a Gradio expert so I can't really figure out what's going on.

**Comment by baihongyu123456** [comment]
Exactly the same error for me,

**Comment by baihongyu123456** [comment]
Launching SadTalker Web UI
Traceback (most recent call last):
  File "D:\soft\sadtalker\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "D:\soft\sadtalker\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "D:\soft\sadtalker\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

**Comment by mynumu** [comment]
Same error here tried Conda and standard git clone install - didnt see that its already logged

nstalling requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "C:\Users\Sam\AI\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "C:\Users\Sam\AI\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\Users\Sam\AI\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.
Press any key to continue . . .

Anyone have a fix? TIA

**Comment by yslin1995** [comment]
try `pip install gradio==3.41.2`

**Comment by hixuco** [comment]
> pip install gradio==3.41.2

No, this installed OK but doesn't fix the problem
