### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'lower'

### ISSUE THREAD

**Issue by ourladyofagi** [Winfredy/SadTalker#76]
Receiving the above error with the automatic1111 extension. Running Windows11.

`Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 110, in test
    first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir,preprocess)
  File "C:\stable-diffusion-webui/extensions/SadTalker\src\utils\preprocess.py", line 85, in generate
    if crop_or_resize.lower() == 'crop': # default crop
AttributeError: 'bool' object has no attribute 'lower'`

**Comment by vinthony** [comment]
fixed due to upgrade in v0.0.2
