### ISSUE TITLE
running simple example fails

### ISSUE THREAD

**Issue by priamai** [Winfredy/SadTalker#763]
Hello there,
this is from them main branch:

```
python inference.py --driven_audio ./examples/driven_audio/bus_chinese.wav \
                    --source_image ./examples/source_image/art_2.png \
                    --still \
                    --preprocess full \
                    --enhancer gfpgan 
```

Error output below:

```
using safetensor as default
3DMM Extraction for source image
landmark Det:: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.74it/s]
3DMM Extraction In Video:: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.61it/s]
mel:: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84/84 [00:00<00:00, 30687.36it/s]
audio2exp:: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 259.92it/s]
Face Renderer:: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 42/42 [00:07<00:00,  5.79it/s]
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (256, 247) to (256, 256) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
sh: 1: ffmpeg: not found
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.10.6/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'ad4bae68-7726-4fd7-baa5-41abe34af027.mp4' -> './results/2023_12_27_08.32.05/art_2##bus_chinese.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/SadTalker/inference.py", line 144, in <module>
    main(args)
  File "/home/ubuntu/SadTalker/inference.py", line 87, in main
    result = animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "/home/ubuntu/SadTalker/src/facerender/animate.py", line 222, in generate
    save_video_with_watermark(path, new_audio_path, av_path, watermark= False)
  File "/home/ubuntu/SadTalker/src/utils/videoio.py", line 26, in save_video_with_watermark
    shutil.move(temp_file, save_path)
  File "/home/ubuntu/.pyenv/versions/3.10.6/lib/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/home/ubuntu/.pyenv/versions/3.10.6/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ubuntu/.pyenv/versions/3.10.6/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'ad4bae68-7726-4fd7-baa5-41abe34af027.mp4'
```
Any idea why this is happening?
The output video is there but the audio is missing.

**Comment by priamai** [comment]
Closing this down, as it was related to missing ffpmeg although the error was very unclear.

**Comment by priamai** [comment]
Closing.

**Comment by prog-ape** [comment]
> Closing this down, as it was related to missing ffpmeg although the error was very unclear.

May I ask how you solved this problem？

**Comment by priamai** [comment]
Yes sorry I did install ffpmef via apt and that fixed the problem.
