### ISSUE TITLE
WebUI Install Issue on Windows - Conda and GitClone python app_sadtalker.py run error

### ISSUE THREAD

**Issue by mynumu** [Winfredy/SadTalker#765]
hi - im seeing this error when trying to run sadtalker on Windows 10.
Tried a conda install and just a standard gitclone of your main repo

Is this an error in the webui launch script??

Thanks

nstalling requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "C:\Users\Sam\AI\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "C:\Users\Sam\AI\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\Users\Sam\AI\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.
Press any key to continue . . .

**Comment by trucaliber** [comment]
It's an argument, not a method. I changed `with gr.Row().style(equal_height=False):` to `with gr.Row(equal_height=False):`

https://www.gradio.app/guides/controlling-layout

**Comment by trucaliber** [comment]
I'm now stuck on another error.

> Launching SadTalker Web UI
> Traceback (most recent call last):
>   File "Launcher.py", line 204, in <module>
>     start()
>   File "Launcher.py", line 198, in start
>     demo = sadtalker_demo()
>   File "H:\SadTalker\app_sadtalker.py", line 40, in sadtalker_demo
>     source_image = gr.Image(label="Source image", source="upload", type="filepath", elem_id="img2img_image").style(width=512)
>   File "H:\SadTalker\venv\lib\site-packages\gradio\component_meta.py", line 157, in wrapper
>     return fn(self, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'source'

**Comment by writeboywrite** [comment]
I had the same issue as mynumu with the webui launch script. I tried the fix trucaliber suggested in the app_sadtalker.py file, and changed with gr.Row().style(equal_height=False): to with gr.Row(equal_height=False):.

That got rid of that specific error when running the WebUI.bat file.

However, it immediately got replaced with a new error, which reads:

Traceback (most recent call last):
  File "C:\AI\SadTalker\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "C:\AI\SadTalker\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\AI\SadTalker\SadTalker\app_sadtalker.py", line 40, in sadtalker_demo
    source_image = gr.Image(label="Source image", source="upload", type="filepath", elem_id="img2img_image").style(width=512)
  File "C:\AI\SadTalker\SadTalker\venv\lib\site-packages\gradio\component_meta.py", line 157, in wrapper
    return fn(self, **kwargs)
TypeError: Image.__init__() got an unexpected keyword argument 'source'

Launch unsuccessful. Exiting.
Press any key to continue . . .

I have no idea how to fix this.

Maybe I need to upgrade or downgrade the Gradio library? Or ... maybe remove or replace the source argument in the Image.__init__() ??? 

I'm not sure how to do the latter, so I'm going to start by upgrading the Gradio library and see if that helps. (Update - nope. Upgrading the Gradio library didn't help.)

**Comment by qipinzheng** [comment]
卸载 pip uninstall gradio

重新安装降级版本 pip install gradio==3.50.2

**Comment by solai25** [comment]
> 卸载 pip uninstall gradio
> 
> 重新安装降级版本 pip install gradio==3.50.2

this works for me
