### ISSUE TITLE
Mac M2 install issue - Numba failure

### ISSUE THREAD

**Issue by AHLEditor** [Winfredy/SadTalker#766]
Just installed Sadtalker.  Mac (M2).  Running webui.sh I get the following:

Python 3.8.18 (default, Sep 11 2023, 08:17:16) 
[Clang 14.0.6 ]
Commit hash: cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8
Installing requirements for SadTalker WebUI (may take longer time in first time)
Traceback (most recent call last):
  File "launcher.py", line 203, in <module>
    prepare_environment()
  File "launcher.py", line 189, in prepare_environment
    run_pip(f"install -r \"{requirements_file}\"", "requirements for SadTalker WebUI (may take longer time in first time)")
  File "launcher.py", line 118, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "launcher.py", line 86, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for SadTalker WebUI (may take longer time in first time).
Command: "/Users/stammer/sadtalker/SadTalker/venv/bin/python3" -m pip install -r "req.txt" --prefer-binary
Error code: 1

[...]

Building wheels for collected packages: numba
  Building wheel for numba (setup.py): started
  Building wheel for numba (setup.py): finished with status 'error'
  Running setup.py clean for numba
Failed to build numba
Installing collected packages: numba, markdown-it-py, jinja2, importlib-resources, importlib-metadata, imageio, httpcore, contourpy, cffi, anyio, yapf, starlette, soundfile, scikit-learn, scikit-image, rich, resampy, pandas, matplotlib, markdown, kornia, jsonschema-specifications, huggingface-hub, httpx, google-auth, librosa, jsonschema, gradio-client, google-auth-oauthlib, filterpy, fastapi, face_alignment, tb-nightly, facexlib, altair, gradio, basicsr, gfpgan
  Running setup.py install for numba: started
  Running setup.py install for numba: finished with status 'error'

stderr:   error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [767 lines of output]
      TBB not found
      Using OpenMP from: /Users/stammer/miniconda3/envs/sadtalker

[...]

running build_ext
      building 'numba._dynfunc' extension
      Warning: Can't read registry to find the necessary compiler setting
      Make sure that Python modules winreg, win32api or win32con are installed.
      C compiler: /opt/homebrew/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/stammer/miniconda3/envs/sadtalker/include -arch arm64 -I/Users/stammer/miniconda3/envs/sadtalker/include -arch arm64 -I/opt/homebrew/opt/llvm/include
      
      creating build/temp.macosx-11.1-arm64-3.8
      creating build/temp.macosx-11.1-arm64-3.8/numba
      compile options: '-I/Users/stammer/sadtalker/SadTalker/venv/include -I/Users/stammer/miniconda3/envs/sadtalker/include/python3.8 -c'
      clang: numba/_dynfuncmod.c
      In file included from numba/_dynfuncmod.c:1:
      In file included from numba/_dynfunc.c:6:
      In file included from numba/_pymodule.h:6:
      /Users/stammer/miniconda3/envs/sadtalker/include/python3.8/Python.h:25:10: fatal error: 'stdio.h' file not found
         25 | #include <stdio.h>
            |          ^~~~~~~~~
      1 error generated.
      error: Command "/opt/homebrew/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/stammer/miniconda3/envs/sadtalker/include -arch arm64 -I/Users/stammer/miniconda3/envs/sadtalker/include -arch arm64 -I/opt/homebrew/opt/llvm/include -I/Users/stammer/sadtalker/SadTalker/venv/include -I/Users/stammer/miniconda3/envs/sadtalker/include/python3.8 -c numba/_dynfuncmod.c -o build/temp.macosx-11.1-arm64-3.8/numba/_dynfuncmod.o" failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
  error: subprocess-exited-with-error
  
  × Running setup.py install for numba did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      TBB not found
      Using OpenMP from: /Users/stammer/miniconda3/envs/sadtalker
      running install
      running build
      got version from file /private/var/folders/s8/rhpvnzz10gz2_58s0s7zz4t00000gn/T/pip-install-mk6k8ci8/numba_44624a27b04746b280fa44c3dfee6f38/numba/_version.py {'version': '0.55.1', 'full': '76720bf88350c70b99ab3d4272d01bd9f14eeace'}
      running build_py
      running build_ext
      building 'numba._dynfunc' extension
      Warning: Can't read registry to find the necessary compiler setting
      Make sure that Python modules winreg, win32api or win32con are installed.
      C compiler: /opt/homebrew/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/stammer/miniconda3/envs/sadtalker/include -arch arm64 -I/Users/stammer/miniconda3/envs/sadtalker/include -arch arm64 -I/opt/homebrew/opt/llvm/include
      
      creating build/temp.macosx-11.1-arm64-3.8
      creating build/temp.macosx-11.1-arm64-3.8/numba
      compile options: '-I/Users/stammer/sadtalker/SadTalker/venv/include -I/Users/stammer/miniconda3/envs/sadtalker/include/python3.8 -c'
      clang: numba/_dynfuncmod.c
      In file included from numba/_dynfuncmod.c:1:
      In file included from numba/_dynfunc.c:6:
      In file included from numba/_pymodule.h:6:
      /Users/stammer/miniconda3/envs/sadtalker/include/python3.8/Python.h:25:10: fatal error: 'stdio.h' file not found
         25 | #include <stdio.h>
            |          ^~~~~~~~~
      1 error generated.
      error: Command "/opt/homebrew/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/stammer/miniconda3/envs/sadtalker/include -arch arm64 -I/Users/stammer/miniconda3/envs/sadtalker/include -arch arm64 -I/opt/homebrew/opt/llvm/include -I/Users/stammer/sadtalker/SadTalker/venv/include -I/Users/stammer/miniconda3/envs/sadtalker/include/python3.8 -c numba/_dynfuncmod.c -o build/temp.macosx-11.1-arm64-3.8/numba/_dynfuncmod.o" failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> numba

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip

[End error]

As stated above I did ensure I am running Python 3.8 and latest version of pip is installed (23.3.2) even tho it keeps bringing up 23.0.1 for some reason.

Any help?

**Comment by xieyezi** [comment]
is there any solution?
