### ISSUE TITLE
FFmpeg cannot edit existing files in-place

### ISSUE THREAD

**Issue by MODOMison** [Winfredy/SadTalker#768]
Output results\9d358038-9b78-457c-8698-35044f5456e6\00003-3404085431##audio_full.mp4 same as Input #0 - exiting
FFmpeg cannot edit existing files in-place.
Error opening output file results\9d358038-9b78-457c-8698-35044f5456e6\00003-3404085431##audio_full.mp4.
Error opening output files: Invalid argument
Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\stable-diffusion-webui-master\extensions\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\Owner\Desktop\stable-diffusion-webui-master\extensions\SadTalker\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Owner\Desktop\stable-diffusion-webui-master\extensions\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Owner\Desktop\stable-diffusion-webui-master\extensions\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1455, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Owner\Desktop\stable-diffusion-webui-master\extensions\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 226, in postprocess
    processed_files = (self._format_video(y), None)
  File "C:\Users\Owner\Desktop\stable-diffusion-webui-master\extensions\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 295, in _format_video
    ff.run()
  File "C:\Users\Owner\Desktop\stable-diffusion-webui-master\extensions\SadTalker\venv\lib\site-packages\ffmpy.py", line 113, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -y -i results\9d358038-9b78-457c-8698-35044f5456e6\00003-3404085431##audio_full.mp4 results\9d358038-9b78-457c-8698-35044f5456e6\00003-3404085431##audio_full.mp4` exited with status 4294967274

STDOUT:

STDERR:

**Comment by Atlantic8** [comment]
same problem

**Comment by viccP** [comment]
When ffmpeg is performing file conversion, the input and output are the same, leading to this error. It may be necessary to modify the source code to address this issue.
![image](https://github.com/OpenTalker/SadTalker/assets/11806067/5a201dd2-26de-43c4-a759-c7bf33de9457)

#734's solution works

**Comment by XieHui-001** [comment]
same problem

**Comment by btwiamamin** [comment]
Same Problem

**Comment by XieHui-001** [comment]
Same Problem

**Comment by skp225** [comment]
same issue which file would we need to edit?

**Comment by skp225** [comment]
> When ffmpeg is performing file conversion, the input and output are the same, leading to this error. It may be necessary to modify the source code to address this issue. ![image](https://private-user-images.githubusercontent.com/11806067/295383395-5a201dd2-26de-43c4-a759-c7bf33de9457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MDcyMjYsIm5iZiI6MTcwNzUwNjkyNiwicGF0aCI6Ii8xMTgwNjA2Ny8yOTUzODMzOTUtNWEyMDFkZDItMjZkZS00M2M0LWE3NTktYzdiZjMzZGU5NDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE5Mjg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NmM4MTAxZmJmMGExZDlhMmUzYmE0Zjc5ZjQ4OGU3OTkwNzAwYjYxNmU0YTQxYzU1ZDA0M2JhOTNiOTc2YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YUYujOHTJvKIvddIXukpX3szNozu3zjdYM7Bz4JEPZc)
> 
> #734's solution works

which solution? could you repost link

**Comment by MiaoR1Zibing** [comment]
Referring to # 743, I modified the code according to it and it works!
[https://github.com/OpenTalker/SadTalker/discussions/743](url)
[test_audio2coeff.zip](https://github.com/OpenTalker/SadTalker/files/14374306/test_audio2coeff.zip)

**Comment by MiaoR1Zibing** [comment]
May it's not #734 but #743.

**Comment by Globalteamspeak** [comment]
I solved this by replacing gradio with gradio==4.1.1 in requirements.txt

**Comment by newbieGameDev** [comment]
I have the same problem and the suggested solutions didn't work for me.

**Comment by kulame** [comment]
same problem.

**Comment by akbulutdora** [comment]
same problem

**Comment by logobrother** [comment]
我通过在requirements.txt中用gradio==4.1.1替换gradio解决了这个问题，这个有效，我解决了，谢谢

**Comment by bitsentinel-cell** [comment]
> I solved this by replacing gradio with gradio==4.1.1 in requirements.txt

how did you figure this out?

**Comment by haiyangyiba** [comment]
> 我通过在requirements.txt中用gradio==4.1.1替换gradio解决了这个问题，这个有效，我解决了，谢谢

厉害了，按着这个来也确实生效了。
请问大佬这是怎么知道的呢？

**Comment by Kira-19820214** [comment]
> I solved this by replacing gradio with gradio==4.1.1 in requirements.txt

did it ！ tks

**Comment by gongsikai1** [comment]
same problem
