### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Dartvauder** [Winfredy/SadTalker#770]
When I try to run SadTalker in automatic1111, i have this problem:

Traceback (most recent call last):
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\system\python\lib\site-packages\gradio\processing_utils.py", line 145, in audio_from_file
    audio = AudioSegment.from_file(filename)
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\system\python\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\system\python\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] Не удается найти указанный файл

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\system\python\lib\site-packages\gradio\blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\system\python\lib\site-packages\gradio\blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\system\python\lib\site-packages\gradio\components\audio.py", line 220, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\system\python\lib\site-packages\gradio\processing_utils.py", line 155, in audio_from_file
    raise RuntimeError(msg) from e
RuntimeError: Cannot load audio from file: `ffprobe` not found. Please install `ffmpeg` in your system to use non-WAV audio file formats and make sure `ffprobe` is in your PATH.

When I try to run SadTalker in standalone app, i have this problem:

venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\extensions\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\extensions\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\extensions\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.

I did absolutely everything according to different instructions. And none of them work. Nothing works. What should I do?

My PC: Windows 11, python 3.10.6, RTX 2060 SUPER 8GB, 32RAM, FFmpeg last version with PATH enviroment

**Comment by ZeusLT** [comment]
since no one is responding to these:

> for `AttributeError: 'Row' object has no attribute 'style'

update requirements.txt and change `gradio `to `gradio==3.41.2` then run the webui.bat again

> RuntimeError: Cannot load audio from file: ffprobe not found. Please install ffmpeg in your system to use non-WAV audio file formats and make sure ffprobe is in your PATH.

download ffmpeg binaries https://ffmpeg.org/download.html (I just go for ffmpeg-git-full.7z) you will need the 3 files "ffprobe.exe" "ffplay.exe" "ffmpeg.exe", move them to a permanent folder somewhere and add that folder to your enviromental variable called PATH

![image](https://github.com/OpenTalker/SadTalker/assets/22300013/e203baa9-1b3a-4adb-90d1-0152db8d2db7)
