### ISSUE TITLE
SystemError: no locals when loading 'str'

### ISSUE THREAD

**Issue by aprohuang** [Winfredy/SadTalker#789]
如何解决

![1705459740356](https://github.com/OpenTalker/SadTalker/assets/93961573/ba5a95e6-502d-4cab-a7eb-b5dcebbfa756)

**Comment by CodeCricut** [comment]
I fixed this by pinning the gradio package version to 3.41.2 in requirements.txt and rerunning webui.bat. I think the cause may be related to this: https://github.com/gradio-app/gradio/issues/6904

Modify the gradio line in requirements.txt:
```
gradio==3.41.2
```

Result:
```
numpy==1.23.4
face_alignment==1.3.5
imageio==2.19.3
imageio-ffmpeg==0.4.7
librosa==0.9.2 # 
numba
resampy==0.3.1
pydub==0.25.1 
scipy==1.10.1
kornia==0.6.8
tqdm
yacs==0.1.8
pyyaml  
joblib==1.1.0
scikit-image==0.19.3
basicsr==1.4.2
facexlib==0.3.0
gradio==3.41.2
gfpgan
av
safetensors
```

**Comment by dje3392** [comment]
I've tried this but I still get the same error

**Comment by dje3392** [comment]
```venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "Launcher.py", line 204, in <module>
    start()
  File "Launcher.py", line 197, in start
    from app_sadtalker import sadtalker_demo
  File "C:\Users\dedwa\Documents\dev\SadTalker\app_sadtalker.py", line 2, in <module>
    import gradio as gr
  File "C:\Users\dedwa\Documents\dev\SadTalker\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\dedwa\Documents\dev\SadTalker\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\dedwa\Documents\dev\SadTalker\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "C:\Users\dedwa\Documents\dev\SadTalker\venv\lib\site-packages\gradio\components\base.py", line 29, in <module>
    from gradio.blocks import Block, BlockContext
  File "C:\Users\dedwa\Documents\dev\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 28, in <module>
    from gradio import (
  File "C:\Users\dedwa\Documents\dev\SadTalker\venv\lib\site-packages\gradio\networking.py", line 18, in <module>
    from gradio.routes import App
  File "C:\Users\dedwa\Documents\dev\SadTalker\venv\lib\site-packages\gradio\routes.py", line 97, in <module>
    templates = Jinja2Templates(directory=STATIC_TEMPLATE_LIB)
  File "C:\Users\dedwa\Documents\dev\SadTalker\venv\lib\site-packages\starlette\templating.py", line 110, in __init__
    self._setup_env_defaults(self.env)
  File "C:\Users\dedwa\Documents\dev\SadTalker\venv\lib\site-packages\starlette\templating.py", line 126, in _setup_env_defaults
    context: typing.Dict[str, typing.Any],
SystemError: no locals when loading 'str'

Launch unsuccessful. Exiting.
Press any key to continue . . .

**Comment by gitrockyyin** [comment]
(lc) [root@localhost langchain-ChatGLM]# python webui.py
Traceback (most recent call last):
  File "webui.py", line 1, in <module>
    import gradio as gr
  File "/root/anaconda3/envs/lc/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/root/anaconda3/envs/lc/lib/python3.8/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/root/anaconda3/envs/lc/lib/python3.8/site-packages/gradio/components/annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "/root/anaconda3/envs/lc/lib/python3.8/site-packages/gradio/components/base.py", line 29, in <module>
    from gradio.blocks import Block, BlockContext
  File "/root/anaconda3/envs/lc/lib/python3.8/site-packages/gradio/blocks.py", line 28, in <module>
    from gradio import (
  File "/root/anaconda3/envs/lc/lib/python3.8/site-packages/gradio/networking.py", line 18, in <module>
    from gradio.routes import App
  File "/root/anaconda3/envs/lc/lib/python3.8/site-packages/gradio/routes.py", line 97, in <module>
    templates = Jinja2Templates(directory=STATIC_TEMPLATE_LIB)
  File "/root/anaconda3/envs/lc/lib/python3.8/site-packages/starlette/templating.py", line 110, in __init__
    self._setup_env_defaults(self.env)
  File "/root/anaconda3/envs/lc/lib/python3.8/site-packages/starlette/templating.py", line 126, in _setup_env_defaults
    context: typing.Dict[str, typing.Any],
SystemError: no locals when loading 'str'
