### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by jiuang** [Winfredy/SadTalker#793]
Hi~
I got an exception when I selected the "**full**" preprocess.
It works for "crop".
![image](https://github.com/OpenTalker/SadTalker/assets/34175244/6344d40f-2b60-4786-a625-7e24d975a084)

ubunt 22.04.3 LTS
SadTalker latest
python 3.9.18
conda 23.7.4
torch    2.1.2+cu121
torchvision    0.16.2+cu121
torchaudio    2.1.2+cu121

log: 

> (py9) root@devops182:/opt/szr/SadTalker# ./webui.sh 
> 
> ################################################################
Install script for SadTalker + Web UI
Tested on Debian 11 (Bullseye)
################################################################
> 
> ################################################################
Running on root user
################################################################
> 
> ################################################################
Repo already cloned, using it as install directory
################################################################
> 
> ################################################################
Create and activate python venv
################################################################
> 
> ################################################################
Launching launcher.py...
> ################################################################
Python 3.9.18 (main, Sep 11 2023, 13:41:44) 
[GCC 11.2.0]
Commit hash: cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Running on local URL:  http://0.0.0.0:7860
> 
> To create a public link, set `share=True` in `launch()`.
using safetensor as default
{'checkpoint': 'checkpoints/SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config/auido2pose.yaml', 'audio2exp_yaml_path': 'src/config/auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'checkpoints/mapping_00109-model.pth.tar', 'facerender_yaml': 'src/config/facerender_still.yaml'}
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py9/lib/python3.9/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/anaconda3/envs/py9/lib/python3.9/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/anaconda3/envs/py9/lib/python3.9/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/opt/anaconda3/envs/py9/lib/python3.9/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/anaconda3/envs/py9/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/opt/anaconda3/envs/py9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/opt/anaconda3/envs/py9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/opt/anaconda3/envs/py9/lib/python3.9/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/opt/szr/SadTalker/src/gradio_demo.py", line 51, in test
    self.animate_from_coeff = AnimateFromCoeff(self.sadtalker_paths, self.device)
  File "/opt/szr/SadTalker/src/facerender/animate.py", line 70, in __init__
    self.load_cpk_mapping(sadtalker_path['mappingnet_checkpoint'], mapping=mapping)
  File "/opt/szr/SadTalker/src/facerender/animate.py", line 145, in load_cpk_mapping
    checkpoint = torch.load(checkpoint_path,  map_location=torch.device(device))
  File "/opt/anaconda3/envs/py9/lib/python3.9/site-packages/torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/opt/anaconda3/envs/py9/lib/python3.9/site-packages/torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Some attempts have been made:
`1. rm -rf ~/.cache/huggingface/`
`2. uninstall torch & install again`
`3. read some blogs..`

Thanks for help.

**Comment by jiuang** [comment]
Model 'mapping_00109-model.pth.tar' was not completed, downloaded again and worked for 'full'.
![image](https://github.com/OpenTalker/SadTalker/assets/34175244/780c0fb0-6ef1-4034-986b-4cb95fed4b9c)
