### ISSUE TITLE
Error when outputting file

### ISSUE THREAD

**Issue by XieHui-001** [Winfredy/SadTalker#796]
using safetensor as default
{'checkpoint': 'checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'checkpoints\\mapping_00109-model.pth.tar', 'facerender_yaml': 'src/config\\facerender_still.yaml'}
C:\Users\1\AppData\Local\Temp\gradio\5343030db1e27ad624d3d8fcdb9ed2abb1fbfd79\face1.png
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.67it/s]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.98it/s]
mel:: 100%|█████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 44630.92it/s]
audio2exp:: 100%|███████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 291.10it/s]
Face Renderer:: 100%|██████████████████████████████████████████████████████████████████| 45/45 [00:30<00:00,  1.45it/s]
The generated video is named ./results/330599e6-153e-4105-9857-795cfef071c4/face1##2024-01-22-163425_180062.mp4
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
seamlessClone:: 100%|██████████████████████████████████████████████████████████████████| 89/89 [00:03<00:00, 29.54it/s]
The generated video is named ./results/330599e6-153e-4105-9857-795cfef071c4/face1##2024-01-22-163425_180062_full.mp4
The generated video is named face1##2024-01-22-163425_180062 in ./results/330599e6-153e-4105-9857-795cfef071c4
ffmpeg version 2024-01-07-git-90bef6390f-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 36.101 / 58. 36.101
  libavcodec     60. 37.100 / 60. 37.100
  libavformat    60. 20.100 / 60. 20.100
  libavdevice    60.  4.100 / 60.  4.100
  libavfilter     9. 17.100 /  9. 17.100
  libswscale      7.  6.100 /  7.  6.100
  libswresample   4. 13.100 /  4. 13.100
  libpostproc    57.  4.100 / 57.  4.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'results\330599e6-153e-4105-9857-795cfef071c4\face1##2024-01-22-163425_180062_full.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.20.100
  Duration: 00:00:03.58, start: 0.000000, bitrate: 272 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 488x848 [SAR 1:1 DAR 61:106], 195 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
        encoder         : Lavc60.37.100 libx264
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 68 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
Output results\330599e6-153e-4105-9857-795cfef071c4\face1##2024-01-22-163425_180062_full.mp4 same as Input #0 - exiting
FFmpeg cannot edit existing files in-place.
Error opening output file results\330599e6-153e-4105-9857-795cfef071c4\face1##2024-01-22-163425_180062_full.mp4.
Error opening output files: Invalid argument
Traceback (most recent call last):
  File "G:\SadTalker\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "G:\SadTalker\SadTalker\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "G:\SadTalker\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "G:\SadTalker\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1455, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "G:\SadTalker\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 226, in postprocess
    processed_files = (self._format_video(y), None)
  File "G:\SadTalker\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 295, in _format_video
    ff.run()
  File "G:\SadTalker\SadTalker\venv\lib\site-packages\ffmpy.py", line 113, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -y -i results\330599e6-153e-4105-9857-795cfef071c4\face1##2024-01-22-163425_180062_full.mp4 results\330599e6-153e-4105-9857-795cfef071c4\face1##2024-01-22-163425_180062_full.mp4` exited with status 4294967274

STDOUT:

STDERR:

**Comment by Markessw** [comment]
Just tried it and I'm getting the same thing...

**Comment by ericz024** [comment]
same problem here. After updating, it doesn't show the tab in Stable Diffusion and the same thing happens

**Comment by ericz024** [comment]
Find file " requirements.txt" i. Change "gradio" into "gradio==4.1.1"

**Comment by Markessw** [comment]
> Find file " requirements.txt" i. Change "gradio" into "gradio==4.1.1"

It still did not work, the tab still is not there in A1111. However I also had a stand-alone version that I couldn't get to work either, but when I use this code in that one it started working, so THANK YOU VERY MUCH. It does great on small files but I have one that 31 seconds long, and when it get to the last part, I get an out of memory error. But thanks to you I'm some-what in business. Thank you for sharing your knowledge.

**Comment by ericz024** [comment]
> > Find file " requirements.txt" i. Change "gradio" into "gradio==4.1.1"
> 
> It still did not work, the tab still is not there in A1111. However I also had a stand-alone version that I couldn't get to work either, but when I use this code in that one it started working, so THANK YOU VERY MUCH. It does great on small files but I have one that 31 seconds long, and when it get to the last part, I get an out of memory error. But thanks to you I'm some-what in business. Thank you for sharing your knowledge.

I'm the same, if you want it to show the tab  you have to roll back to the previous version in stable diffusion or wait for them to update to fix the error
