### ISSUE TITLE
Error WebUi

### ISSUE THREAD

**Issue by EzStory** [Winfredy/SadTalker#798]
Launching SadTalker Web UI
Traceback (most recent call last):
  File "D:\SadTalker\2\Launcher.py", line 204, in <module>
    start()
  File "D:\SadTalker\2\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "D:\SadTalker\2\app.py", line 37, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.
Drücken Sie eine beliebige Taste . . .

_Originally posted by @EzStory in https://github.com/OpenTalker/SadTalker/discussions/797_

**Comment by yitaoge** [comment]
同样的问题，你解决了没有

**Comment by nhattam1231995** [comment]
tôi cũng bị trường hợp tương tự

**Comment by saqibmaqbool786** [comment]
I have the same problem. Have anyone solved this issue ???

**Comment by Zdeto** [comment]
Solved with:
pip install gradio==3.41.2

**Comment by saqibmaqbool786** [comment]
> Solved with: pip install gradio==3.41.2

i installed gradio using same command but its still giving me same error

Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "C:\Users\saqib\Downloads\SadTalker-main\Launcher.py", line 204, in <module>
    start()
  File "C:\Users\saqib\Downloads\SadTalker-main\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\Users\saqib\Downloads\SadTalker-main\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.

**Comment by hongyu2024** [comment]
> Solved with: pip install gradio==3.41.2

Thank you!!

**Comment by decimecano** [comment]
> Solved with: pip install gradio==3.41.2

Do I have to install it in the same direction ?(./SadTalker-main)?

**Comment by decimecano** [comment]
> > Solved with: pip install gradio==3.41.2
> 
> i installed gradio using same command but its still giving me same error
> 
> Installing requirements for SadTalker WebUI (may take longer time in first time) Launching SadTalker Web UI Traceback (most recent call last): File "C:\Users\saqib\Downloads\SadTalker-main\Launcher.py", line 204, in start() File "C:\Users\saqib\Downloads\SadTalker-main\Launcher.py", line 198, in start demo = sadtalker_demo() File "C:\Users\saqib\Downloads\SadTalker-main\app_sadtalker.py", line 35, in sadtalker_demo with gr.Row().style(equal_height=False): AttributeError: 'Row' object has no attribute 'style'
> 
> Launch unsuccessful. Exiting.

did you fix the problem? how?

**Comment by jmr022024** [comment]
> > Solved with: pip install gradio==3.41.2
> 
> Thank you!!

Please explain the steps to follow and in which folder Solved

**Comment by jharch** [comment]
> Solved with: pip install gradio==3.41.2

didnt work

**Comment by MrGotoexe** [comment]
> > Solved with: pip install gradio==3.41.2
> 
> didnt work

same here

**Comment by bigdataLyt** [comment]
> Solved with: pip install gradio==3.41.2

Yeah!!

**Comment by bigdataLyt** [comment]
It could be a version problem of gradio
