### ISSUE TITLE
Error on Automatic1111 + Trojan Warning

### ISSUE THREAD

**Issue by ameen-roayan** [Winfredy/SadTalker#80]
I get this error after hitting generate 

E:\Automatic1111\stable-diffusion-webui\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Automatic1111\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "E:\Automatic1111\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 64, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "E:\Automatic1111\stable-diffusion-webui/extensions/SadTalker\src\utils\preprocess.py", line 45, in __init__
    self.croper = Croper(path_of_lm_croper)
  File "E:\Automatic1111\stable-diffusion-webui/extensions/SadTalker\src\utils\croper.py", line 38, in __init__
    self.predictor = dlib.shape_predictor(path_of_lm)
RuntimeError: Unable to open E:\Automatic1111\stable-diffusion-webui\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat

All files present in checkpoints folder & webui folder added the destination of checkpoints 

![image](https://user-images.githubusercontent.com/92278134/230773325-58d7f36a-ba9d-4d4f-bead-ea919dd51dd2.png)
![image](https://user-images.githubusercontent.com/92278134/230773350-abb3f3c4-1763-4c7b-ae12-c56aa5b988e9.png)

**Comment by vinthony** [comment]
it seems there is a small * at the end of each file, try to rename all the files without it.

**Comment by ameen-roayan** [comment]
thanks for that ! instant fix. 
I thought this was some python thing i did not quite understand so kept it. 

but this is how they got downloaded for future reference

**Comment by vinthony** [comment]
we will fixed the problem of windows autodownload.

**Comment by ameen-roayan** [comment]
it appears i will also need this in order to run it --disable-safe-unpickle commandline argument.

**Comment by ameen-roayan** [comment]
![image](https://user-images.githubusercontent.com/92278134/230779316-b03a230c-8118-45fd-9f66-93390894c045.png)
Multiple Trojan warnings, also still getting file not found error 

Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Automatic1111\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\BFM_Fitting\\similarity_Lm3D_all.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Automatic1111\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "E:\Automatic1111\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 64, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "E:\Automatic1111\stable-diffusion-webui/extensions/SadTalker\src\utils\preprocess.py", line 51, in __init__
    self.lm3d_std = load_lm3d(dir_of_BFM_fitting)
  File "E:\Automatic1111\stable-diffusion-webui/extensions/SadTalker\src\face3d\util\load_mats.py", line 107, in load_lm3d
    Lm3D = loadmat(osp.join(bfm_folder, 'similarity_Lm3D_all.mat'))
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 224, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "C:\Users\vx_10\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Automatic1111\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\BFM_Fitting\\similarity_Lm3D_all.mat'

**Comment by vinthony** [comment]
similar to #75, will update .safetensor if possible.

**Comment by bbecausereasonss** [comment]
Hmm my install just stays at 0% now... with the huggingface site not sure why.

face-alignment False
Installing requirements for SadTalker
imageio True
imageio-ffmpeg False
Installing requirements for SadTalker
librosa True
pydub True
scipy True
tqdm True
yacs True
pyyaml False
Installing requirements for SadTalker
dlib True
gfpgan True
Fetching 22 files:   0%|                                                                         | 0/22 [00:00<?, ?it/s]

**Comment by vinthony** [comment]
> Hmm my install just stays at 0% now... with the huggingface site not sure why.
> 
> face-alignment False Installing requirements for SadTalker imageio True imageio-ffmpeg False Installing requirements for SadTalker librosa True pydub True scipy True tqdm True yacs True pyyaml False Installing requirements for SadTalker dlib True gfpgan True Fetching 22 files: 0%| | 0/22 [00:00<?, ?it/s]

it seems the huggingface is slow for you, try to manually download the checkpoints and set the environment, you can refer here:  https://github.com/Winfredy/SadTalker/issues/78#issuecomment-1501074375

**Comment by james-s-tayler** [comment]
Definitely need to update to safetensors as it's really not a wise idea to disable safety / security features, especially in an ecosystem where anyone can create an extension and many people are willing to install it without verifying what's even in it.

**Comment by vinthony** [comment]
> Definitely need to update to safetensors as it's really not a wise idea to disable safety / security features, especially in an ecosystem where anyone can create an extension and many people are willing to install it without verifying what's even in it.

This is the next big thing we are going to fix.

**Comment by james-s-tayler** [comment]
Awesome! This project is so next level.
