### ISSUE TITLE
ERROR: Could not build wheels for scikit-image

### ISSUE THREAD

**Issue by mubiesam** [Winfredy/SadTalker#803]
執行 pip install -r requirements.txt 時出現...
 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-image
Failed to build scikit-image
ERROR: Could not build wheels for scikit-image, which is required to install pyproject.toml-based projects

更新... C/C++ 編譯器 Microsoft Visual C++ 2015-2022 Redistributable 14.38.33130 Python 3.11.5 pip 23.2.1
嘗試... conda install scikit-image 安裝成功，但再次執行 pip install -r requirements.txt 時，還是出現同樣ERROR: Failed building wheel for scikit-image

請問該如何處理? 謝謝!

**Comment by feathered-arch** [comment]
Revert to Python 3.10.10

**Comment by mubiesam** [comment]
Thank you very much for the quick answer, Revert to Python 3.10.10 did pass for pip install -r requirements.txt, but another issue came up, so I decided to try Windows way as this video https://www.youtube.com/watch?v=P2JM45Kq4iM&list=WL&index=7&t=14s

After installing Python at this path C:\Users\sam77\AppData\Local\Programs\Python\Python310
C:\Users\sam77\Sadtalker then webui.bat 
got error...
Launching SadTalker Web UI
Traceback (most recent call last):
  File "C:\Users\sam77\Sadtalker\Launcher.py", line 204, in <module> start()
  File "C:\Users\sam77\Sadtalker\Launcher.py", line 198, in start demo = sadtalker_demo()
  File "C:\Users\sam77\Sadtalker\app_sadtalker.py", line 35, in sadtalker_demo with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Looking into Launcher.py 
INCOMPATIBLE PYTHON VERSION
This program is tested with 3.10.6 Python, but you have {major}.{minor}.{micro}.
If you encounter an error with "RuntimeError: Couldn't install torch." message, or any other error regarding unsuccessful package (library) installation, please downgrade (or upgrade) to the latest version of 3.10 Python and delete current Python and "venv" folder in WebUI's directory. You can download 3.10 Python from here: https://www.python.org/downloads/release/python-3109/ {"Alternatively, use a binary release of WebUI:  https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases" if is_windows else ""} Use --skip-python-version-check to suppress this warning. """)

Tried to install stable-diffusion-webui C:\Users\sam77\Sadtalker\stable-diffusion-webui-1.7.0 but still got the same error...no attribute 'style'

Any suggestion...

**Comment by FMaz008** [comment]
Gradio deprecated the style method (and a few other things), but OpenTalker/SadTalker has not maintained this repository in a little while, PR are pendings which could fix the issue. I recently pushed one that address your problem:
https://github.com/OpenTalker/SadTalker/pull/857

Hopefully this help.
