### ISSUE TITLE
大佬，BrokenPipeError: [Errno 32] Broken pipe这个问题如何解决

### ISSUE THREAD

**Issue by prog-ape** [Winfredy/SadTalker#809]
ffmpeg version 4.4.2-0ubuntu0.22.04.1

命令：
python inference.py --driven_audio /home/sad/img-talker/18d6f840341/0a55b7c60d454ad280af6315f63448fb.mp3 --source_image /home/sad/img-talker/18d6f840341/18d6f840341.jpg --result_dir /home/sad/img-talker/18d6f840341 --still --preprocess full --enhancer gfpgan

去掉--enhancer gfpgan就可以正常运行，加上的话就经常出现以下异常

Face Renderer:: 100%|������������������������������| 271/271 [02:00<00:00,  2.25it/s]
Traceback (most recent call last):
  File "/home/sad/anaconda3/envs/sadtalker/lib/python3.10/site-packages/imageio_ffmpeg/_io.py", line 631, in write_frames
    p.stdin.write(bb)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sad/SadTalker/inference.py", line 144, in <module>
    main(args)
  File "/home/sad/SadTalker/inference.py", line 87, in main
    result = animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "/home/sad/SadTalker/src/facerender/animate.py", line 205, in generate
    imageio.mimsave(path, result,  fps=float(25))
  File "/home/sad/anaconda3/envs/sadtalker/lib/python3.10/site-packages/imageio/v2.py", line 331, in mimwrite
    return file.write(ims, **kwargs)
  File "/home/sad/anaconda3/envs/sadtalker/lib/python3.10/site-packages/imageio/core/legacy_plugin_wrapper.py", line 216, in write
    writer.append_data(ndimage)
  File "/home/sad/anaconda3/envs/sadtalker/lib/python3.10/site-packages/imageio/core/format.py", line 589, in append_data
    return self._append_data(im, total_meta)
  File "/home/sad/anaconda3/envs/sadtalker/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 606, in _append_data
    self._write_gen.send(im)
  File "/home/sad/anaconda3/envs/sadtalker/lib/python3.10/site-packages/imageio_ffmpeg/_io.py", line 638, in write_frames
    raise IOError(msg)
OSError: [Errno 32] Broken pipe

FFMPEG COMMAND:
/home/sad/ffmpeg/ffmpeg-6.0.1-amd64-static//ffmpeg -y -f rawvideo -vcodec rawvideo -s 512x512 -pix_fmt rgb24 -r 25.00 -i - -an -vcodec libx264 -pix_fmt yuv420p -v warning /home/sad/img-talker/18d6f840341/2024_02_03_15.09.02/temp_18d6f840341##0a55b7c60d454ad280af6315f63448fb.mp4

FFMPEG STDERR OUTPUT:

**Comment by Hanshere1122** [comment]
我也是这个问题，解决了没~
