### ISSUE TITLE
求助，这个报错怎么处理啊

### ISSUE THREAD

**Issue by caaaan0415** [Winfredy/SadTalker#816]
WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!
3DMM Extraction for source image
landmark Det:: 100%|██████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.36s/it]
3DMM Extraction In Video:: 100%|██████████████████████████████████████████| 1/1 [00:00<00:00, 15.09it/s]
mel:: 100%|████████████████████████████████████████████████████████| 445/445 [00:00<00:00, 59974.46it/s]
audio2exp:: 100%|███████████████████████████████████████████████████████| 45/45 [00:00<00:00, 79.79it/s]
Face Renderer:: 100%|███████████████████████████████████████████████| 223/223 [1:09:00<00:00, 18.57s/it]
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (256, 257) to (256, 272) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
Traceback (most recent call last):
  File ".\inference.py", line 144, in <module>
    main(args)
  File ".\inference.py", line 87, in main
    result = animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "D:\git\SadTalker\src\facerender\animate.py", line 215, in generate
    sound = AudioSegment.from_file(audio_path)
  File "C:\Users\xxb\AppData\Local\Programs\Python\Python38\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\xxb\AppData\Local\Programs\Python\Python38\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\xxb\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\xxb\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by AIdafashi** [comment]
解决了吗？

**Comment by nitinmukesh** [comment]
> WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the 

Use 256 x 256 OR 512 x 512 dimension images
