### ISSUE TITLE
Not sure how to resolve this issue

### ISSUE THREAD

**Issue by nitinmukesh** [Winfredy/SadTalker#817]
Completred the installation on Windows. The tab appeared correctly.
When I provide the inputs and click on Generate it comes up with errors. Any suggestions

```
venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: --disable-safe-unpickle
2024-02-25 16:57:42.253330: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From C:\stable-diffusion-webui\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Style database not found: C:\stable-diffusion-webui\styles.csv
ControlNet preprocessor location: C:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-02-25 16:57:48,554 - ControlNet - INFO - ControlNet v1.1.440
2024-02-25 16:57:48,680 - ControlNet - INFO - ControlNet v1.1.440
Loading weights [624bf05c85] from C:\stable-diffusion-webui\models\Stable-diffusion\deliberatedMixed_v10.safetensors
2024-02-25 16:57:48,947 - ControlNet - INFO - ControlNet UI callback registered.
"
            SadTalker will not support download all the files from hugging face, which will take a long time.

            please manually set the SADTALKER_CHECKPOINTS in `webui_user.bat`(windows) or `webui_user.sh`(linux)

Creating model from config: C:\stable-diffusion-webui\configs\v1-inference.yaml
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 21.4s (prepare environment: 7.4s, import torch: 3.7s, import gradio: 0.8s, setup paths: 5.9s, other imports: 0.4s, load scripts: 0.9s, create ui: 1.5s, gradio launch: 0.5s).
Applying attention optimization: Doggettx... done.
Model loaded in 4.5s (load weights from disk: 0.9s, create model: 0.3s, apply weights to model: 3.1s, calculate empty prompt: 0.1s).
WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!
{'wav2lip_checkpoint': 'C:\\stable-diffusion-webui/extensions/SadTalker/checkpoints/wav2lip.pth', 'audio2pose_checkpoint': 'C:\\stable-diffusion-webui/extensions/SadTalker/checkpoints/auido2pose_00140-model.pth', 'audio2exp_checkpoint': 'C:\\stable-diffusion-webui/extensions/SadTalker/checkpoints/auido2exp_00300-model.pth', 'free_view_checkpoint': 'C:\\stable-diffusion-webui/extensions/SadTalker/checkpoints/facevid2vid_00189-model.pth.tar', 'path_of_net_recon_model': 'C:\\stable-diffusion-webui/extensions/SadTalker/checkpoints/epoch_20.pth', 'dir_of_BFM_fitting': 'C:\\stable-diffusion-webui/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'C:\\stable-diffusion-webui/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'C:\\stable-diffusion-webui/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': False, 'mappingnet_checkpoint': 'C:\\stable-diffusion-webui/extensions/SadTalker/checkpoints/mapping_00109-model.pth.tar', 'facerender_yaml': 'C:\\stable-diffusion-webui/extensions/SadTalker/src/config\\facerender_still.yaml'}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui/extensions/SadTalker\src\test_audio2coeff.py", line 48, in __init__
    load_cpk(sadtalker_path['audio2pose_checkpoint'], model=self.audio2pose_model, device=device)
  File "C:\stable-diffusion-webui/extensions/SadTalker\src\test_audio2coeff.py", line 17, in load_cpk
    checkpoint = torch.load(checkpoint_path, map_location=torch.device(device))
  File "C:\stable-diffusion-webui\modules\safe.py", line 108, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "C:\stable-diffusion-webui\modules\safe.py", line 156, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 49, in test
    self.audio_to_coeff = Audio2Coeff(self.sadtalker_paths, self.device)
  File "C:\stable-diffusion-webui/extensions/SadTalker\src\test_audio2coeff.py", line 50, in __init__
    raise Exception("Failed in loading audio2pose_checkpoint")
Exception: Failed in loading audio2pose_checkpoint
```

webui-user.bat

@echo off

```
set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--disable-safe-unpickle

call webui.bat
```

**Comment by nitinmukesh** [comment]
Since standalone is working don't need for Auto1111
