### ISSUE TITLE
Standalone installation on windows not working

### ISSUE THREAD

**Issue by nitinmukesh** [Winfredy/SadTalker#818]
Downloaded and Setup the application locally on Win 11.

Getting the following error and it fails to launch

```
venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "C:\stable_diffusion\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "C:\stable_diffusion\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\stable_diffusion\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.
Press any key to continue . . .
```

**Comment by nitinmukesh** [comment]
It's working now.

**Comment by hjcenry** [comment]
How did you work? I have the same problem

**Comment by decimecano** [comment]
I'm having the same issue. How did you fixed it?

**Comment by nitinmukesh** [comment]
> How did you work? I have the same problem



> I'm having the same issue. How did you fixed it?

Follow this guide
https://youtu.be/sqUQx1Dy1dg?si=T4dQaMkD3zj5wGGi

**Comment by anupamluv** [comment]
I am also looking for its solution.... the youtube link is private now... plz help

**Comment by nitinmukesh** [comment]
@anupamluv 

https://youtu.be/sqUQx1Dy1dg?si=T4dQaMkD3zj5wGGi
