### ISSUE TITLE
Traceback error and outdated model

### ISSUE THREAD

**Issue by OldNewDesign** [Winfredy/SadTalker#819]
WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!
{'wav2lip_checkpoint': '"E:\\Ai Creation Tools\\SD Forge UI\\extensions\\SadTalker\\checkpoints"\\wav2lip.pth', 'audio2pose_checkpoint': '"E:\\Ai Creation Tools\\SD Forge UI\\extensions\\SadTalker\\checkpoints"\\auido2pose_00140-model.pth', 'audio2exp_checkpoint': '"E:\\Ai Creation Tools\\SD Forge UI\\extensions\\SadTalker\\checkpoints"\\auido2exp_00300-model.pth', 'free_view_checkpoint': '"E:\\Ai Creation Tools\\SD Forge UI\\extensions\\SadTalker\\checkpoints"\\facevid2vid_00189-model.pth.tar', 'path_of_net_recon_model': '"E:\\Ai Creation Tools\\SD Forge UI\\extensions\\SadTalker\\checkpoints"\\epoch_20.pth', 'dir_of_BFM_fitting': 'E:\\Ai Creation Tools\\SD Forge UI/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'E:\\Ai Creation Tools\\SD Forge UI/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'E:\\Ai Creation Tools\\SD Forge UI/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': False, 'mappingnet_checkpoint': '"E:\\Ai Creation Tools\\SD Forge UI\\extensions\\SadTalker\\checkpoints"\\mapping_00229-model.pth.tar', 'facerender_yaml': 'E:\\Ai Creation Tools\\SD Forge UI/extensions/SadTalker/src/config\\facerender.yaml'}
Traceback (most recent call last):
  File "E:\Ai Creation Tools\SD Forge UI\modules_forge\patch_basic.py", line 17, in loader
    result = original_loader(*args, **kwargs)
  File "E:\Ai Creation Tools\SD Forge UI\venv\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\Ai Creation Tools\SD Forge UI\venv\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\Ai Creation Tools\SD Forge UI\venv\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
OSError: [Errno 22] Invalid argument: '"E:\\Ai Creation Tools\\SD Forge UI\\extensions\\SadTalker\\checkpoints"\\auido2pose_00140-model.pth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Ai Creation Tools\SD Forge UI\extensions\SadTalker\src\test_audio2coeff.py", line 48, in __init__
    load_cpk(sadtalker_path['audio2pose_checkpoint'], model=self.audio2pose_model, device=device)
  File "E:\Ai Creation Tools\SD Forge UI\extensions\SadTalker\src\test_audio2coeff.py", line 17, in load_cpk
    checkpoint = torch.load(checkpoint_path, map_location=torch.device(device))
  File "E:\Ai Creation Tools\SD Forge UI\modules_forge\patch_basic.py", line 33, in loader
    raise ValueError(exp)
ValueError: [Errno 22] Invalid argument: '"E:\\Ai Creation Tools\\SD Forge UI\\extensions\\SadTalker\\checkpoints"\\auido2pose_00140-model.pth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Ai Creation Tools\SD Forge UI\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Ai Creation Tools\SD Forge UI\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\Ai Creation Tools\SD Forge UI\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Ai Creation Tools\SD Forge UI\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Ai Creation Tools\SD Forge UI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Ai Creation Tools\SD Forge UI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Ai Creation Tools\SD Forge UI\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\Ai Creation Tools\SD Forge UI\extensions\SadTalker\src\gradio_demo.py", line 42, in test
    self.audio_to_coeff = Audio2Coeff(self.sadtalker_paths, self.device)
  File "E:\Ai Creation Tools\SD Forge UI\extensions\SadTalker\src\test_audio2coeff.py", line 50, in __init__
    raise Exception("Failed in loading audio2pose_checkpoint")
Exception: Failed in loading audio2pose_checkpoint

**Comment by kulame** [comment]
meet same issues.  any solution ?
