### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by xiangwangxingming** [Winfredy/SadTalker#829]
venv "venv\Scripts\Python.exe"
Python 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)]
Commit hash: cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "Launcher.py", line 204, in <module>
    start()
  File "Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\Users\3\sad talker\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.
请按任意键继续. . .

哪里的问题

**Comment by hongyu2024** [comment]
gradio 版本问题
换成 3.41.2
