### ISSUE TITLE
webui安装sadtalker出现的错误

### ISSUE THREAD

**Issue by 850977164** [Winfredy/SadTalker#835]
Python 3.10.6 (main, Oct 24 2022, 16:07:47) [GCC 11.2.0]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: -f --xformers --medvram --theme=dark --port=6006
Style database not found: /root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/styles.csv
content_dir --  interrogate
Loading weights [6ce0161689] from /root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Creating model from config: /root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/configs/v1-inference.yaml
face_alignment False
Installing requirements for SadTalker
Applying attention optimization: xformers... done.
Model loaded in 2.2s (load weights from disk: 0.3s, create model: 0.6s, apply weights to model: 0.7s, apply half(): 0.3s, calculate empty prompt: 0.2s).
*** Error executing callback ui_tabs_callback for /root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/extensions/SadTalker/scripts/extension-Copy1.py
    Traceback (most recent call last):
      File "/root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/modules/script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "/root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/extensions/SadTalker/scripts/extension-Copy1.py", line 163, in on_ui_tabs
        install()
      File "/root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/extensions/SadTalker/scripts/extension-Copy1.py", line 134, in install
        launch.run_pip("install "+ v, "requirements for SadTalker")
      File "/root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/modules/launch_utils.py", line 144, in run_pip
        return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
      File "/root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/modules/launch_utils.py", line 116, in run
        raise RuntimeError("\n".join(error_bits))
    RuntimeError: Couldn't install requirements for SadTalker.
    Command: "/root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/venv/bin/python3" -m pip install face-alignment==1.3.5 --prefer-binary
    Error code: 1
    stdout: Looking in indexes: http://mirrors.aliyun.com/pypi/simpleno-cache-dir = true, https://pypi.ngc.nvidia.com

    stderr: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.ngc.nvidia.com', port=443): Read timed out. (read timeout=15)")': /face-alignment/
    ERROR: Could not find a version that satisfies the requirement face-alignment==1.3.5 (from versions: none)
    ERROR: No matching distribution found for face-alignment==1.3.5
    WARNING: There was an error checking the latest version of pip.

---
face_alignment False
Installing requirements for SadTalker
*** Error executing callback ui_tabs_callback for /root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py
    Traceback (most recent call last):
      File "/root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/modules/script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "/root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 162, in on_ui_tabs
        install()
      File "/root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 134, in install
        launch.run_pip("install "+ v, "requirements for SadTalker")
      File "/root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/modules/launch_utils.py", line 144, in run_pip
        return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
      File "/root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/modules/launch_utils.py", line 116, in run
        raise RuntimeError("\n".join(error_bits))
    RuntimeError: Couldn't install requirements for SadTalker.
    Command: "/root/autodl-tmp/stable-diffusion-webui-master/stable-diffusion-webui/venv/bin/python3" -m pip install face-alignment==1.3.5 --prefer-binary
    Error code: 1
    stdout: Looking in indexes: http://mirrors.aliyun.com/pypi/simpleno-cache-dir = true, https://pypi.ngc.nvidia.com

    stderr: ERROR: Could not find a version that satisfies the requirement face-alignment==1.3.5 (from versions: none)
    ERROR: No matching distribution found for face-alignment==1.3.5
    WARNING: There was an error checking the latest version of pip.

---
Running on local URL:  http://127.0.0.1:6006

**Comment by 850977164** [comment]
我的pip已经更新版本，仍然有问题
(ldm) root@autodl-container-cada1195fa-9d4f3e24:~/.cache# pip --version
pip 24.0 from /root/miniconda3/envs/ldm/lib/python3.8/site-packages/pip (python 3.8)

**Comment by 850977164** [comment]
我通过pip install face-alignment==1.3.5，还是有这个错误
![1710641586163](https://github.com/OpenTalker/SadTalker/assets/39330916/3a48abb6-3fc3-4d02-8bca-8fadd50e1e67)
