### ISSUE TITLE
当添加了reference video ，就报错 “exceptions must derive from BaseException  ”

### ISSUE THREAD

**Issue by yslion** [Winfredy/SadTalker#838]
单跑图片没问题， 加上参考视频，就报错。 

![image](https://github.com/OpenTalker/SadTalker/assets/4454836/4232f553-bb29-41ca-a546-83d0bc402906)

using safetensor as default
{'checkpoint': 'checkpoints/SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config/auido2pose.yaml', 'audio2exp_yaml_path': 'src/config/auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'checkpoints/mapping_00109-model.pth.tar', 'facerender_yaml': 'src/config/facerender_still.yaml'}
/tmp/gradio/d3d50f42413a4e5874e7643bb8d39b8e761e0e41/image.png
landmark Det:: 100%|██████████████████████████████| 1/1 [00:00<00:00, 15.60it/s]
3DMM Extraction In Video:: 100%|██████████████████| 1/1 [00:00<00:00, 75.37it/s]
using ref video for genreation
3DMM Extraction for the reference video providing pose
landmark Det:: 100%|██████████████████████████| 751/751 [00:53<00:00, 14.16it/s]
3DMM Extraction In Video:: 100%|██████████████| 751/751 [00:10<00:00, 73.24it/s]
Traceback (most recent call last):
  File "/root/SadTalker/venv/lib/python3.8/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/SadTalker/venv/lib/python3.8/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/root/SadTalker/venv/lib/python3.8/site-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/SadTalker/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/SadTalker/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/SadTalker/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/SadTalker/src/gradio_demo.py", line 125, in test
    raise('error in refinfo')
TypeError: exceptions must derive from BaseException

**Comment by Odelialan** [comment]
File "/root/SadTalker/src/gradio_demo.py", line 125, in test
raise('error in refinfo')----->raise Exception('error in refinfo')
