### ISSUE TITLE
 raise IOError(msg)   OSError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Hanshere1122** [Winfredy/SadTalker#845]
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1/extensions/SadTalker\src\gradio_demo.py", line 139, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess, img_size=size)
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1/extensions/SadTalker\src\facerender\animate.py", line 205, in generate
    imageio.mimsave(path, result,  fps=float(25))
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\imageio\v2.py", line 484, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\imageio\core\legacy_plugin_wrapper.py", line 253, in write
    writer.append_data(image, metadata)
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\imageio\core\format.py", line 590, in append_data
    return self._append_data(im, total_meta)
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\imageio\plugins\ffmpeg.py", line 600, in _append_data
    self._write_gen.send(im)
  File "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\imageio_ffmpeg\_io.py", line 637, in write_frames
    raise IOError(msg)
OSError: [Errno 32] Broken pipe

FFMPEG COMMAND:
D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\imageio_ffmpeg\binaries\ffmpeg-win64-v4.2.2.exe -y -f rawvideo -vcodec rawvideo -s 256x256 -pix_fmt rgb24 -r 25.00 -i - -an -vcodec libx264 -pix_fmt yuv420p -v warning D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\results\19af39a2-909c-4a83-b20b-aabb730512c8\temp_tmptmzgpvno##https___ysharma-openai-tts-new.hf.space_--replicas_nohef_file_tmp_gradio_4aa9884c0a9725de596a65c53c8ee5e90b3de24b_tmpzmm3qphs-0-100.mp4

FFMPEG STDERR OUTPUT:

**Comment by asadullahnaeem** [comment]
Had the same error. Shortening the save path length solved this issue..

**Comment by AppStolz** [comment]
> Traceback (letzter Aufruf zuletzt): Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\routes.py ", Zeile 488, in run_predict Output = waiting app.get_blocks().process_api( Datei "D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib \site-packages\gradio\blocks.py“, Zeile 1431, in process_api result = waiting self.call_function( Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4 .6.1\python\lib\site-packages\gradio\blocks.py“, Zeile 1103, in Call_Function Prediction = Wait Anyio.to_Thread.run_sync( Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5 \sd-webui-aki-v4.6.1\python\lib\site-packages\anyio\to_thread.py“, Zeile 31, in run_sync return waiting get_asynclib().run_sync_in_worker_thread( Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd- webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\anyio_backends_asyncio.py“, Zeile 937, in run_sync_in_worker_thread returnwaite zukünftige Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd- webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\anyio_backends_asyncio.py“, Zeile 867, in run result = context.run(func, *args) Datei „D :\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\utils.py“, Zeile 707, in Wrapper- Antwort = f( *args, **kwargs) Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\modules\call_queue.py“, Zeile 13, in f res = func(*args, **kwargs) Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1/extensions/SadTalker\src\gradio_demo.py“, Zeile 139, im Test return_path = self.animate_from_coeff.generate(data, save_dir, pic_path, crop_info, Enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess, img_size=size) Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui -aki-v4.5\sd-webui-aki-v4.6.1/extensions/SadTalker\src\facerender\animate.py“, Zeile 205, in generic imageio.mimsave(path, result, fps=float(25)) Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\imageio\v2.py“, Zeile 484, in Mimwrite- Rückgabe file.write(ims, is_batch=True, **kwargs) Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages \imageio\core\legacy_plugin_wrapper.py“, Zeile 253, in write write.append_data(image, metadata) Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\imageio\core\format.py“, Zeile 590, in append_data return self._append_data(im, total_meta) Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\imageio\plugins \ffmpeg.py“, Zeile 600, in _append_data self._write_gen.send(im) Datei „D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\ lib\site-packages\imageio_ffmpeg_io.py“, Zeile 637, in write_frames löst IOError(msg) OSError aus: [Errno 32] Broken Pipe
> 
> FFMPEG-BEFEHL: D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\imageio_ffmpeg\binaries\ffmpeg-win64-v4.2.2. exe -y -f rawvideo -vcodec rawvideo -s 256x256 -pix_fmt rgb24 -r 25.00 -i - -an -vcodec libx264 -pix_fmt yuv420p -v warning D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd -Webui-aki-v4.6.1 \ Ergebnisse \ 19AF39A2-909C-4A83-B20B-AABB730512C8 \ TEMP_TMPTMZGPVNO ## HTTPS ___ YSHARMA-OPENAI-TTS-NEW.SPACE _. 5DE596A65C53C8EE5E90B3DE24B_TMPZMM3QPHS-0-100.MP4
> 
> FFMPEG STDERR-AUSGABE:

### Troubleshooting Steps:

1. **Check ffmpeg Installation**:
   - Ensure that `ffmpeg` is correctly installed and can be used by `imageio`.
   - You can check this by running the `ffmpeg` command in your command prompt:
     ```
     D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\python\lib\site-packages\imageio_ffmpeg\binaries\ffmpeg-win64-v4.2.2.exe
     ```
   - If `ffmpeg` isn't working correctly, consider reinstalling it or using a newer version.

2. **Temporary Files**:
   - The path to the temporary file used by `imageio` appears to be very long and contains special characters (`#`, `___`, `HTTPS`, etc.). This might cause issues.
   - Try shortening the path or removing special characters.

3. **Image Size and Format**:
   - Check if the image size and pixel format you're using are supported by `ffmpeg`. The error log indicates that the pixel format `rgb24` followed by `yuv420p` is being used, which should generally work, but it might be helpful to try other formats.

4. **Logs**:
   - It would be beneficial to see the `STDERR` output from `ffmpeg`. Unfortunately, it's not included in your excerpt. This output could provide further clues about the issue.

5. **Gradio and Imageio Version**:
   - Ensure you are using the latest version of `Gradio` and `imageio`. An update might fix the issue.

6. **Disk Space**:
   - Ensure there is sufficient disk space on your system, especially in the target directory (`D:\BaiduNetdiskDownload\QiuYeStableDiffusion\sd-webui-aki-v4.5\sd-webui-aki-v4.6.1\ Ergebnisse \ 19AF39A2-909C-4A83-B20B-AABB730512C8`).
