### ISSUE TITLE
I need help. Install Question

### ISSUE THREAD

**Issue by restrained-sober** [Winfredy/SadTalker#846]
To create a public link, set `share=True` in `launch()`.
Startup time: 10.3s (import torch: 1.1s, import gradio: 1.0s, import ldm: 0.3s, other imports: 0.6s, setup codeformer: 0.2s, load scripts: 1.4s, create ui: 2.9s, gradio launch: 2.4s, scripts app_started_callback: 0.4s).
Traceback (most recent call last):
  File "E:\SD2\SD\Python310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\SD2\SD\Python310\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\SD2\SD\Python310\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\SD2\SD\Python310\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "E:\SD2\SD\Python310\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'
Traceback (most recent call last):
  File "E:\SD2\SD\Python310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\SD2\SD\Python310\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\SD2\SD\Python310\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\SD2\SD\Python310\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "E:\SD2\SD\Python310\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

**Comment by sonukumar2** [comment]
Sadtalkerai.com
