### ISSUE TITLE
AttributeError: 'Row' object has no attribute 'style'

### ISSUE THREAD

**Issue by DevLenn** [Winfredy/SadTalker#853]
I get the following error by running the webui.bat in anaconda on windows:

Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "Launcher.py", line 204, in <module>
    start()
  File "Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "D:\Podcast\ai-video\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

**Comment by IamTalos** [comment]
Same error, any luck?

**Comment by DevLenn** [comment]
@IamTalos nope

**Comment by FMaz008** [comment]
I submitted a pull request fixing those issues:
https://github.com/OpenTalker/SadTalker/pull/857

**Comment by Zaosusu** [comment]
try ：pip install gradio==3.50.0

**Comment by wcai-git** [comment]
fix gr.Row().style(equal_height=False): to gr.Row(equal_height=False):

**Comment by Juranik** [comment]
I fixed this error,
let me show u, look:

1. venv\Scripts\activate
2. pip install gradio==3.46.1
3. in <app_sadtalker.py> change code: gr.Row().style(equal_height=False): >> gr.Row(equal_height=False):
4. python launcher.py
Congrats!

**Comment by X-Airlines** [comment]
> 4\. python launcher.py

Traceback (most recent call last):
  File "C:\Users\acikg\Desktop\SadTalker\launcher.py", line 204, in <module>
    start()
  File "C:\Users\acikg\Desktop\SadTalker\launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\Users\acikg\Desktop\SadTalker\app_sadtalker.py", line 40, in sadtalker_demo
    source_image = gr.Image(label="Source image", source="upload", type="filepath", elem_id="img2img_image").style(width=512)
  File "C:\Users\acikg\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
    return fn(self, **kwargs)
TypeError: Image.__init__() got an unexpected keyword argument 'source'

**Comment by Explorographer** [comment]
Made those changes and same error here.

**Comment by FMaz008** [comment]
Guys, look at the changes in my PR above and reproduce these.

**Comment by Explorographer** [comment]
What?!

**Comment by FMaz008** [comment]
> What?!

https://github.com/OpenTalker/SadTalker/pull/857

More specifically: https://github.com/OpenTalker/SadTalker/pull/857/commits/a84ff25ec16152af13c12f18ae2a68341ee2d582

**Comment by HebatullahHesham** [comment]
> I fixed this error, let me show u, look:
> 
> 1. venv\Scripts\activate
> 2. pip install gradio==3.46.1
> 3. in <app_sadtalker.py> change code: gr.Row().style(equal_height=False): >> gr.Row(equal_height=False):
> 4. python launcher.py
>    Congrats!

Please How to use SadTalker gradio WebUI on kaggle notebook by connecting it with Ngrok?

Please, I need help. Here is the code I run on cells for using SadTalker on Kaggle that doesn't lead me to use the WebUI:

 !git clone https://github.com/vinthony/SadTalker.git
%cd SadTalker
!pip install -r requirements.txt
!bash scripts/download_models.sh
!bash webui.sh
It always appears to be the same issue again and again, even if I try to install, upgrade, or downgrade a specific Gradio version.

File "app_sadtalker.py", line 35, in sadtalker_demo
with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

I have solved this issue on my local device by installing the required Python version, which was 3.10.6, uninstalling other versions on my device, and making sure to delete the remaining corrupted files from the older version so it can be fixed if there is a conflict with the other version.

I really appreciate your help because I have asked ChatGPT, and it was absolutely dumb.

**Comment by HebatullahHesham** [comment]
Please How to use SadTalker gradio WebUI on kaggle notebook by connecting it with Ngrok?

Please, I need help. Here is the code I run on cells for using SadTalker on Kaggle that doesn't lead me to use the WebUI:

1. !git clone https://github.com/vinthony/SadTalker.git
2. %cd SadTalker
3. !pip install -r requirements.txt
4. !bash scripts/download_models.sh
5. !bash webui.sh

It always appears to be the same issue again and again, even if I try to install, upgrade, or downgrade a specific Gradio version.

File "app_sadtalker.py", line 35, in sadtalker_demo
with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

I have solved this issue on my local device by installing the required Python version, which was 3.10.6, uninstalling other versions on my device, and making sure to delete the remaining corrupted files from the older version so it can be fixed if there is a conflict with the other version.

I really appreciate your help because I have asked ChatGPT, and it was absolutely dumb.
