### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by hfchensq1** [Winfredy/SadTalker#86]
after this period,i encountered this problem

landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:07<00:00,  7.60s/it]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.56it/s]
mel:: 100%|██████████████████████████████████████████████████████████████████████| 260/260 [00:00<00:00, 130351.31it/s]
audio2exp:: 100%|█████████████████████████████████████████████████████████████████████| 26/26 [00:00<00:00, 159.94it/s]
Face Renderer:: 100%|████████████████████████████████████████████████████████████████| 130/130 [00:32<00:00,  4.03it/s]
'ffmpeg' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "D:\program\PYTHON\3.10.6\lib\shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'b6ffde0c-a0ae-4a2b-aaf6-a72dc5ead92d.mp4' -> './results/49449804-b73a-478a-9dcc-82fe052fec15\\tmpisc4k0zj##itosinger19oytncd1.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\program\PYTHON\3.10.6\Lib\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\program\PYTHON\3.10.6\Lib\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\program\PYTHON\3.10.6\Lib\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\program\PYTHON\3.10.6\Lib\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\program\PYTHON\3.10.6\Lib\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\program\PYTHON\3.10.6\Lib\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\stablediffuion\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "F:\stablediffuion\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 121, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "F:\stablediffuion\stable-diffusion-webui/extensions/SadTalker\src\facerender\animate.py", line 183, in generate
    save_video_with_watermark(path, new_audio_path, av_path, watermark= None)
  File "F:\stablediffuion\stable-diffusion-webui/extensions/SadTalker\src\utils\videoio.py", line 26, in save_video_with_watermark
    shutil.move(temp_file, save_path)
  File "D:\program\PYTHON\3.10.6\lib\shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "D:\program\PYTHON\3.10.6\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "D:\program\PYTHON\3.10.6\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'b6ffde0c-a0ae-4a2b-aaf6-a72dc5ead92d.mp4'

i use wav format audio.sadtalker embedded in stable diffusion.
what happend?

**Comment by hfchensq1** [comment]
i installed ffmpeg

Requirement already satisfied: ffmpeg in d:\program\python\3.10.6\lib\site-packages (1.4)

**Comment by zhoubx** [comment]
问题解决了吗？我也是用的sd插件，也遇到了同样的问题

**Comment by hfchensq1** [comment]
> 问题解决了吗？我也是用的sd插件，也遇到了同样的问题，不过我是在阿里云的服务器上，是linux系统

解决了 不过是windows 安装了然后配置下系统路径就好了

**Comment by asdzdr** [comment]
怎么配置系统路径啊
