### ISSUE TITLE
modify  src/face3d/util/my_awing_arch.py line:18 

### ISSUE THREAD

**Issue by 576196565** [Winfredy/SadTalker#861]
File "/data/stable-diffusion-webui-1.8/extensions/SadTalker/src/face3d/util/my_awing_arch.py", line 18, in calculate_points
    preds = preds.astype(np.float, copy=False)
modify  preds = preds.astype(np.float32, copy=False)
ERROR:
3DMM Extraction In Video::   0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/stable-diffusion-webui-1.8/VENV/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/data/stable-diffusion-webui-1.8/VENV/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/data/stable-diffusion-webui-1.8/VENV/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/data/stable-diffusion-webui-1.8/VENV/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/data/stable-diffusion-webui-1.8/VENV/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/data/stable-diffusion-webui-1.8/VENV/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/data/stable-diffusion-webui-1.8/VENV/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/data/stable-diffusion-webui-1.8/modules/call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "/data/stable-diffusion-webui-1.8/extensions/SadTalker/src/gradio_demo.py", line 96, in test
    first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir, preprocess, True, size)
  File "/data/stable-diffusion-webui-1.8/extensions/SadTalker/src/utils/preprocess.py", line 146, in generate
    trans_params, im1, lm1, _ = align_img(frame, lm1, self.lm3d_std)
  File "/data/stable-diffusion-webui-1.8/extensions/SadTalker/src/face3d/util/preprocess.py", line 101, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

**Comment by LostQuant** [comment]
Same issues as above, it first complains about np.float is depreciated. Then we change to naive float and restart, and it complains about this inhomogeneous shape.
