### ISSUE TITLE
Help! I met this issue : File "Launcher.py", line 203, in <module>

### ISSUE THREAD

**Issue by Freyzheng2020** [Winfredy/SadTalker#871]
Commit hash: <none>
Installing requirements for SadTalker WebUI (may take longer time in first time)
Traceback (most recent call last):
  File "Launcher.py", line 203, in <module>
    prepare_environment()
  File "Launcher.py", line 189, in prepare_environment
    run_pip(f"install -r \"{requirements_file}\"", "requirements for SadTalker WebUI (may take longer time in first time)")
  File "Launcher.py", line 118, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "Launcher.py", line 86, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for SadTalker WebUI (may take longer time in first time).

**Comment by Freyzheng2020** [comment]
[launcher.zip](https://github.com/OpenTalker/SadTalker/files/15023245/launcher.zip)
