### ISSUE TITLE
报这个错误不知道如何处理

### ISSUE THREAD

**Issue by kevinli83** [Winfredy/SadTalker#874]
![Uploading error.png…]()

**Comment by kevinli83** [comment]
To create a public link, set `share=True` in `launch()`.
WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!
{'wav2lip_checkpoint': 'checkpoints\\wav2lip.pth', 'audio2pose_checkpoint': 'checkpoints\\auido2pose_00140-model.pth', 'audio2exp_checkpoint': 'checkpoints\\auido2exp_00300-model.pth', 'free_view_checkpoint': 'checkpoints\\facevid2vid_00189-model.pth.tar', 'path_of_net_recon_model': 'checkpoints\\epoch_20.pth', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'src/config\\auido2exp.yaml', 'use_safetensor': False, 'mappingnet_checkpoint': 'checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'src/config\\facerender.yaml'}
Traceback (most recent call last):
  File "D:\AI\SadTalker\src\test_audio2coeff.py", line 48, in __init__
    load_cpk(sadtalker_path['audio2pose_checkpoint'], model=self.audio2pose_model, device=device)
  File "D:\AI\SadTalker\src\test_audio2coeff.py", line 17, in load_cpk
    checkpoint = torch.load(checkpoint_path, map_location=torch.device(device))
  File "D:\AI\SadTalker\venv\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\AI\SadTalker\venv\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\AI\SadTalker\venv\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints\\auido2pose_00140-model.pth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "D:\AI\SadTalker\venv\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\AI\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "D:\AI\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\SadTalker\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\AI\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "D:\AI\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\AI\SadTalker\venv\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI\SadTalker\src\gradio_demo.py", line 48, in test
    self.audio_to_coeff = Audio2Coeff(self.sadtalker_paths, self.device)
  File "D:\AI\SadTalker\src\test_audio2coeff.py", line 50, in __init__
    raise Exception("Failed in loading audio2pose_checkpoint")
Exception: Failed in loading audio2pose_checkpoint

**Comment by 0xZZSheep** [comment]
https://github.com/OpenTalker/SadTalker?tab=readme-ov-file#2-download-models
要先执行这个脚本下载模型
```
bash scripts/download_models.sh
```
