### ISSUE TITLE
执行推理代码出错，救我

### ISSUE THREAD

**Issue by xiaolong-li1** [Winfredy/SadTalker#876]
(SadTalker) D:\Program Files\Pycharm_Projects\SadTalker>python inference.py --driven_audio "D:\Program Files\Pycharm_Projects\SadTalker\property\voice1.wav" --source_image "D:\Program Files\Pycharm_Projects\SadTalker\property\p1.jpg" --result_dir "D:\Program Files\Pycharm_Projects\SadTalker\property\result" --still --preprocess full --enhancer gfpgan
./checkpoints\epoch_20.pth
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 55, in main
    preprocess_model = CropAndExtract(path_of_lm_croper, path_of_net_recon_model, dir_of_BFM_fitting, device)
  File "D:\Program Files\Pycharm_Projects\SadTalker\src\utils\preprocess.py", line 46, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "D:\Program Files\Pycharm_Projects\SadTalker\src\face3d\extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device=device)
  File "C:\Users\32081\miniconda3\envs\SadTalker\lib\enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

**Comment by jnchen** [comment]
怎么解决的？
