### ISSUE TITLE
ubuntu22.04上部署，看起来是安装TTS出错了

### ISSUE THREAD

**Issue by hanqingchina** [Winfredy/SadTalker#878]
(base) x@x-home:~/SadTalker$ bash webui.sh

################################################################
Install script for SadTalker + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on x user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launcher.py...
################################################################
Python 3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:47:35) 
[GCC 12.3.0]
Commit hash: cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8
Installing requirements for SadTalker WebUI (may take longer time in first time)
Installing install TTS individually in SadTalker, which might not work on windows.
Traceback (most recent call last):
  File "launcher.py", line 203, in <module>
    prepare_environment()
  File "launcher.py", line 192, in prepare_environment
    run_pip(f"install TTS", "install TTS individually in SadTalker, which might not work on windows.")
  File "launcher.py", line 118, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "launcher.py", line 86, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install install TTS individually in SadTalker, which might not work on windows..
Command: "/home/han/SadTalker/venv/bin/python3" -m pip install TTS --prefer-binary
Error code: 2
stdout: Collecting TTS
  Using cached TTS-0.14.3-cp38-cp38-manylinux1_x86_64.whl (739 kB)
Collecting bnunicodenormalizer==0.1.1
  Using cached bnunicodenormalizer-0.1.1.tar.gz (38 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting bnnumerizer
  Using cached bnnumerizer-0.0.2.tar.gz (4.7 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting unidic-lite==1.0.8
  Using cached unidic-lite-1.0.8.tar.gz (47.4 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting transformers
  Using cached transformers-4.40.0-py3-none-any.whl (9.0 MB)
Requirement already satisfied: packaging in ./venv/lib/python3.8/site-packages (from TTS) (24.0)
Requirement already satisfied: librosa==0.10.0.* in ./venv/lib/python3.8/site-packages (from TTS) (0.10.0.post2)
Collecting umap-learn==0.5.1
  Using cached umap-learn-0.5.1.tar.gz (80 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting trainer==0.0.20
  Using cached trainer-0.0.20-py3-none-any.whl (45 kB)
Collecting pypinyin
  Using cached pypinyin-0.51.0-py2.py3-none-any.whl (1.4 MB)
Collecting g2pkk>=0.1.1
  Using cached g2pkk-0.1.2-py3-none-any.whl (25 kB)
Collecting anyascii
  Using cached anyascii-0.3.2-py3-none-any.whl (289 kB)
Collecting k-diffusion
  Using cached k_diffusion-0.1.1.post1-py3-none-any.whl (33 kB)
Requirement already satisfied: matplotlib in ./venv/lib/python3.8/site-packages (from TTS) (3.7.5)
Requirement already satisfied: pandas in ./venv/lib/python3.8/site-packages (from TTS) (2.0.3)
Collecting jieba
  Using cached jieba-0.42.1.tar.gz (19.2 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pyyaml in ./venv/lib/python3.8/site-packages (from TTS) (6.0.1)
Collecting pysbd
  Using cached pysbd-0.3.4-py3-none-any.whl (71 kB)
Collecting jamo
  Using cached jamo-0.4.1-py3-none-any.whl (9.5 kB)
Requirement already satisfied: scipy>=1.4.0 in ./venv/lib/python3.8/site-packages (from TTS) (1.10.1)
Collecting bangla==0.0.2
  Using cached bangla-0.0.2-py2.py3-none-any.whl (6.2 kB)
Requirement already satisfied: numba==0.55.1 in ./venv/lib/python3.8/site-packages (from TTS) (0.55.1)
Requirement already satisfied: tqdm in ./venv/lib/python3.8/site-packages (from TTS) (4.66.2)
Requirement already satisfied: torch>=1.7 in ./venv/lib/python3.8/site-packages (from TTS) (1.12.1+cu113)
Requirement already satisfied: fsspec>=2021.04.0 in ./venv/lib/python3.8/site-packages (from TTS) (2024.3.1)
Collecting flask
  Using cached flask-3.0.3-py3-none-any.whl (101 kB)
Collecting inflect==5.6.0
  Using cached inflect-5.6.0-py3-none-any.whl (33 kB)
Collecting einops
  Using cached einops-0.7.0-py3-none-any.whl (44 kB)
Collecting mecab-python3==1.0.5
  Using cached mecab_python3-1.0.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (577 kB)
Collecting cython==0.29.28
  Using cached Cython-0.29.28-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
Requirement already satisfied: numpy==1.21.6 in ./venv/lib/python3.8/site-packages (from TTS) (1.21.6)
Collecting coqpit>=0.0.16
  Using cached coqpit-0.0.17-py3-none-any.whl (13 kB)
Requirement already satisfied: torchaudio in ./venv/lib/python3.8/site-packages (from TTS) (0.12.1+cu113)
Collecting aiohttp
  Using cached aiohttp-3.9.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
Collecting nltk
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Requirement already satisfied: soundfile in ./venv/lib/python3.8/site-packages (from TTS) (0.12.1)
Collecting gruut[de,es,fr]==2.2.3
  Using cached gruut-2.2.3.tar.gz (73 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting Babel<3.0.0,>=2.8.0
  Using cached Babel-2.14.0-py3-none-any.whl (11.0 MB)
Collecting dateparser~=1.1.0
  Using cached dateparser-1.1.8-py2.py3-none-any.whl (293 kB)
Collecting gruut-ipa<1.0,>=0.12.0
  Using cached gruut-ipa-0.13.0.tar.gz (101 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting gruut_lang_en~=2.0.0
  Using cached gruut_lang_en-2.0.0.tar.gz (15.2 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting jsonlines~=1.2.0
  Using cached jsonlines-1.2.0-py2.py3-none-any.whl (7.6 kB)
Collecting networkx<3.0.0,>=2.5.0
  Using cached networkx-2.8.8-py3-none-any.whl (2.0 MB)
Collecting num2words<1.0.0,>=0.5.10
  Using cached num2words-0.5.13-py3-none-any.whl (143 kB)
Collecting python-crfsuite~=0.9.7
  Using cached python_crfsuite-0.9.10-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Requirement already satisfied: importlib_resources in ./venv/lib/python3.8/site-packages (from gruut[de,es,fr]==2.2.3->TTS) (6.4.0)
Collecting gruut_lang_es~=2.0.0
  Using cached gruut_lang_es-2.0.0.tar.gz (31.4 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting gruut_lang_de~=2.0.0
  Using cached gruut_lang_de-2.0.0.tar.gz (18.1 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting gruut_lang_fr~=2.0.0
  Using cached gruut_lang_fr-2.0.2.tar.gz (10.9 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: scikit-learn>=0.20.0 in ./venv/lib/python3.8/site-packages (from librosa==0.10.0.*->TTS) (1.1.3)
Requirement already satisfied: decorator>=4.3.0 in ./venv/lib/python3.8/site-packages (from librosa==0.10.0.*->TTS) (5.1.1)
Requirement already satisfied: soxr>=0.3.2 in ./venv/lib/python3.8/site-packages (from librosa==0.10.0.*->TTS) (0.3.7)
Requirement already satisfied: lazy-loader>=0.1 in ./venv/lib/python3.8/site-packages (from librosa==0.10.0.*->TTS) (0.4)
Requirement already satisfied: msgpack>=1.0 in ./venv/lib/python3.8/site-packages (from librosa==0.10.0.*->TTS) (1.0.8)
Requirement already satisfied: audioread>=2.1.9 in ./venv/lib/python3.8/site-packages (from librosa==0.10.0.*->TTS) (3.0.1)
Requirement already satisfied: typing-extensions>=4.1.1 in ./venv/lib/python3.8/site-packages (from librosa==0.10.0.*->TTS) (4.11.0)
Requirement already satisfied: joblib>=0.14 in ./venv/lib/python3.8/site-packages (from librosa==0.10.0.*->TTS) (1.1.0)
Requirement already satisfied: pooch<1.7,>=1.0 in ./venv/lib/python3.8/site-packages (from librosa==0.10.0.*->TTS) (1.6.0)
Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (from numba==0.55.1->TTS) (56.0.0)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in ./venv/lib/python3.8/site-packages (from numba==0.55.1->TTS) (0.38.1)
Collecting psutil
  Using cached psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
Collecting protobuf<3.20,>=3.9.2
  Using cached protobuf-3.19.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Collecting tensorboardX
  Using cached tensorboardX-2.6.2.2-py2.py3-none-any.whl (101 kB)
Collecting pynndescent>=0.5
  Using cached pynndescent-0.5.12-py3-none-any.whl (56 kB)
Requirement already satisfied: cffi>=1.0 in ./venv/lib/python3.8/site-packages (from soundfile->TTS) (1.16.0)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.8/site-packages (from aiohttp->TTS) (23.2.0)
Collecting async-timeout<5.0,>=4.0
  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.4.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (240 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.9.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (308 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (129 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: Jinja2>=3.1.2 in ./venv/lib/python3.8/site-packages (from flask->TTS) (3.1.3)
Requirement already satisfied: Werkzeug>=3.0.0 in ./venv/lib/python3.8/site-packages (from flask->TTS) (3.0.2)
Requirement already satisfied: click>=8.1.3 in ./venv/lib/python3.8/site-packages (from flask->TTS) (8.1.7)
Collecting blinker>=1.6.2
  Using cached blinker-1.7.0-py3-none-any.whl (13 kB)
Collecting itsdangerous>=2.1.2
  Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Requirement already satisfied: importlib-metadata>=3.6.0 in ./venv/lib/python3.8/site-packages (from flask->TTS) (7.1.0)
Requirement already satisfied: Pillow in ./venv/lib/python3.8/site-packages (from k-diffusion->TTS) (10.3.0)
Requirement already satisfied: torchvision in ./venv/lib/python3.8/site-packages (from k-diffusion->TTS) (0.13.1+cu113)
Collecting torchdiffeq
  Using cached torchdiffeq-0.2.3-py3-none-any.whl (31 kB)
Requirement already satisfied: scikit-image in ./venv/lib/python3.8/site-packages (from k-diffusion->TTS) (0.19.3)
Collecting dctorch
  Using cached dctorch-0.1.2-py3-none-any.whl (2.3 kB)
Requirement already satisfied: safetensors in ./venv/lib/python3.8/site-packages (from k-diffusion->TTS) (0.4.3)
Collecting clip-anytorch
  Using cached clip_anytorch-2.6.0-py3-none-any.whl (1.4 MB)
Collecting torchsde
  Using cached torchsde-0.2.6-py3-none-any.whl (61 kB)
Requirement already satisfied: kornia in ./venv/lib/python3.8/site-packages (from k-diffusion->TTS) (0.6.8)
Collecting jsonmerge
  Using cached jsonmerge-1.9.2-py3-none-any.whl (19 kB)
Collecting torch>=1.7
  Using cached torch-2.2.2-cp38-cp38-manylinux1_x86_64.whl (755.5 MB)
Collecting accelerate
  Using cached accelerate-0.29.3-py3-none-any.whl (297 kB)
Collecting clean-fid
  Using cached clean_fid-0.1.35-py3-none-any.whl (26 kB)
Collecting wandb
  Using cached wandb-0.16.6-py3-none-any.whl (2.2 MB)
Collecting nvidia-cublas-cu12==12.1.3.1
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Collecting nvidia-cuda-cupti-cu12==12.1.105
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Requirement already satisfied: filelock in ./venv/lib/python3.8/site-packages (from torch>=1.7->TTS) (3.13.4)
Collecting nvidia-cuda-runtime-cu12==12.1.105
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸          634.9/823.6 kB 15.1 kB/s eta 0:00:13

stderr: ERROR: Exception:
Traceback (most recent call last):
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/home/han/miniconda3/envs/sadtalker/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/home/han/miniconda3/envs/sadtalker/lib/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/home/han/miniconda3/envs/sadtalker/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/han/miniconda3/envs/sadtalker/lib/python3.8/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/home/han/miniconda3/envs/sadtalker/lib/python3.8/ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/home/han/miniconda3/envs/sadtalker/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip

----------------------------------------
这个该怎么解决？PIP已经更新为24.0

**Comment by hanqingchina** [comment]
要不然就显示如下信息，哈希不对：
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
     ╸                                        15.5/731.7 MB 8.1 MB/s eta 0:01:29

stderr: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=1000.0)")': /simple/async-timeout/
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    nvidia-cudnn-cu12==8.9.2.26 from https://files.pythonhosted.org/packages/ff/74/a2e2be7fb83aaedec84f391f082cf765dfb635e7caa9b49065f73e4835d8/nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (from torch>=1.7->TTS):
        Expected sha256 5ccb288774fdfb07a7e7025ffec286971c06d8d7b4fb162525334616d7629ff9
             Got        96b8d7fb48cf1dd4e2fc85ffb31aee59260d18a890456af37287e41ad6d21b91

**Comment by hanqingchina** [comment]
现在是卡在这里不动了，下午卡了5-6个小时，结束进程再开，又卡在这里快两小时了，python进程显示有CPU占用：
Python 3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:47:35) 
[GCC 12.3.0]
Commit hash: cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8
Installing requirements for SadTalker WebUI (may take longer time in first time)
Installing install TTS individually in SadTalker, which might not work on windows.

![image](https://github.com/OpenTalker/SadTalker/assets/33996536/25f3ccbc-a4db-4fa1-8f4d-50ac522cc936)

**Comment by hanqingchina** [comment]
现在又是依赖问题了，也是第一次碰到

stderr: ERROR: Exception:
Traceback (most recent call last):
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/han/SadTalker/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 392, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000

**Comment by CaiNiaoZhangDY** [comment]
您好，请问这个问题解决了吗，我也是遇到了相同的问题

**Comment by hanqingchina** [comment]
> 您好，请问这个问题解决了吗，我也是遇到了相同的问题

没有啊，重装了两次都是一样依赖问题，放弃了

**Comment by kaisar945** [comment]
The Magic: `pip install git+https://github.com/notatallshaw/pip@prefer-conflicting-causes`

**Comment by p-eve** [comment]
+1 同样卡住了
