### ISSUE TITLE
Before it all had working for me, but when I decided restart webui, I'm started getting this error...Help pls!

### ISSUE THREAD

**Issue by Juranik** [Winfredy/SadTalker#882]
```
venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Commit hash: cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SadTalker\Launcher.py", line 199, in <module>
    start()
  File "C:\Users\Administrator\Desktop\SadTalker\Launcher.py", line 192, in start
    from app import sadtalker_demo
  File "C:\Users\Administrator\Desktop\SadTalker\app.py", line 3, in <module>
    from src.gradio_demo import SadTalker
  File "C:\Users\Administrator\Desktop\SadTalker\src\gradio_demo.py", line 3, in <module>
    from src.utils.preprocess import CropAndExtract
  File "C:\Users\Administrator\Desktop\SadTalker\src\utils\preprocess.py", line 9, in <module>
    from src.face3d.util.preprocess import align_img
  File "C:\Users\Administrator\Desktop\SadTalker\src\face3d\util\preprocess.py", line 5, in <module>
    from scipy.io import loadmat
  File "C:\Users\Administrator\Desktop\SadTalker\venv\lib\site-packages\scipy\io\__init__.py", line 98, in <module>
    from .matlab import loadmat, savemat, whosmat
  File "C:\Users\Administrator\Desktop\SadTalker\venv\lib\site-packages\scipy\io\matlab\__init__.py", line 45, in <module>
    from ._mio import loadmat, savemat, whosmat
  File "C:\Users\Administrator\Desktop\SadTalker\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 9, in <module>
    from ._mio4 import MatFile4Reader, MatFile4Writer
  File "C:\Users\Administrator\Desktop\SadTalker\venv\lib\site-packages\scipy\io\matlab\_mio4.py", line 8, in <module>
    import scipy.sparse
  File "C:\Users\Administrator\Desktop\SadTalker\venv\lib\site-packages\scipy\sparse\__init__.py", line 267, in <module>
    from ._csr import *
  File "C:\Users\Administrator\Desktop\SadTalker\venv\lib\site-packages\scipy\sparse\_csr.py", line 10, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import

Launch unsuccessful. Exiting.
```

**Comment by oisilener1982** [comment]
have you tried deleting the venv folder?

**Comment by Juranik** [comment]
> have you tried deleting the venv folder?

Hello, thank you for answer, I deleted this rep, but now, I'll try again to lauch it, thank you again for the answer, if I will let you know
