### ISSUE TITLE
 TypeError: 'ModelManager' object is not subscriptable

### ISSUE THREAD

**Issue by cxiaowen** [Winfredy/SadTalker#899]
python app_sadtalker.py
/home/xmg/anaconda3/envs/sadtalker/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/media/xmg/KINGSTON_4T/QY/SadTalker-main/app_sadtalker.py", line 107, in <module>
    demo = sadtalker_demo()
  File "/media/xmg/KINGSTON_4T/QY/SadTalker-main/app_sadtalker.py", line 49, in sadtalker_demo
    tts_talker = TTSTalker()
  File "/media/xmg/KINGSTON_4T/QY/SadTalker-main/src/utils/text2speech.py", line 8, in __init__
    model_name = TTS().list_models()[0]
TypeError: 'ModelManager' object is not subscriptable  这个是什么原因

**Comment by xuchaoguo1983** [comment]
cd home/xmg/anaconda3/envs/sadtalker/lib/python3.10/site-packages/TTS
vim api.py

go to function list_models and make changs as below:

def list_models(self):
        return ModelManager(models_file=TTS.get_models_file_path(), progress_bar=False, verbose=False).list_models()

**Comment by mahendrajakhar** [comment]
instead you can install by lowring it's version
or install using pip install coqui-tts
