### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object in preprocess.py

### ISSUE THREAD

**Issue by saymoon** [Winfredy/SadTalker#90]
I encountered an error while running the inference script with the following command:

```cmd
python inference.py --driven_audio C:\Users\user\develop\SadTalker\work\audio.mp3 --source_image C:\Users\user\develop\SadTalker\work\image.jpg
./checkpoints\epoch_20.pth
./checkpoints\auido2pose_00140-model.pth
./checkpoints\auido2exp_00300-model.pth
./checkpoints\facevid2vid_00189-model.pth.tar
./checkpoints\mapping_00229-model.pth.tar
3DMM Extraction for source image
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 72, in main
    first_coeff_path, crop_pic_path, crop_info =  preprocess_model.generate(pic_path, first_frame_dir, args.preprocess)
  File "C:\Users\user\develop\SadTalker\src\utils\preprocess.py", line 86, in generate
    x_full_frames, crop, quad = self.croper.crop(x_full_frames, still=True, xsize=pic_size)
TypeError: cannot unpack non-iterable NoneType object
```

OS: Windows 10
Python version: conda, 3.8
Please let me know if there's any additional information I can provide to help resolve this issue. Thank you!

**Comment by saymoon** [comment]
I have discovered the cause of the issue based on the best practice guidelines. The problem occurred because I was using a non-REAL person image as the source image. After replacing the source image with a real human image, the issue has been resolved.
