### ISSUE TITLE
这是什么错误

### ISSUE THREAD

**Issue by fzy1229** [Winfredy/SadTalker#906]
venv "venv\Scripts\Python.exe"
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Commit hash: cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Collecting torch==1.12.1+cu113
  Downloading https://download.pytorch.org/whl/cu113/torch-1.12.1%2Bcu113-cp38-cp38-win_amd64.whl (2143.5 MB)
     |████████████████████████████████| 2143.5 MB 1.5 kB/s
Collecting torchvision==0.13.1+cu113
  Downloading https://download.pytorch.org/whl/cu113/torchvision-0.13.1%2Bcu113-cp38-cp38-win_amd64.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 6.8 MB/s
Collecting torchaudio==0.12.1
  Downloading https://download.pytorch.org/whl/cu113/torchaudio-0.12.1%2Bcu113-cp38-cp38-win_amd64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 6.8 MB/s
Collecting typing-extensions
  Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Downloading https://download.pytorch.org/whl/pillow-10.2.0-cp38-cp38-win_amd64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB ...
Collecting numpy
  Downloading numpy-1.24.4-cp38-cp38-win_amd64.whl (14.9 MB)
     |██████▌                         | 3.1 MB 8.7 kB/s eta 0:22:39ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\34350\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 455, in read
    n = self.readinto(b)
  File "C:\Users\34350\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 499, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\34350\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\34350\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\34350\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\commands\install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 367, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 203, in _get_criteria_to_update
    name, crit = self._merge_into_criterion(r, parent=candidate)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 33, in _iter_built
    candidate = func()
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 200, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 306, in __init__
    super().__init__(
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 317, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 550, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 239, in unpack_url
    file = get_http_url(
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\network\download.py", line 157, in __call__
    for chunk in chunks:
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\cli\progress_bars.py", line 152, in iter
    for x in it:
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_internal\network\utils.py", line 62, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\34350\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\34350\SadTalker\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
WARNING: You are using pip version 21.1.1; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\34350\SadTalker\venv\Scripts\python.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "Launcher.py", line 203, in <module>
    prepare_environment()
  File "Launcher.py", line 187, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "Launcher.py", line 70, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "C:\Users\34350\SadTalker\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
Error code: 2

Launch unsuccessful. Exiting.

**Comment by Dtongh** [comment]
转战wav2lip吧！  上万高清中文数据集训练出来的256高清模型，含推理代码，oonx加速推理。
需要+V  tgfhzx666  看效果
