### ISSUE TITLE
who can help me

### ISSUE THREAD

**Issue by fzy1229** [Winfredy/SadTalker#909]
venv "venv\Scripts\Python.exe"
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Commit hash: cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Collecting torch==1.12.1+cu113
  Downloading https://download.pytorch.org/whl/cu113/torch-1.12.1%2Bcu113-cp38-cp38-win_amd64.whl (2143.5 MB)
     |████████████████████████████████| 2143.5 MB 408 bytes/s
Collecting torchvision==0.13.1+cu113
  Downloading https://download.pytorch.org/whl/cu113/torchvision-0.13.1%2Bcu113-cp38-cp38-win_amd64.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 3.3 MB/s
Collecting torchaudio==0.12.1
  Downloading https://download.pytorch.org/whl/cu113/torchaudio-0.12.1%2Bcu113-cp38-cp38-win_amd64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 3.3 MB/s
Collecting typing-extensions
  Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Collecting numpy
  Downloading numpy-1.24.4-cp38-cp38-win_amd64.whl (14.9 MB)
     |████████████████████████████████| 14.9 MB 273 kB/s
Collecting pillow!=8.3.*,>=5.3.0
  Downloading pillow-10.3.0-cp38-cp38-win_amd64.whl (2.5 MB)
     |████████████████████████████████| 2.5 MB 105 kB/s
Collecting requests
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 128 kB/s
Collecting idna<4,>=2.5
  Downloading idna-3.7-py3-none-any.whl (66 kB)
     |████████████████████████████████| 66 kB 139 kB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
     |████████████████████████████████| 163 kB 79 kB/s
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp38-cp38-win_amd64.whl (99 kB)
     |████████████████████████████████| 99 kB 79 kB/s
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 57 kB/s
Installing collected packages: urllib3, typing-extensions, idna, charset-normalizer, certifi, torch, requests, pillow, numpy, torchvision, torchaudio
Successfully installed certifi-2024.2.2 charset-normalizer-3.3.2 idna-3.7 numpy-1.24.4 pillow-10.3.0 requests-2.31.0 torch-1.12.1+cu113 torchaudio-0.12.1+cu113 torchvision-0.13.1+cu113 typing-extensions-4.11.0 urllib3-2.2.1
WARNING: You are using pip version 21.1.1; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\34350\SadTalker\venv\Scripts\python.exe -m pip install --upgrade pip' command.
Installing requirements for SadTalker WebUI (may take longer time in first time)
Traceback (most recent call last):
  File "Launcher.py", line 203, in <module>
    prepare_environment()
  File "Launcher.py", line 189, in prepare_environment
    run_pip(f"install -r \"{requirements_file}\"", "requirements for SadTalker WebUI (may take longer time in first time)")
  File "Launcher.py", line 118, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "Launcher.py", line 86, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for SadTalker WebUI (may take longer time in first time).
Command: "C:\Users\34350\SadTalker\venv\Scripts\python.exe" -m pip install -r "requirements.txt" --prefer-binary
Error code: 1
stdout: Collecting numpy==1.23.4
  Downloading numpy-1.23.4-cp38-cp38-win_amd64.whl (14.7 MB)
Collecting face_alignment==1.3.5
  Downloading face_alignment-1.3.5-py2.py3-none-any.whl (29 kB)
Collecting imageio==2.19.3
  Downloading imageio-2.19.3-py3-none-any.whl (3.4 MB)
Collecting imageio-ffmpeg==0.4.7
  Downloading imageio_ffmpeg-0.4.7-py3-none-win_amd64.whl (22.6 MB)
Collecting librosa==0.9.2
  Downloading librosa-0.9.2-py3-none-any.whl (214 kB)

stderr: ERROR: Could not find a version that satisfies the requirement numba (from versions: none)
ERROR: No matching distribution found for numba
WARNING: You are using pip version 21.1.1; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\34350\SadTalker\venv\Scripts\python.exe -m pip install --upgrade pip' command.

Launch unsuccessful. Exiting.

**Comment by xlxbj** [comment]
The pip version is too low. Run C:\Users\34350\SadTalker\venv\Scripts\python.exe -m pip install --upgrade pip in the console to solve the problem
