### ISSUE TITLE
help  TnT

### ISSUE THREAD

**Issue by dscr945** [Winfredy/SadTalker#923]
大佬，打扰您一下。我部署运行sadtalker报错结果是这个
Traceback (most recent call last):
  File "E:\SadTalker\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "E:\SadTalker\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "E:\SadTalker\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

**Comment by eoffermann** [comment]
Install 3.41.2 of gradio.

Back in 3.41.2, gradio.Row() had a style() method - it was deprecated but still existed. That method went away altogether in 4.
