### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu113 (from versions: 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1) ERROR: No matching distribution found for torch==1.12.1+cu113 Traceback (most recent call last):   File "D:\sad talker\SadTalker\Launcher.py", line 203, in <module>     prepare_environment()   File "D:\sad talker\SadTalker\Launcher.py", line 187, in prepare_environment     run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)   File "D:\sad talker\SadTalker\Launcher.py", line 70, in run     raise RuntimeError(f"""{errdesc or 'Error running command'}. RuntimeError: Couldn't install torch. Command: "D:\sad talker\SadTalker\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113 Error code: 1  Launch unsuccessful. Exiting.

### ISSUE THREAD

**Issue by panini0123** [Winfredy/SadTalker#926]
venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Commit hash: <none>
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu113 (from versions: 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1)
ERROR: No matching distribution found for torch==1.12.1+cu113
Traceback (most recent call last):
  File "D:\sad talker\SadTalker\Launcher.py", line 203, in <module>
    prepare_environment()
  File "D:\sad talker\SadTalker\Launcher.py", line 187, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "D:\sad talker\SadTalker\Launcher.py", line 70, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "D:\sad talker\SadTalker\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
Error code: 1

Launch unsuccessful. Exiting.

It shows this error when I try to open webui.bat, I followed this tutorial: https://www.youtube.com/watch?v=yEkLEm-10Mw&t=190s

what am I doing wrong?

**Comment by X-Airlines** [comment]
+1

**Comment by orkun41** [comment]
I think SadTalker did not compatible with python 3.11.9 try on python 3.10.9 version this works for me
