### ISSUE TITLE
New Updated Version Doesn't Work! 

### ISSUE THREAD

**Issue by davidraymondcross** [Winfredy/SadTalker#930]
Stop pretending like this works. I followed all the directions and tried 20 times. This does not work. It creates the same error every time. 

*** Error executing callback ui_tabs_callback for C:\Program Files\stable-diffusion\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py
    Traceback (most recent call last):
      File "C:\Program Files\stable-diffusion\stable-diffusion-webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Program Files\stable-diffusion\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 172, in on_ui_tabs
        from app_sadtalker import sadtalker_demo
      File "C:\Program Files\stable-diffusion\stable-diffusion-webui/extensions/SadTalker\app_sadtalker.py", line 3, in <module>
        from src.gradio_demo import SadTalker
      File "C:\Program Files\stable-diffusion\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 6, in <module>
        from src.generate_batch import get_data
      File "C:\Program Files\stable-diffusion\stable-diffusion-webui/extensions/SadTalker\src\generate_batch.py", line 8, in <module>
        import src.utils.audio as audio
      File "C:\Program Files\stable-diffusion\stable-diffusion-webui/extensions/SadTalker\src\utils\audio.py", line 1, in <module>
        import librosa
      File "C:\Program Files\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\librosa\__init__.py", line 211, in <module>
        from . import core
      File "C:\Program Files\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\librosa\core\__init__.py", line 9, in <module>
        from .constantq import *  # pylint: disable=wildcard-import
      File "C:\Program Files\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\librosa\core\constantq.py", line 1058, in <module>
        dtype=np.complex,
      File "C:\Program Files\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\numpy\__init__.py", line 338, in __getattr__
        raise AttributeError(__former_attrs__[attr])
    AttributeError: module 'numpy' has no attribute 'complex'.
    `np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
    The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
        https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

---
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 32.3s (prepare environment: 6.4s, import torch: 5.7s, import gradio: 2.5s, setup paths: 3.9s, initialize shared: 2.9s, other imports: 1.9s, load scripts: 1.1s, create ui: 7.2s, gradio launch: 0.8s).
Creating model from config: C:\Program Files\stable-diffusion\stable-diffusion-webui\configs\v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 15.7s (load weights from disk: 11.4s, create model: 0.4s, apply weights to model: 1.9s, calculate empty prompt: 1.9s).

I followed the steps - https://github.com/OpenTalker/SadTalker/blob/main/docs/webui_extension.md

I set my webui_user.bat to "set SADTALKER_CHECKPOINTS=(my file extension I put here)"

I installed FFmpeg prior to doing this. I changed the environment variables on the PC PATH to FFmpeg

I followed all the instructions that [vinthony] wrote and all the suggestions he made to other people with my problem. 

It is time VINTHONY to admit that your software is flawed and take it off the GIT Hub. It doesn't work. It may have used to work around a year ago, but it no longer works. Fix your instructions or remove your failed software.

**Comment by eoffermann** [comment]
This is inappropriate (and more than a little weird).

Lots of github projects fall out of sync with recent package updates when the original developers move on to other things. THis is especially true for academic research, and EVEN MORE SO with AI research the last few years. The people that create a research project like this usually have other research to do.

We are **_extremely fortunate_** that as part of publishing their research that people advancing technology in the space also release their models and code. We're doubly fortunate when they release it with a generous opensource license. SadTalker is free software in every sense of the word. The source is Apache 2.0 licensed, and nobody has to pay a dime for it. You can work with the software, modify the software, even advance the technology contained therein and claim patents on derivative projects.

The errors you're getting are because the libraries you're running are too recent and/or out of sync with each other. Sometimes that happens. You shouldn't come in and demand that somebody fix it for you or take the git repo offline, though. That's just silly.

If I were to guess based on your traceback, I'd say you're running the wrong version of _librosa_. I *think* if you uninstall _numpy_ and then `pip install librosa==0.9.2` it will correctly install the corresponding _numpy_ and _librosa_ versions you need. That said, it's fairly likely that you'll have other package versions to sort out but maybe that's the end of it.

Your post here is a good example of why each time someone else adapts the source for their environment, those dependency resolutions don't get pushed to the main project: because their specific needs may not be yours and those changes will just break things for someone else.

**Comment by oisilener1982** [comment]
Dont expect any update and fix from the devs. The main author of this project is very busy and collaborating with japanese ai researcher for another project. Sadtalker is dead but the fix is to backread a little

**Comment by davidraymondcross** [comment]
I already moved on to another working git in ComfyUI. People need to be warned. I spent over 8 hours of my life trying to install this. Nobody else should have to suffer my same fate. So anyone reading this just know there is no solution to make this work.

**Comment by oisilener1982** [comment]
You are wrong. Sadtalker is working fine in the latest version of auto 1111

**Comment by samuthub** [comment]
I'm done. (Windows11) but cannot use webui.bat

==My path==
D:\SadTalker\
D:\miniconda3\envs\sadtalker\


https://github.com/OpenTalker/SadTalker/assets/173276323/6415709d-8564-4928-a377-99d59317aefa

**Comment by samuthub** [comment]
I'm done. (Windows11) but cannot use webui.bat

=My path=
D:\SadTalker\
D:\SadTalker\checkpoints\
D:\SadTalker\gfpgan\weights\

=Environment=
D:\miniconda3\envs\sadtalker\

=How to install FFMPEG=
https://www.youtube.com/watch?v=YQuFqsNi2G4

https://github.com/OpenTalker/SadTalker/assets/173276323/504997ed-a78e-4e7e-82d5-084298faa998

**Comment by mustofakamal1** [comment]
Try this for each issue you have encountered:
1. `np.complex` error, run this in venv `pip install librosa==0.9.2`
2. `np.float` error at `extensions/SadTalker/src/face3d/util/my_awing_arch.py` line 18, change the code `preds = preds.astype(np.float, copy=False)` to `preds = preds.astype(float, copy=False)`
3. `ValueError: setting an array element with a sequence.` error at `extensions/SadTalker/src/face3d/util/preprocess.py`, change the code `trans_params = np.array([w0, h0, s, t[0], t[1]])` to `trans_params = np.array([w0, h0, s, t[0], t[1]], dtype="object")`

In my case, I encountered those issues, now it works. Hope it helps.
