### ISSUE TITLE
FFmpeg cannot edit existing files in-place. Please Help me.

### ISSUE THREAD

**Issue by kevin2862** [Winfredy/SadTalker#931]
Web UI cannot output files. It keeps displaying the same path repeatedly. How can I solve it?

-------
-------

C:\Users\a1003\AppData\Local\Temp\gradio\3ebeed406919a0d8689ff220b0fa3eb3f12d16f9\jstosun.png
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.29it/s]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 95.10it/s]
mel:: 100%|█████████████████████████████████████████████████████████████████████| 1469/1469 [00:00<00:00, 94625.31it/s]
audio2exp:: 100%|███████████████████████████████████████████████████████████████████| 147/147 [00:00<00:00, 391.50it/s]
Face Renderer:: 100%|████████████████████████████████████████████████████████████████| 735/735 [02:03<00:00,  5.95it/s]
The generated video is named ./results/a9eaacbc-e7f9-4a19-8d4f-40b47b3725c5/jstosun##429back.mp4
The generated video is named jstosun##429back in ./results/a9eaacbc-e7f9-4a19-8d4f-40b47b3725c5
ffmpeg version 7.0-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './results/a9eaacbc-e7f9-4a19-8d4f-40b47b3725c5\jstosun##429back.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.1.100
  Duration: 00:00:58.76, start: 0.000000, bitrate: 204 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 256x256, 110 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, stereo, fltp, 88 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
Output ./results/a9eaacbc-e7f9-4a19-8d4f-40b47b3725c5\jstosun##429back.mp4 same as Input #0 - exiting
FFmpeg cannot edit existing files in-place.
Error opening output file ./results/a9eaacbc-e7f9-4a19-8d4f-40b47b3725c5\jstosun##429back.mp4.
Error opening output files: Invalid argument
Traceback (most recent call last):
  File "C:\Users\a1003\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\a1003\SadTalker\venv\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\a1003\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1918, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\a1003\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1744, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\a1003\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 242, in postprocess
    processed_files = (self._format_video(value), None)
  File "C:\Users\a1003\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 314, in _format_video
    ff.run()
  File "C:\Users\a1003\SadTalker\venv\lib\site-packages\ffmpy.py", line 113, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -y -i ./results/a9eaacbc-e7f9-4a19-8d4f-40b47b3725c5\jstosun##429back.mp4 ./results/a9eaacbc-e7f9-4a19-8d4f-40b47b3725c5\jstosun##429back.mp4` exited with status 4294967274

STDOUT:

STDERR:

**Comment by SevenMpp** [comment]
Have you solved this problem?

**Comment by nicho2** [comment]
in test_audio2coeff.py

change ## with something other else (__ for me)

        
            savemat(os.path.join(coeff_save_dir, '%s__%s.mat'%(batch['pic_name'], batch['audio_name'])),
                    {'coeff_3dmm': coeffs_pred_numpy})

            return os.path.join(coeff_save_dir, '%s__%s.mat'%(batch['pic_name'], batch['audio_name']))
