### ISSUE TITLE
运行inference.py报错，求大神告知怎么解决

### ISSUE THREAD

**Issue by guo-huan** [Winfredy/SadTalker#945]
执行命令：python inference.py  --driven_audio  D:\SadTalker\examples\driven_audio\chinese_news.wav --source_image D:\SadTalker\examples\source_image\happy.png --enhancer gfpgan

报错：
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 55, in main
    preprocess_model = CropAndExtract(path_of_lm_croper, path_of_net_recon_model, dir_of_BFM_fitting, device)
  File "D:\SadTalker\src\utils\preprocess.py", line 46, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "D:\SadTalker\src\face3d\extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device=device)
  File "D:\anaconda3\envs\SadTalker_ENV\lib\enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

**Comment by guo-huan** [comment]
找到问题了，已解决

**Comment by nitinmukesh** [comment]
@guo-huan 

How did you fixed the issue?

**Comment by a907066892** [comment]
没有下载模型到checkpoints文件夹吧
