### ISSUE TITLE
现在哪个版本可以用?

### ISSUE THREAD

**Issue by xiaofanku** [Winfredy/SadTalker#949]
目前环境: python 3.10. cuda:12.1. 下0.2报错: `module compiled against API version 0xf but this version of numpy is 0xe`

main分支也报错: 
```
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "C:\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "C:\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.
请按任意键继续. . .
```

**Comment by xiaofanku** [comment]
随便 问一下可以实时流时输出吗?

**Comment by a907066892** [comment]
[app_sadtalker.zip](https://github.com/user-attachments/files/17001692/app_sadtalker.zip)
替换这个包里的py文件

**Comment by hixuco** [comment]
> [app_sadtalker.zip](https://github.com/user-attachments/files/17001692/app_sadtalker.zip) 替换这个包里的py文件
Thanks a lot, this really helps, also there are few other fixes needed with  gr.Audio and gr.Video,  mainly to remove the style

**Comment by cikiChe** [comment]
maybe you should see :https://www.youtube.com/watch?v=p5qPojr3cqA&t=339s
