### ISSUE TITLE
The login URL appears for me but I still get an error and cannot open it.

### ISSUE THREAD

**Issue by huahuaguoke** [Winfredy/SadTalker#950]
Running on local URL:  http://127.0.0.1:7861
Traceback (most recent call last):
  File "C:\Users\user002\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "C:\Users\user002\SadTalker\Launcher.py", line 200, in start
    demo.launch()
  File "C:\Users\user002\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 2456, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

Launch unsuccessful. Exiting.

**Comment by RushabhShahPrograms** [comment]
you should try this video for reference to configure sadtalker: [Youtube Video](https://www.youtube.com/watch?v=p5qPojr3cqA&t=339s)
