### ISSUE TITLE
SD extension webui error

### ISSUE THREAD

**Issue by pipixie7** [Winfredy/SadTalker#956]
using safetensor as default
{'checkpoint': 'A:\\SD\\sd-webui-aki-v4.7\\extensions\\SadTalker\\checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'A:\\SD\\sd-webui-aki-v4.7/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'A:\\SD\\sd-webui-aki-v4.7/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'A:\\SD\\sd-webui-aki-v4.7/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'A:\\SD\\sd-webui-aki-v4.7\\extensions\\SadTalker\\checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'A:\\SD\\sd-webui-aki-v4.7/extensions/SadTalker/src/config\\facerender.yaml'}
C:\Users\16696\AppData\Local\Temp\gradio\tmpjlix_686.png
Traceback (most recent call last):
  File "A:\SD\sd-webui-aki-v4.7\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "A:\SD\sd-webui-aki-v4.7\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "A:\SD\sd-webui-aki-v4.7\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "A:\SD\sd-webui-aki-v4.7\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "A:\SD\sd-webui-aki-v4.7\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "A:\SD\sd-webui-aki-v4.7\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "A:\SD\sd-webui-aki-v4.7\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "A:\SD\sd-webui-aki-v4.7\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "A:\SD\sd-webui-aki-v4.7/extensions/SadTalker\src\gradio_demo.py", line 96, in test
    first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir, preprocess, True, size)
  File "A:\SD\sd-webui-aki-v4.7/extensions/SadTalker\src\utils\preprocess.py", line 146, in generate
    trans_params, im1, lm1, _ = align_img(frame, lm1, self.lm3d_std)
  File "A:\SD\sd-webui-aki-v4.7/extensions/SadTalker\src\face3d\util\preprocess.py", line 101, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

what is this?  how to solve it?

**Comment by nitinmukesh** [comment]
Use Standalone version.
