### ISSUE TITLE
到--still这步出错了，不知道什么原因？full_video_path 要赋个初值？

### ISSUE THREAD

**Issue by paulzhang913** [Winfredy/SadTalker#98]
The generated video is named xiaolan##xiaolan.mp4 in C:\softz\SadTalker\2023_04_10_18.50.41
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 112, in main
    animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "C:\softz\SadTalker\src\facerender\animate.py", line 200, in generate
    enhanced_images = face_enhancer(full_video_path, method=enhancer, bg_upsampler=background_enhancer)
UnboundLocalError: local variable 'full_video_path' referenced before assignment

**Comment by vinthony** [comment]
可以更新一下代码
